### PR TITLE
Make it easy to write out PDB files for proposed kinase inhibitors

### PR DESCRIPTION
**Pull request by jchodera**
@pgrinaway: Try out 
```
python perses/tests/testsystems.pdb
```
and look at the generated `kinase-inhibitors-vacuum-geometry-proposals.pdb`, which writes out the geometry proposals.  Is this just the ring fusion problem?

### CODE REVIEW

**Comment by pgrinaway** [comment]
Taking a look now, one second

**Comment by pgrinaway** [comment]
I think it is ring fusion. I have a question though: when I turn on NCMC, I get this output:

```
initial potential before 'insert' : 13538.395445 kT
initial potential components:   [('HarmonicBondForce', Quantity(value=31949.706385135534, unit=kilojoule/mole)), ('HarmonicAngleForce', Quantity(value=1814.07441261312, unit=kilojoule/mole)), ('PeriodicTorsionForce', Quantity(value=230.24819006394338, unit=kilojoule/mole)), ('NonbondedForce', Quantity(value=-224.63759226001002, unit=kilojoule/mole)), ('CustomNonbondedForce', Quantity(value=27169.211513825056, unit=kilojoule/mole)), ('CustomNonbondedForce', Quantity(value=-439.06911405286445, unit=kilojoule/mole)), ('CustomBondForce', Quantity(value=1116661.8508893528, unit=kilojoule/mole)), ('CMMotionRemover', Quantity(value=0.0, unit=kilojoule/mole))]
final potential before 'insert' : 32983468.919008 kT
final potential components: [('HarmonicBondForce', Quantity(value=82209294.06504345, unit=kilojoule/mole)), ('HarmonicAngleForce', Quantity(value=10679.832434457665, unit=kilojoule/mole)), ('PeriodicTorsionForce', Quantity(value=460.86338915883505, unit=kilojoule/mole)), ('NonbondedForce', Quantity(value=47.02093321730854, unit=kilojoule/mole)), ('CustomNonbondedForce', Quantity(value=51615.17591995633, unit=kilojoule/mole)), ('CustomNonbondedForce', Quantity(value=-82.4948626941559, unit=kilojoule/mole)), ('CustomBondForce', Quantity(value=22.30294423444001, unit=kilojoule/mole)), ('CMMotionRemover', Quantity(value=0.0, unit=kilojoule/mole))]
```

What is confusing me is that `HarmonicBondForce` is the one with ridiculous energies. Obviously, the bond deformation would cause this, but then shouldn't the problem actually manifest in `CustomBondForce`? My understanding of what `AbsoluteAlchemicalFactory` does is that it only replaces forces for alchemical partners and their forces. So is this saying that the core atom bonds have insane energies? Working on generating a trajectory to take a look at as well.

**Comment by pgrinaway** [comment]
Note also that in that example, `CustomBondForce` calmed down a lot, as expected.

**Comment by pgrinaway** [comment]
Hm, not sure why `CustomAngleForce` is missing there, too. Maybe it's just not being printed out.

**Comment by jchodera** [comment]
I wonder if this is an indices problem, where the indices of alchemical atoms are getting screwed up somewhere before the `Custom*Force`s are created.  Looking into this now.

**Comment by pgrinaway** [comment]
Also, the `alchemical_system` ends up missing the `CustomAngleForce`:

```
[<simtk.openmm.openmm.HarmonicBondForce; proxy of <Swig Object of type 'OpenMM::HarmonicBondForce *' at 0x111fa7a20> >,
 <simtk.openmm.openmm.HarmonicAngleForce; proxy of <Swig Object of type 'OpenMM::HarmonicAngleForce *' at 0x111fa7960> >, 
<simtk.openmm.openmm.PeriodicTorsionForce; proxy of <Swig Object of type 'OpenMM::PeriodicTorsionForce *' at 0x111fa77b0> >,
 <simtk.openmm.openmm.NonbondedForce; proxy of <Swig Object of type 'OpenMM::NonbondedForce *' at 0x111fa7c60> >, 
<simtk.openmm.openmm.CustomNonbondedForce; proxy of <Swig Object of type 'OpenMM::CustomNonbondedForce *' at 0x111fa7a80> >, 
<simtk.openmm.openmm.CustomNonbondedForce; proxy of <Swig Object of type 'OpenMM::CustomNonbondedForce *' at 0x111fa76f0> >, 
<simtk.openmm.openmm.CustomBondForce; proxy of <Swig Object of type 'OpenMM::CustomBondForce *' at 0x111fa73f0> >,
 <simtk.openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x111fa7f30> >]
```

**Comment by jchodera** [comment]
Right now, we're not making the bonds, angles, or torsions involving alchemical atoms to be alchemically modified.  The [current code](https://github.com/choderalab/perses/blob/master/perses/annihilation/ncmc_switching.py#L234) just annihilates sterics and electrostatics.

We can turn the bond, angle, and torsion annihilation on if we set [options](https://github.com/choderalab/alchemy/blob/master/alchemy/alchemy.py#L220-L222) `alchemical_torsions`, `alchemical_angles`, and `alchemical_bonds`.  If we set these to `True`, it will be any term that involves alchemical atoms---is that what we want?  Or do we want to specify particular terms?

**Comment by jchodera** [comment]
Note that the `CustomBondForce` that is included now is just 1,4 exceptions for `CustomNonbondedForce`.

**Comment by pgrinaway** [comment]
Oh! Sorry! Yes, that's exactly what I wanted to experiment with.

**Comment by pgrinaway** [comment]
>Note that the CustomBondForce that is included now is just 1,4 exceptions for CustomNonbondedForce.


Forgot about that! Thanks!

**Comment by jchodera** [comment]
OK, so you will play with this?  I'll not make changes there.

Should we merge this?

**Comment by pgrinaway** [comment]
We can merge this. I'll try to figure out what's going on and move this discussion to an issue.

**Pull request merged**
