### PR TITLE
Release 0.9.3

### PR DESCRIPTION
**Pull request by mikemhenry**
PRs to add to change log (if it makes sense) 

https://github.com/choderalab/perses/pull/858
https://github.com/choderalab/perses/pull/860
https://github.com/choderalab/perses/pull/866
https://github.com/choderalab/perses/pull/871
https://github.com/choderalab/perses/pull/874
https://github.com/choderalab/perses/pull/877
https://github.com/choderalab/perses/pull/878
https://github.com/choderalab/perses/pull/880
https://github.com/choderalab/perses/pull/887
https://github.com/choderalab/perses/pull/892
https://github.com/choderalab/perses/pull/893
https://github.com/choderalab/perses/pull/894
https://github.com/choderalab/perses/pull/896
https://github.com/choderalab/perses/pull/898
https://github.com/choderalab/perses/pull/787

### CODE REVIEW

**Comment by mikemhenry** [comment]
@ijpulidos can you do a quick scan to see if I missed any PRs?

**Comment by ijpulidos** [comment]
Sounds about right, I get other 2 which may not be relevant for an actual "changelog", just some inner changes. From doing a search with `repo:choderalab/perses type:pr merged:>2021-08-31` I get 17 (instead of your 15), the two that are missing in your list, would be

#850
#868

**Comment by mikemhenry** [comment]
That is prefect! I had a mistake in my search string, thanks! 
Do you think the changes in the context cache will be ready? @ijpulidos

**Comment by ijpulidos** [comment]
@mikemhenry Currently working on those, hopefully I'll them ready today or tomorrow. I'll let you know how this goes later during the day.

**Comment by mikemhenry** [comment]
@ijpulidos that sounds good! We can also make a minor release even just for that fix, IMHO it is better for us to release often

**Comment by ijpulidos** [comment]
Yeah, I agree, sorry for the delay with this but there were some details to be figured out. I'm hopeful I can make it soon enough for this release. I'll keep you updated!

**Comment by mikemhenry** [comment]
No worries! I feel like we lost some momentum with the holiday break and I know that every time we think we are close to fixing the caching, we find more bits that add complexity

**Comment by ijpulidos** [comment]
@mikemhenry according to our discussion with the milestones roadmap this one would need to be changed to reflect the changes in the milestones. This one is now 0.9.3. I hope it's not too much of an issue!

**Comment by mikemhenry** [comment]
Not at all -- branch name is confusing, I will see if I can change it

**Comment by mikemhenry** [comment]
I will have to close this one since the remote name changed and there isn't way to fix the PR

**Pull request closed without merging**
