### PR TITLE
Refactor NCMC to allow PDB files of NCMC insertion/deletion trajectories to be written

### PR DESCRIPTION
**Pull request by jchodera**
This is still a work in progress, but it allows NCMC switching trajectories to write PDB files of insertion/deletion if desired.

### CODE REVIEW

**Comment by jchodera** [comment]
I should probably see if I can only write the atoms that are changing along with a separate PDB file containing the static atoms.

**Comment by jchodera** [comment]
Anyone know of an easy way to write just an atom slice to a PDB file using `mdtraj`?

**Comment by juliebehr** [comment]
Are you already creating the atom slice?  Because once you do, it's its own trajectory and can be saved using ```md.save``` or ```md.save_pdb```

**Comment by juliebehr** [comment]
Otherwise you would want something like
```
sliced_traj = traj.atom_slice([atom_indices])
sliced_traj.save_pdb(pdb_filename)
```
or 
```
traj.atom_slice([atom_indices], inplace=True)
traj.save_pdb(pdb_filename)
```

-- I do not believe you can do it simultaneously, without making the actual slice first

**Comment by jchodera** [comment]
Thanks!

What's the best way to create an mdtraj object in the first place from a
Topology and positions from OpenMM?

**Comment by juliebehr** [comment]
I think there might be a bug in the code that would facilitate this -- I remember it being a PR fairly recently, very possible that it's intended to work differently from how I'm trying to use it.  Also, I doubt this is the *best* way to do this, but it seems like it should be possible from:
```
xyz = context.getState(getPositions=True).value_in_unit(unit.nanometer)
traj = md.Trajectory(xyz, md.Topology.from_openmm(topology))
```

https://github.com/mdtraj/mdtraj/pull/1048

Note that I have not tested this beyond determining that the topology step fails.

**Comment by jchodera** [comment]
This should be good to merge if tests pass!

**Comment by juliebehr** [comment]
Did something just get messed up? All of the 2.7 + 2 of the 3.4 failed.

**Comment by juliebehr** [comment]
```
The command "conda build devtools/conda-recipe" exited with 1.
$ source activate _test
Error: could not find environment: _test
```

**Comment by juliebehr** [comment]
The 3.4 testsystems and test.utils:
```
  File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/perses-0.1-py3.4.egg/perses/annihilation/ncmc_switching.py", line 349, in integrate
    import cPickle as pickle
nose.proxy.ImportError: No module named 'cPickle'
```

**Comment by juliebehr** [comment]
And 3.4 test_elimination:
```
======================================================================
ERROR: Test NCMCAlchemicalIntegrator
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/perses-0.1-py3.4.egg/perses/tests/test_elimination.py", line 215, in test_ncmc_alchemical_integrator_stability_molecules
    if np.isnan(ncmc_integrator.getLogAcceptanceProbability()):
nose.proxy.TypeError: getLogAcceptanceProbability() missing 1 required positional argument: 'context'
```

**Comment by jchodera** [comment]
Thanks, @juliebehr!

**Comment by jchodera** [comment]
OK, I'm pretty confused by
```

Installed /home/travis/miniconda/envs/_build/lib/python2.7/site-packages/perses-0.1-py2.7.egg
Processing dependencies for perses==0.1
Searching for ordereddict
Traceback (most recent call last):
  File "setup.py", line 90, in <module>
    'numba'
  File "/home/travis/miniconda/envs/_build/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/travis/miniconda/envs/_build/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/travis/miniconda/envs/_build/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/travis/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/setuptools/command/install.py", line 67, in run
  File "/home/travis/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/setuptools/command/install.py", line 117, in do_egg_install
  File "/home/travis/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/setuptools/command/easy_install.py", line 391, in run
  File "/home/travis/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/setuptools/command/easy_install.py", line 621, in easy_install
  File "/home/travis/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/setuptools/command/easy_install.py", line 672, in install_item
  File "/home/travis/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/setuptools/command/easy_install.py", line 717, in process_distribution
  File "/home/travis/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/pkg_resources/__init__.py", line 826, in resolve
  File "/home/travis/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/pkg_resources/__init__.py", line 1071, in best_match
  File "/home/travis/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/pkg_resources/__init__.py", line 1083, in obtain
  File "/home/travis/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/setuptools/command/easy_install.py", line 628, in easy_install
  File "/home/travis/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/setuptools/package_index.py", line 608, in fetch_distribution
  File "/home/travis/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/setuptools/package_index.py", line 445, in find_packages
  File "/home/travis/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/setuptools/package_index.py", line 779, in scan_url
  File "/home/travis/miniconda/envs/_build/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/setuptools/package_index.py", line 287, in process_url
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/ordereddict/r
Command failed: /bin/bash -x -e /home/travis/build/choderalab/perses/devtools/conda-recipe/build.sh
```
Looks like a problem with `numba` maybe?

**Comment by jchodera** [comment]
OK, hopefully fixed the failures.

**Pull request merged**
