### PR TITLE
Fix badge and remove some minimization code

### PR DESCRIPTION
**Pull request by pgrinaway**
This PR:

* Fixes the Jenkins badge

* Removes the extraneous minimization code that was used for geometry debugging and caused problems with constraints. (#256)

### CODE REVIEW

**Comment by pgrinaway** [comment]
Hm, no module named numpy?

**Comment by pgrinaway** [comment]
[Any ideas?](https://travis-ci.org/choderalab/perses/jobs/165022846#L581-L586)

**Comment by pgrinaway** [comment]
Talking to @Lnaden about potential fixes here regarding conda installation.

**Comment by pgrinaway** [comment]
Ok, looks like that is working

**Comment by bas-rustenburg** [comment]
@pgrinaway , what is the issue with conda-build, and could it possibly affect any other projects?

**Comment by pgrinaway** [comment]
The current version is broken. I'm not sure why, so I've pinned it to 2.0.2, which does work.

**Pull request merged**
