### PR TITLE
add python 3.10 to CI

### PR DESCRIPTION
**Pull request by mikemhenry**
## Motivation and context

Resolves #???

## Change log

```

```

### CODE REVIEW

**Comment by mikemhenry** [comment]
Resolves #1079

**Comment by mikemhenry** [comment]
@ijpulidos do we want to drop 3.8 from the matrix?

**Comment by ijpulidos** [comment]
> @ijpulidos do we want to drop 3.8 from the matrix?

That's a good question, I know this was never official but I think we are somewhat following [Numpy's deprecation policy](https://numpy.org/neps/nep-0029-deprecation_policy.html). According to that we should be supporting 3.8+ up to Jan 2023, as far as I understand.

**Comment by ijpulidos** [comment]
Seems like we would need to drop support for Openmm 7.6 if we want to add support to python 3.10, judging from https://github.com/choderalab/perses/runs/7641867028?check_suite_focus=true#step:5:53

**Comment by mikemhenry** [comment]
I was thinking that I would just remove that from the matrix since I don't think we need to stop testing on openmm 7.6, unless there is no scope to use that version with perses. 

@zhang-ivy @dominicrufa 

Do either of you use openmm 7.6?

**Comment by zhang-ivy** [comment]
Nope, I don't use it!

**Comment by mikemhenry** [comment]
@ijpulidos ready for review!

**Comment by zhang-ivy** [comment]
@mikemhenry @ijpulidos : Do we need to add 3.10 to CI for openmmtools as well?

**Comment by mikemhenry** [comment]
@zhang-ivy good idea https://github.com/choderalab/openmmtools/pull/619

**Review by ijpulidos — APPROVED** [review]
Looks good to me! LGTM.

**Pull request merged**
