### PR TITLE
Add landscape, begin cleanup

### PR DESCRIPTION
**Pull request by pgrinaway**
The plan for this PR is:

* Add landscape
* Review code health issues on landscape
* Repair health issues that are reasonable and straightforwardly fixed.

Other code health issues that are more complex should be resolved in a different PR.

### CODE REVIEW

**Comment by pgrinaway** [comment]
Anyone know what `DistutilsSetupError` is or where it is defined?

**Comment by pgrinaway** [comment]
With everyone's consent, I will try to eliminate mutable default arguments. Looks like they can have [pretty undesirable behavior](http://docs.python-guide.org/en/latest/writing/gotchas/).

**Comment by jchodera** [comment]
Holy crap yes, sorry!

**Comment by pgrinaway** [comment]
This can be merged whenever, if it's ok.

**Comment by jchodera** [comment]
You and @juliebehr are doing code reviews for each other now, right?

**Comment by pgrinaway** [comment]
@juliebehr told me this looks good. Going to merge (no substantive changes, just style and avoiding some of the unexpected results of mutable default arguments)

**Pull request merged**
