### PR TITLE
Modify chemical_state_keys from PointMutationEngine

### PR DESCRIPTION
**Pull request by juliebehr**
Addresses https://github.com/choderalab/perses/issues/190

The IP part is that I'm pretty sure I've altered the intended behavior of ```test_mutate_from_every_amino_to_every_other``` because I was previous taking advantage of the fact that I didn't actually go back to wildtype before making a new mutation, and now when I try to initiate my little protein with 20 different amino acids to start, it will actually only change 1 away from the wildtype (I think).

### CODE REVIEW

**Comment by juliebehr** [comment]
Just kidding about the list of strings; lists aren't hashable.

**Comment by jchodera** [comment]
I think immutable forms of list might be hashable. Is there a "frozenlist"
object?

**Comment by andrrizzi** [comment]
I think the frozenlist is just a tuple.

**Comment by juliebehr** [comment]
Is something wrong with a string?

**Comment by juliebehr** [comment]
I had initially yesterday intended it to make (eg) ```['LYS99ALA', 'MET102GLN']``` and now that mutant's key would be ```'LYS99ALA-MET102GLN'```

**Comment by jchodera** [comment]
Might be easier to analyze as a tuple (eg to see how many samples had MET102GLN in them) but the difference is probably minimal.

**Comment by juliebehr** [comment]
```key.split('-')``` and it's a list again

**Comment by juliebehr** [comment]
I just added the ability for the proposal to choose WT when allowed_mutations have been specified (previously it was only choosing from that list) and I expected this to break the tests where I count on being about to force it to make a certain mutation by making it the only allowed_mutations option but they seem to still run...

**Comment by juliebehr** [comment]
Nope, I forgot to reinstall

**Comment by juliebehr** [comment]
Ok, solved by finding a use for metadata, which I'm not sure if I'm crazy about -- ```metadata['always_change'] = True``` will block self-proposals, implemented only in ```PointMutationEngine```

**Comment by jchodera** [comment]
`metadata` is meant to store information that is specific to each sample.  It's not meant to be a place where we add extra arguments.  If you want to add an `always_change` (or maybe `include_initial_sequence`?) argument to `PointMutationEngine`, why not just add it as an extra argument?  Those `ProposalEngine`s don't need to share the same constructors.

**Comment by jchodera** [comment]
Should this get merged in, @juliebehr @pgrinaway ?

**Comment by jchodera** [comment]
Should this get merged in @juliebehr @pgrinaway ?

**Comment by juliebehr** [comment]
Yes

**Comment by jchodera** [comment]
@pgrinaway: Can you review and merge when you get a chance?

**Pull request merged**
