### PR TITLE
Adding NCMC tests

### PR DESCRIPTION
**Pull request by jchodera**
Working on adding a test in which a harmonic oscillator is dragged back and forth.

### CODE REVIEW

**Comment by jchodera** [comment]
I have a few more things to fix up the chain (`alchemy`, `pymbar`) so this will take me a few hours.

**Comment by jchodera** [comment]
This should be good to merge, @pgrinaway.  NCMC tests pass (both alanine dipeptide test and strict harmonic oscillator dragging test).

Not sure what the other failures are due to.  Something on your end?

**Comment by jchodera** [comment]
This should be ready to merge, unless you want me to add some more NCMC tests at this time!

**Comment by pgrinaway** [comment]
Oops, missed this. LGTM. I'm going to merge it then.

**Comment by pgrinaway** [comment]
I'll address the test failures (some kind of import problem?) in the next PR.

**Comment by jchodera** [comment]
Somehow I missed that!  It's not an import problem---it's a [`setup.py` dependency problem](https://travis-ci.org/choderalab/perses#L605-L631).
```
Processing dependencies for perses==0.1
Searching for openmm>=7.0
Traceback (most recent call last):
  File "setup.py", line 85, in <module>
    'alchemy >=1.1.2',
...
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/openmm/r
```

**Comment by jchodera** [comment]
We should be requiring `alchemy >=1.1.3` in both `setup.py` and `meta.yaml`.

**Comment by jchodera** [comment]
Let me know if you want me to take a stab at fixing this.

**Comment by jchodera** [comment]
I just fixed this in #24

**Pull request merged**
