### PR TITLE
Fix object storage for python 3

### LINKED ISSUE #249: Storage layer test failures
I'm seeing failures like [this](https://travis-ci.org/choderalab/perses/jobs/161324417#L859) relating to the storage layer. @jchodera suggested in #247 that this might be caused by some pickling issues.

### PR DESCRIPTION
**Pull request by jchodera**
Fixes #249

### CODE REVIEW

**Comment by pgrinaway** [comment]
Huh, I wonder what [this is](https://travis-ci.org/choderalab/perses/jobs/161428202#L848)

**Comment by pgrinaway** [comment]
Apparently a potentially [similar issue](https://github.com/tensorflow/tensorflow/issues/830) plagued tensorflow.

**Comment by pgrinaway** [comment]
[Related](https://github.com/choderalab/openmoltools/pull/205)

**Comment by pgrinaway** [comment]
I'm looking into fixing this

**Comment by jchodera** [comment]
Thanks! Looks like the cause and solution is explained in https://github.com/swig/swig/pull/560

**Comment by pgrinaway** [comment]
Seems from the `openmoltools` issue that the problem is creating the `simtk.openmm.System` object inside the generator was the culprit.

**Comment by jchodera** [comment]
Let me fix.

**Comment by jchodera** [comment]
Wait, we don't create a `System` object inside a generator in `perses.tests.test_storage`, do we?

**Comment by pgrinaway** [comment]
No, I'm not sure what's going on here. But I can say that this function:
```python
def test_storage_hopefully_works():
    testsystem_name = 'ValenceSmallMoleculeLibraryTestSystem'
    niterations = 5 # number of iterations to run

    # Create storage.
    tmpfile = tempfile.NamedTemporaryFile()
    filename = tmpfile.name

    import perses.tests.testsystems
    # Instantiate test system.
    testsystem = perses.tests.testsystems.ValenceSmallMoleculeLibraryTestSystem(storage_filename=filename)

    # Test MCMCSampler samplers.
    #for environment in testsystem.environments:
    environment = 'vacuum'
    mcmc_sampler = testsystem.mcmc_samplers[environment]
    mcmc_sampler.verbose = False
    f = partial(run_sampler, mcmc_sampler, niterations)
    f.description = "Testing MCMCSampler for %s with environment %s" % (testsystem_name, environment)
    return f
```
works, whereas if we replace the last line with `yield f` it gives the familiar error:

```
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/grinawap/PycharmProjects/perses/perses/tests/test_storage.py", line 195, in <module>
    for t in test_storage_hopefully_works():
SystemError: <built-in function delete_System> returned a result with an error set
```

**Comment by pgrinaway** [comment]
Seems like when the `StopIteration` exception is raised by the generator (standard behavior), a `SystemError` is being thrown. But I have no idea why, or what that built-in function is.

**Comment by pgrinaway** [comment]
In fact, just yielding the `mcmc_sampler` causes the error:

```python
def test_storage_hopefully_works():
    testsystem_name = 'ValenceSmallMoleculeLibraryTestSystem'
    niterations = 5 # number of iterations to run

    # Create storage.
    tmpfile = tempfile.NamedTemporaryFile()
    filename = tmpfile.name

    import perses.tests.testsystems
    # Instantiate test system.
    testsystem = perses.tests.testsystems.ValenceSmallMoleculeLibraryTestSystem(storage_filename=filename)

    # Test MCMCSampler samplers.
    #for environment in testsystem.environments:
    environment = 'vacuum'
    mcmc_sampler = testsystem.mcmc_samplers[environment]
    mcmc_sampler.verbose = False
    #f = partial(mcmc_sampler.run, niterations)
    #f.description = "Testing MCMCSampler for %s with environment %s" % (testsystem_name, environment)
    yield mcmc_sampler


if __name__ == "__main__":
    for t in test_storage_hopefully_works():
        pass
```

**Comment by pgrinaway** [comment]
Yielding the `testsystem` does not.

**Comment by pgrinaway** [comment]
This fails:
```python
def thermostate_generator():
    for i in range(2):
        system = openmm.System()
        yield ThermodynamicState(system, 30.0*unit.kelvin)

if __name__ == "__main__":
    for t in test_storage_hopefully_works():
        pass
```

**Comment by pgrinaway** [comment]
@bas-rustenburg [points out](https://github.com/swig/swig/blob/master/CHANGES#L281) that the problem may lie in the version of SWIG.

**Comment by bas-rustenburg** [comment]
Yeah, its what John pointed out in swig. It just hasn't been included yet in the version of SWIG that OpenMM is built against.

**Comment by bas-rustenburg** [comment]
My suggested solution for now, stop using the generator concept here until OpenMM has updated it's SWIG version.

**Comment by jchodera** [comment]
What version of `swig` do we need?

I think we've [pinned the `openmm` recipe to `swig ==3.0.7`](https://github.com/omnia-md/conda-recipes/blob/master/openmm/meta.yaml#L26-L27).

**Comment by jchodera** [comment]
Looks like we need `swig` 3.0.8 or later.

**Comment by pgrinaway** [comment]
Might be some way around it? Interestingly this code passes:
```python
def thermostate_generator():
    for i in range(2):
        yield ThermodynamicState(openmm.System(), 30.0*unit.kelvin)
```

while this fails:
```python
def thermostate_generator():
    for i in range(2):
        system = openmm.System()
        yield ThermodynamicState(system, 30.0*unit.kelvin)
```

**Comment by jchodera** [comment]
OK, a dumb fix is in.

**Comment by jchodera** [comment]
OK, all tests pass.

**Pull request merged**
