### PR TITLE
Topology proposal class

### PR DESCRIPTION
**Pull request by pgrinaway**
I have no idea how I messed up the other branch, but this one is now working. I'm going to close #26

### CODE REVIEW

**Comment by pgrinaway** [comment]
Locally, I'm getting `ImportError: No module named integrators` for the NCMC tests... I've installed openmmtools, but I can't seem to import `integrators`. Not sure what that is... presumably something messed up on my local python installation.

**Comment by pgrinaway** [comment]
Otherwise, the `GeometryEngine` test passes with the new `TopologyProposal`

**Comment by jchodera** [comment]
Go ahead and merge for now?

To clean things locally:
* conda remove --yes openmmtools openmmtools-dev
* conda clean -plts --yes
* manually clean out anything in ~/anaconda/lib/python2.7/site-packages/openmmtools*
* conda install --yes openmmtools

**Comment by pgrinaway** [comment]
Ok, that worked! thanks! All tests pass locally.

**Pull request merged**
