### PR TITLE
NullTestSystems

### PR DESCRIPTION
**Pull request by juliebehr**
This PR was previously not opened because the evaluations of the test fail; however, this is not inherent to the testsystems themselves, but rather improvements that we will subsequently make to the `ExpandedEnsembleSampler`. The presence of these test systems on the master branch should be helpful to making these improvements.

Also included are modifications to the `AbsoluteAlchemicalFactory` constructor call, and the introduction of using extra angle and torsion terms for hydrogens as well as heavy atoms.

### CODE REVIEW

**Comment by jchodera** [comment]
> but rather improvements that we will subsequently make to the ExpandedEnsembleSampler

Which improvements, specifically?

**Comment by juliebehr** [comment]
Everything regarding improving acceptance rates

**Comment by jchodera** [comment]
> Everything regarding improving acceptance rates

Ah, OK! That's not changes to `ExpandedEnsembleSampler`, but changes to the parameters fed to the geometry engine or NCMC engines (or those engines themselves).

**Comment by jchodera** [comment]
The [failures](https://travis-ci.org/choderalab/perses/jobs/172727690#L1286-L1329) indicate that we either have bugs with NCMC or something is wrong with the`logP` used in the `pentane` null elimination. Since I think we're running the other NCMC harmonic oscillator tests---which should pick up on issues with NCMC itself---that seems to suggest we're getting something wrong with the `logP`. The error grows with the number of NCMC steps, though, so I'm confused why that would happen if we have the correct NCMC contribution to `logP`.
```
======================================================================
ERROR: Testing alchemical null elimination for 'pentane' with 50 NCMC steps
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/test/lib/python3.4/site-packages/perses/tests/test_elimination.py", line 133, in check_alchemical_null_elimination
    raise Exception(msg)
nose.proxy.Exception: Delta F (50 steps switching) = 6.721582 +- 0.682316 kT; should be within 6.000000 sigma of 0
delete logP:
[ 21.99269045  20.43442393  24.67278972  19.02848394  28.72486876
  32.10578366  23.05597254  16.44185857  25.18115871  24.95225572
  24.64069531  27.77746991  16.07356162  17.54631541  28.21846965
  22.70694726  31.37780943  25.12077012  22.69813631  23.36399953
  25.93130505  24.401454    20.89655171  27.89134567  19.80586372
  28.70660678  17.55581623  26.01007833  21.69018402  23.17145044
  19.42635536  21.62994198  25.16749469  26.3878315   27.24736087
  30.81462227  18.36312851  23.69059326  24.12636314  24.42416564
  26.52228458  24.1545415   25.98978571  30.11412604  17.92110083
  25.75518169  26.28979604  26.33361063  25.46065317  17.59983679]
insert logP:
[-27.64357053 -48.86857602 -54.98160138 -50.23327203 -43.52726804
 -55.36963859 -31.47922618 -34.54405471 -34.59421503 -33.83958691
 -45.65972152 -34.45056502 -24.86378005 -36.65825186 -42.89052787
 -36.96731596 -42.3257165  -33.51548383 -33.53864505 -41.91870223
 -36.33356607 -38.48182807 -31.01363    -31.12452908 -30.62093381
 -53.66961861 -32.40543485 -32.72661631 -36.61538403 -38.5288279
 -39.81257336 -36.54690067 -45.39691607 -44.53202295 -37.81051607
 -46.8188031  -48.43129735 -40.86745043 -50.79472168 -36.6177077
 -41.79291282 -36.24207907 -40.30648784 -34.39552225 -40.85680506
 -47.62689868 -50.65723396 -49.60207835 -42.68815827 -37.02335453]
logP:
[ -5.65088008 -28.4341521  -30.30881166 -31.20478809 -14.80239928
 -23.26385494  -8.42325364 -18.10219614  -9.41305633  -8.88733119
 -21.01902621  -6.67309512  -8.79021843 -19.11193645 -14.67205822
 -14.2603687  -10.94790708  -8.39471371 -10.84050874 -18.55470271
 -10.40226102 -14.08037407 -10.11707829  -3.23318341 -10.8150701
 -24.96301183 -14.84961861  -6.71653798 -14.92520001 -15.35737746
 -20.386218   -14.91695869 -20.22942139 -18.14419145 -10.56315521
 -16.00418083 -30.06816884 -17.17685716 -26.66835854 -12.19354206
 -15.27062824 -12.08753757 -14.31670213  -4.28139621 -22.93570423
 -21.87171699 -24.36743792 -23.26846772 -17.2275051  -19.42351774]
-------------------- >> begin captured logging << --------------------
```

**Pull request merged**
