### PR TITLE
Add option to impose RMSD restraint on core heavy atoms and nearby protein CA atoms

### PR DESCRIPTION
**Pull request by jchodera**
This PR adds the option for imposing an RMSD restraint on core heavy atoms and nearby protein CA atoms.

Enabling this option also adds a virtual (zero force) bond between the small molecule and protein, and between any protein chains, ensuring the whole system is imaged together.

@dominicrufa : Any suggestions on where to add a unit test?

### CODE REVIEW

**Comment by dominicrufa** [comment]
probably somewhere [here](https://github.com/choderalab/perses/blob/rmsd-restraint/perses/tests/test_relative.py), though im not sure what the test will actually do? just make sure that the custom cv force is actually there in the hybrid system?

**Comment by jchodera** [comment]
> probably somewhere here, though im not sure what the test will actually do? just make sure that the custom cv force is actually there in the hybrid system?

I'm presuming we currently have a test that runs the FAH setup pipeline on a very small protein:ligand system. I'd just want to add a variant of that (or modify it) to also try imposing the RMSD restraint.

**Comment by jchodera** [comment]
I just ran into this issue (https://github.com/openmm/openmm/issues/2913) which means that I need to add a zero-energy `CustomBondForce` between protein and ligand. I'll add that now.

**Comment by dominicrufa** [comment]
> > probably somewhere here, though im not sure what the test will actually do? just make sure that the custom cv force is actually there in the hybrid system?
> 
> I'm presuming we currently have a test that runs the FAH setup pipeline on a very small protein:ligand system. I'd just want to add a variant of that (or modify it) to also try imposing the RMSD restraint.

we do run the `RelativeFEPSetup` (which is essentially the fah setup before minimization) on the host guest system to test the deterministic geometry map. to test that there does indeed exist a customcv force added to the hybrid_system, you can just copy/paste the `RelativeFEPSetup` class initializer in a test below [this](https://github.com/choderalab/perses/blob/d1bf2d4f70dcb644e9d7812de3e424b57ad53ed1/perses/tests/test_relative_setup.py#L218) test and just assert that there is an rmsd force in the hybrid system

**Comment by jchodera** [comment]
@dominicrufa : Could you take this PR over and finish it up? Perhaps @glass-w can help. I realize I'm juggling too many things, but we need to get this in this week. Thanks!

**Comment by dominicrufa** [comment]
> @dominicrufa : Could you take this PR over and finish it up? Perhaps @glass-w can help. I realize I'm juggling too many things, but we need to get this in this week. Thanks!

Sure, i'll give it a shot.

**Comment by jchodera** [comment]
@dominicrufa : Just bumping this---would be great if you could take a look at adding a test to finish this up!

**Comment by jchodera** [comment]
@dominicrufa : Can you help add a test and merge this?

**Comment by dominicrufa** [comment]
as a sanity check, should the rmsd force be using pbc?

**Comment by jchodera** [comment]
> as a sanity check, should the rmsd force be using pbc?

Since I also add a virtual bond between the protein chains and the protein and ligand, these will all be imaged together, so we don't need to use PBC with RMSDForce.

@dominicrufa : Are there other things needing my review/input here?

**Comment by jchodera** [comment]
@dominicrufa can you work with @mikemhenry to get this finished up and merged?

**Comment by dominicrufa** [comment]
> @dominicrufa can you work with @mikemhenry to get this finished up and merged?
I wrote a test for this branch. the only error in the PR tests right now reads:

> ModuleNotFoundError: No module named 'openff'
which is causing the failures. @mikemhenry , I'm not too familiar with what has gone / is going into refactoring, but if this can be fixed, the PR should be ready to merge

**Comment by jchodera** [comment]
> ModuleNotFoundError: No module named 'openff'

This presumably has to do with the namespace change as the openff toolkit moved to conda-forge.

This also needs to be rebased or have `master` merged in.

**Comment by mikemhenry** [comment]
Working on the PR right now -- 

@dominicrufa 
can you make sure my merge looks good here? https://github.com/choderalab/perses/pull/748/commits/8d9c9fd9e682fe9d9363a999a8294440e9814f22

It looks like flatten torsions has been merged in, so I had to manually resolve some merge conflicts. They were straightforward but  would like someone to double check them!

**Comment by mikemhenry** [comment]
This looks ready to merge, and I checked to make sure the test actually runs:
https://github.com/choderalab/perses/pull/748/checks?check_run_id=2116303508#step:9:60

**Comment by jchodera** [comment]
Thanks! It looks like there are some failures on the nightly OpenMM dev builds that we can address with the OpenMM folks?
```
____________ ERROR collecting perses/tests/test_coordinate_numba.py ____________
ImportError while importing test module '/home/runner/work/perses/perses/perses/tests/test_coordinate_numba.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/share/miniconda/envs/test/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
perses/tests/test_coordinate_numba.py:6: in <module>
    from perses.rjmc.geometry import check_dimensionality
perses/rjmc/__init__.py:1: in <module>
    from perses.rjmc import geometry, coordinate_numba, coordinate_tools, topology_proposal
perses/rjmc/topology_proposal.py:14: in <module>
    import openmoltools.forcefield_generators as forcefield_generators
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/openmoltools/__init__.py:26: in <module>
    from openmoltools import amber_parser, system_checker, utils, packmol, openeye, amber, cirpy, gromacs, schrodinger
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/openmoltools/amber_parser.py:4: in <module>
    import simtk.openmm.app.element as element
E   ModuleNotFoundError: No module named 'simtk.openmm.app.element'
____________ ERROR collecting perses/tests/test_geometry_engine.py _____________
```

**Comment by mikemhenry** [comment]
The failures on nightly are related to this issue:
https://github.com/openmm/openmm/issues/3022
We need to fix packages upstream like `openmoltools` to either use a `try` and `accept` block so we can support the namespace change OR change the imports so the backwards compatibility from openmm works out of the box.

**Comment by jchodera** [comment]
>  change the imports so the backwards compatibility from openmm works out of the box.

This sounds like the correct solution! The changes shouldn't be too extensive. Could you help tackle this?
It should be quick-and-dirty since we eventually want to deprecate `openmoltools` and replace it entirely with `openff-toolkit` functionality, but we unfortunately aren't quite there yet!

**Comment by jchodera** [comment]
@mikemhenry @dominicrufa We need to get this merged in ASAP and a new release cut when able!

**Review by mikemhenry — APPROVED** [review]

**Pull request merged**
