### PR TITLE
Upload conda package to S3

### PR DESCRIPTION
**Pull request by jchodera**
@pgrinaway : I've set up an S3 bucket `perses-ci` to upload build artifacts to for testing.

Since the IAM credentials are encrypted, I'm going to have to merge this PR to test.

### CODE REVIEW

**Comment by pgrinaway** [comment]
>I'm going to have to merge this PR to test.

Why? We are able to read encrypted environment variables on PRs and branches (otherwise, the OpenEye parts of the tests wouldn't work on PRs and branches)

**Comment by jchodera** [comment]
Thanks! See related questions on slack

**Comment by jchodera** [comment]
Also, looks like it won't work:

https://travis-ci.org/choderalab/perses/jobs/189055033#L1311

**Comment by jchodera** [comment]
S3 deployments are skipped for PRs

**Comment by pgrinaway** [comment]
You could just change that line in your branch to play around with it, though.

**Comment by jchodera** [comment]
Oh, is that a message from the after_success script and not the deploy: section?

**Comment by jchodera** [comment]
OK, I had to specifically [enable S3 deployment for all branches](https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A).

**Comment by jchodera** [comment]
@pgrinaway : That deployment failure message "Skipping a deployment with the s3 provider because the current build is a pull request." in the `continuous-integration/travis-ci/pr` build isn't coming from `devtools/travis-ci/after_success.sh`. But it doesn't seem to be working in `continuous-integration/travis-ci/push` either.

**Comment by jchodera** [comment]
Ah. [It doesn't work in PRs:](https://docs.travis-ci.com/user/deployment#Pull-Requests)
> Note that pull request builds skip the deployment step altogether.

I'll close this and see if I can get it to work on the branch pushes.

**Comment by pgrinaway** [comment]
>OK, I had to specifically enable S3 deployment for all branches.


Can you enable it for all branches, but then use a condition to restrict it to `master` and whatever branch you're playing around with?

**Comment by jchodera** [comment]
We'll eventually want to test all branches (or at least all PRs), so I'm trying to get it to work for all branches right now. Obviously, it will only test the branch I'm working on at the moment, since that's the only one with the `deploy` section.

**Comment by jchodera** [comment]
It worked!
https://travis-ci.org/choderalab/perses/jobs/189908166#L814-L911

**Pull request closed without merging**
