### PR TITLE
Remove movie rendering scripts

### PR DESCRIPTION
**Pull request by jchodera**
This PR removes existing movie-making scripts, which are now here:
https://github.com/choderalab/persesmoviemaker

Are there any other things that need to be removed?

### CODE REVIEW

**Comment by pgrinaway** [comment]
Can we put `analyze-profile` somewhere else too? Maybe in a `tests` directory, or another repo.

**Comment by jchodera** [comment]
Whoops, that was never intended to be checked in.

Which do you prefer?
* A `perses/utils/profiling/` directory with some full-featured profiling scripts (so we don't have to write these from scratch each time)?
* Just remove it altogether

**Comment by jchodera** [comment]
@pgrinaway: We're also still running into this error:
```
======================================================================
FAIL: Doctest: perses.samplers.samplers.ExpandedEnsembleSampler
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/lib/python3.4/doctest.py", line 2187, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
nose.proxy.AssertionError: Failed doctest test for perses.samplers.samplers.ExpandedEnsembleSampler
  File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/perses-0.1-py3.4.egg/perses/samplers/samplers.py", line 516, in ExpandedEnsembleSampler
----------------------------------------------------------------------
File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/perses-0.1-py3.4.egg/perses/samplers/samplers.py", line 570, in perses.samplers.samplers.ExpandedEnsembleSampler
Failed example:
    exen_sampler.run()
Exception raised:
    Traceback (most recent call last):
      File "/home/travis/miniconda/envs/_test/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest perses.samplers.samplers.ExpandedEnsembleSampler[12]>", line 1, in <module>
        exen_sampler.run()
      File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/perses-0.1-py3.4.egg/perses/samplers/samplers.py", line 840, in run
        self.update()
      File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/perses-0.1-py3.4.egg/perses/samplers/samplers.py", line 819, in update
        self.update_state()
      File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/perses-0.1-py3.4.egg/perses/samplers/samplers.py", line 741, in update_state
        geometry_new_positions, geometry_logp_propose = self.geometry_engine.propose(topology_proposal, geometry_old_positions, self.sampler.thermodynamic_state.beta)
      File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/perses-0.1-py3.4.egg/perses/rjmc/geometry.py", line 111, in propose
        logp_proposal, new_positions = self._logp_propose(top_proposal, current_positions, beta, direction='forward')
      File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/perses-0.1-py3.4.egg/perses/rjmc/geometry.py", line 1045, in _logp_propose
        phi, logp_phi = self._propose_mtm_torsion(atom, torsion, res_mol, mol_conf, positions, r, theta, context, beta)
      File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/perses-0.1-py3.4.egg/perses/rjmc/geometry.py", line 1227, in _propose_mtm_torsion
        trial_xyzs = self.torsion_scan(bond_position, angle_position, torsion_position, internal_coordinates, proposed_torsions)
      File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/perses-0.1-py3.4.egg/perses/rjmc/geometry.py", line 1254, in torsion_scan
        from coordinate_numba import torsion_scan
    ImportError: No module named 'coordinate_numba'
```

**Comment by pgrinaway** [comment]
I've added the above problem to my trello. Can this be merged? It looks fine to me.

**Comment by pgrinaway** [comment]
Ok, going to merge--I think this is fine.

**Pull request merged**
