### PR TITLE
Correct behavior for always_change

### PR DESCRIPTION
**Pull request by juliebehr**
Addressing bug https://github.com/choderalab/perses/issues/244 for cases where `allowed_mutations` have not been specified.  Previously, would have prevented moves back to WT, after a move away from WT has been accepted.  Now, requires every mutation from the previous state to be different.

For instance, if your WT sequence is:
`1MET-2TYR-3ILE-4PHE-5SER` and `max_allowed_mutants = 2`
the first proposal will choose 2 locations at random, and change them to anything other than the WT residues, possibly:
```
locations = [2, 5]
1MET-2GLN-3ILE-4PHE-5LEU
chemical_state_key = 'TYR2GLN-SER5LEU'
```

The next proposal first chooses 2 locations at random, then changes those residues to anything other than what they were previously (therefore allowing a return to WT in the event that the same locations are chosen again). Some possibilities:
```
locations = [2, 5]
1MET-2TYR-3ILE-4PHE-5SER
chemical_state_key = 'WT'
```
OR
```
locations = [2, 5]
1MET-2PRO-3ILE-4PHE-5HIS
chemical_state_key = 'TYR2PRO-SER5HIS'
```
OR
```
locations = [2, 3]
1MET-2TYR-3ALA-4PHE-5SER
chemical_state_key = 'ILE3ALA'
```
But NOT a possibility would be:
```
locations = [2, 3]
1MET-2GLN-3ALA-4PHE-5SER
chemical_state_key = 'TYR2GLN-ILE3ALA'
```
because the `TYR2GLN` mutant from the previous iteration has to change.

### CODE REVIEW

**Comment by juliebehr** [comment]
(failing tests are the same ones in master)

**Comment by jchodera** [comment]
This looks great!

If `max_allowed_mutants = 2`, will that *always* propose two mutations per proposal? If so, what would you think about allowing the number of mutations per proposal to be set independently of the total number of mutations away from wild-type that are allowed? We may, for example, only want to propose one mutation at a time (to get high acceptance rates), but still allow up to two mutations away from wild-type.

The failing test case is hopefully fixed in #253.

**Comment by juliebehr** [comment]
Yes, it will always propose 2 mutations (except in a case like the final example where one of the changes actually moves back to WT).  I had planned on doing one at a time with 2 separate runs using `max_allowed_mutants = 1` to ever actually look for double mutants.

**Comment by jchodera** [comment]
>  I had planned on doing one at a time with 2 separate runs using max_allowed_mutants = 1 to ever actually look for double mutants.

Do you mean do one run with `max_allowed_mutants = 1`, record any mutants worth looking at, and then another run with `max_allowed_mutants = 1` and a different wild-type sequence with that mutant modeled in?

**Comment by juliebehr** [comment]
Yes

**Comment by jchodera** [comment]
Wouldn't it just be easier to separately be able to specify `max_allowed_mutants` and `mutations_per_proposal`?

**Comment by juliebehr** [comment]
Sure, I'm just saying that's why it isn't like that already.  It doesn't really seem urgent.

**Comment by jchodera** [comment]
Oh, no, not urgent unless we need it for Myb. Maybe just mark it as an issue?

@pgrinaway : This is ready for you to review, I think!

**Comment by pgrinaway** [comment]
Ok, going to review now!

**Comment by pgrinaway** [comment]
Ok, I think this is good to merge then.

**Pull request merged**
