### PR TITLE
 Fix travis import hell

### PR DESCRIPTION
**Pull request by pgrinaway**
As the title says...

### CODE REVIEW

**Comment by pgrinaway** [comment]
Build failure unrelated, issue added to trello. I'm going to rebuild the problematic ones now to see that this is actually working (it occasionally worked before).

**Comment by jchodera** [comment]
Somehow, the other PR (removing rendering scripts) got mixed in here too.

**Comment by pgrinaway** [comment]
I think we just missed a couple files on the last PR so I removed them here.

**Comment by pgrinaway** [comment]
Ok, so it's still broken.

**Comment by jchodera** [comment]
OK, I need to move those files into the new repo then.

**Comment by pgrinaway** [comment]
Sounds good.

**Comment by jchodera** [comment]
>  I need to move those files into the new repo then.

[Done](https://github.com/choderalab/persesmoviemaker/pull/1).

**Comment by pgrinaway** [comment]
Anyone ever see [this before](this before)?

**Comment by jchodera** [comment]
That link seems to be broken. What are you pointing to specifically?

**Comment by pgrinaway** [comment]
Oops, copypasta fail. Here: https://travis-ci.org/choderalab/perses/jobs/139015837#L339

**Comment by jchodera** [comment]
I think that's just a network failure. Restart the tests?

**Comment by pgrinaway** [comment]
hm, restarted twice, still a problem...

**Comment by jchodera** [comment]
Looks like the [syntax has changed](http://docs.eyesopen.com/toolkits/python/quickstart-python/) to:
```
pip install -i https://pypi.anaconda.org/OpenEye/simple OpenEye-toolkits
```
as of the latest release. Can you fix?

**Comment by pgrinaway** [comment]
Sure! I wonder why some of them were working...

**Comment by pgrinaway** [comment]
Huh, I wonder what is going on here? https://travis-ci.org/choderalab/perses/jobs/139046703#L451 ...maybe I messed up the nosetest installation...

**Comment by pgrinaway** [comment]
Oh, huh: Error: HTTPError: 503 Server Error: Service Unavailable: Back-end server is at capacity for url

**Comment by jchodera** [comment]
Ah, OK.

**Comment by jchodera** [comment]
Maybe we should add a random sleep delay to the beginning of each travis branch so we don't hammer it with all of the test branches at the same time?

**Comment by pgrinaway** [comment]
Is travis having network connectivity problems?

**Comment by pgrinaway** [comment]
Maybe it's anaconda, actually.

**Comment by jchodera** [comment]
Woohoo!  All tests pass!

**Pull request merged**
