### PR TITLE
[WIP] Begin implementing samplers

### PR DESCRIPTION
**Pull request by pgrinaway**
Starting to implement the sampler objects that we've described in #61 and elsewhere.

### CODE REVIEW

**Comment by jchodera** [comment]
The `MCMCSampler` probably needs some way to specify the thermodynamic state to be sampled (temperature, pressure, etc).  

Also, it generally helps to monitor the reduced potential in `kT`, since it's easier than using unit-bearing potential energies (which also don't include pressure-volume stuff).

**Comment by pgrinaway** [comment]
>The MCMCSampler probably needs some way to specify the thermodynamic state to be sampled (temperature, pressure, etc).

Doesn't this get specified in a combination of inputs to the `Integrator` as well as `MonteCarloBarostat` or something like that (those objects are passed in instantiated already)? I agree that it still needs to be there though.


>Also, it generally helps to monitor the reduced potential in kT, since it's easier than using unit-bearing potential energies (which also don't include pressure-volume stuff).

Ok.

**Comment by pgrinaway** [comment]
I guess I could just accept a `ThermodynamicState` object for that...

**Comment by pgrinaway** [comment]
@jchodera what is the easiest way to reliably retrieve the pressure?
it looks like the way to do this is
```python
pressure_param_name = barostat.Pressure() #Anisotropic barostats have three obviously
pressure = context.getParameter(pressure_param_name)
```
Since different barostats have different ways of retrieving the pressure, I'm not sure what the most general solution is. 

On the other hand, in the Yank code, it seems like you just use the set value for the pressure (which makes sense, since obviously an NPT ensemble should have a constant pressure...). Is that more correct? Or should I take the current calculated pressure as above?

**Comment by jchodera** [comment]
It's tricky.  

Are you retrieving it from a `Context` or a `System`?

Setting temperature and pressure is also hard.  See what `MCMCSampler` does here to *set* the pressure and temperature:
https://github.com/choderalab/openmmmcmc/blob/master/openmmmcmc/thermodynamics.py#L115-L145

More generally, are you sure you want to pass a `Context` in to `MCMCSampler`, rather than a `System`?

**Comment by jchodera** [comment]
Sorry, I am an idiot. I totally forgot the current MCMCSampler doesn't have
a way to update the System yet.

Perhaps the best way to proceed is to propose an API that will make things
simple for you and I can implement this into MCMCSampler for you? Or we
could decide that it is easier to implement a basic MCMCSampler in perses
that does what you need.

Whatever the case, what we need is a minimal working example for the whole
stack that does what you need (passes information in the order you want)
without the internals filled then. Only then can we make sure to implement
the minimal API bits.

Defining these classes one at a time and implementing them fully before
going to the next layer of the sampler stack is unlikely to get us there
quickly, as we have seen.

**Comment by jchodera** [comment]
I can take a stab at this if you would prefer to just move on to geometry
engine tests.

**Comment by pgrinaway** [comment]
>I can take a stab at this if you would prefer to just move on to geometry
engine tests.


Ok, thanks. That would probably help things along a bit...

**Comment by pgrinaway** [comment]
I'll close this PR then.

**Pull request closed without merging**
