### PR TITLE
Storage fixes

### PR DESCRIPTION
**Pull request by pgrinaway**
This is a small PR with a few storage fixes:

* `get_object` had the variable name hardcoded, which prevented it from being used. This is fixed, but I had to add two extra parameters to `get_object`: `envname` and `modname`. 

* The test happened to use the exact same name as the hardcoded variable, so it was passing. I changed it to use some names we might encounter in simulation (though maybe even just a random string would suffice)

I debated for a bit about how to do this exactly in the spirit of the API, but I decided on the quick patch now so that we could keep going. I'm happy to take a look at this again later.

### CODE REVIEW

**Comment by jchodera** [comment]
I swear that was fixed in another PR!

**Comment by pgrinaway** [comment]
Maybe it was accidentally undone?

**Comment by jchodera** [comment]
Oof, that seems like a possibility!

**Comment by pgrinaway** [comment]
Accidentally created a conflict here yesterday, just resolved + will merge when tests pass.

**Pull request merged**
