### PR TITLE
Remove hacks now that upstream has updated packages

### LINKED ISSUE #798: Remove forks from CI once ParmEd and openmoltools releases are updated
Using this issue to remind myself to remove my forks once upstream merges in my PRs and cuts a release.

- [ ] `parmed`
- [ ] `openmoltools`

### PR DESCRIPTION
**Pull request by mikemhenry**
## Description

Removed forks when installing openmm nightly 

## Motivation and context

Now that parmed has made a new release to support the openmm name change + we just cut (will be on conda-forge soon) a new openmoltools release, these CI hacks are no longer needed.

Resolves #798 

## How has this been tested?

Tested on CI

## Change log

```
CI no longer requires forks for openmm namespace changes.  
```

### CODE REVIEW

**Comment by mikemhenry** [comment]
Just waiting for the openmoltools release to show up here https://github.com/conda-forge/openmoltools-feedstock/pulls

**Comment by ijpulidos** [comment]
Nice!... I think we could also get rid of pinning the openmm version in  https://github.com/choderalab/perses/blob/c1f5769d3610984b7c6c0dbe42920a56c31d893f/devtools/conda-envs/test_env.yaml#L19
What do you think?

**Comment by ijpulidos** [comment]
We should probably also fix this in the conda-forge feedstock `meta.yml` file that I changed to deal with this at the time. Right?

**Comment by mikemhenry** [comment]
> Nice!... I think we could also get rid of pinning the openmm version in
> 
> https://github.com/choderalab/perses/blob/c1f5769d3610984b7c6c0dbe42920a56c31d893f/devtools/conda-envs/test_env.yaml#L19
> 
> What do you think?

Yes I will do that now... 



> We should probably also fix this in the conda-forge feedstock `meta.yml` file that I changed to deal with this at the time. Right?

On our next release, we should bump it up to 7.6.x

**Pull request merged**
