### PR TITLE
Updates forcefield recommendation to use openff-2.0.0 instead of openff-1.0.0

### PR DESCRIPTION
**Pull request by mikemhenry**
fixes issue #966

### CODE REVIEW

**Review by ijpulidos — COMMENTED** [review]
This looks great, thanks!

There's only one file missing for adding the change here https://github.com/choderalab/perses/blob/main/examples/kinase-neq-switching/run_example.py#L38

**Comment by mikemhenry** [comment]
Good catch! I only looked for `openff-1.0.0`!

**Review by ijpulidos — APPROVED** [review]
This looks great, thanks!

**Comment by mikemhenry** [comment]
Sorry for the review request, it was a mistake

**Pull request merged**
