### PR TITLE
Speed up RTD env generation

### PR DESCRIPTION
**Pull request by mikemhenry**
## Motivation and context

Resolves #???

## Change log

```

```

### CODE REVIEW

**Comment by mikemhenry** [comment]
This should speed up our RTD builds!

**Comment by mikemhenry** [comment]
I was surprised this didn't work since it is the same as it is here? https://github.com/choderalab/openmmtools/blob/main/readthedocs.yml maybe I am missing something @ijpulidos

**Comment by mikemhenry** [comment]
@ijpulidos should be good to go now!

**Review by ijpulidos — APPROVED** [review]
LGTM!

**Pull request merged**
