### PR TITLE
[WIP] Topology proposal class

### PR DESCRIPTION
**Pull request by pgrinaway**
Ok, I've introduced a new class that contains the relevant information that we need from the proposal. I've also created a single subclass for small molecules, that adds a `molecule_smiles` property. I think this might be cleaner than using a `dict`, since it enforces what the property name should be. I've still left the `metadata` in, in case we need to otherwise use it.

### CODE REVIEW

**Comment by pgrinaway** [comment]
Also, perhaps I'll try to shorten the name of the subclass...

**Comment by jchodera** [comment]
> Also, perhaps I'll try to shorten the name of the subclass...

I actually like the descriptive name.  I think it's fine.

**Comment by jchodera** [comment]
OK, that's a less than useful failure message when creating a PR from a fork.  Not sure how to fix that.

Maybe for future work, use a branch of the `choderalab/perses` repo?  Should be fine to test locally for now.

**Comment by pgrinaway** [comment]
Oops, yeah. Ok. I'll test locally then

**Comment by pgrinaway** [comment]
Unable to merge, not sure what happened here. Superseded by #27

**Pull request closed without merging**
