### PR TITLE
Bugfix Release 0.10.1

### PR DESCRIPTION
**Pull request by ijpulidos**
## Description

Changelog for bugfix release 0.10.1.

Please check `changelog.rst` for detailed information.

### CODE REVIEW

**Review by zhang-ivy — APPROVED** [review]

**Comment by zhang-ivy** [comment]
@ijpulidos : Looks good to me!

**Review by jchodera — APPROVED** [review]
Looks good!

After this release, let's make sure each PR adds its own release note text before it is merged!

**Comment by ijpulidos** [comment]
> After this release, let's make sure each PR adds its own release note text before it is merged!

The correspnding PRs have the release notes, we are not forcing to change the `changelog.rst` file to avoid possible merge conflicts. But we might want to reconsider this, since these should be really easy to solve if they happen at all.

**Comment by jchodera** [comment]
> The corresponding PRs have the release notes, we are not forcing to change the changelog.rst file to avoid possible merge conflicts. But we might want to reconsider this, since these should be really easy to solve if they happen at all.

I think we want each PR to add the new release note. After each release, we can add the headers for each section of the release notes to avoid collisions between PRs.

**Pull request merged**
