### PR TITLE
Add imidazole protomer/tautomer example

### PR DESCRIPTION
**Pull request by jchodera**
This is the beginning of the addition of a minimal imidazole protomer/tautomer example for the experimental [`ProtonationStateSampler`](https://github.com/choderalab/perses/blob/master/perses/samplers/samplers.py#L1120).

cc [Trello](https://trello.com/c/TinTalyb)

### CODE REVIEW

**Comment by jchodera** [comment]
I've added the imidazole example, but I'm running into a `perses` error I haven't seen before:
```
[LSKI1497:choderalab/perses/perses.choderalab] choderaj% python perses/tests/testsystems.py
Creating system generators...
/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/data/constant-pH/imidazole/imidazole.pdb
Constructing positions and topologies...
System 'vacuum-imidazole' has 9 atoms
System 'explicit-imidazole' has 999 atoms
Initializing proposal engines...
Building systems...
Defining thermodynamic states...
Creating SAMS samplers...
Traceback (most recent call last):
  File "perses/tests/testsystems.py", line 1976, in <module>
    run_constph_imidazole()
  File "perses/tests/testsystems.py", line 1950, in run_constph_imidazole
    testsystem = ImidazoleProtonationStateTestSystem()
  File "perses/tests/testsystems.py", line 1362, in __init__
    chemical_state_key = proposal_engines[environment].compute_state_key(topologies[environment])
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/rjmc/topology_proposal.py", line 1289, in compute_state_key
    chemical_state_key, _ = self._topology_to_smiles(topology)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/rjmc/topology_proposal.py", line 1267, in _topology_to_smiles
    raise ValueError("More than one residue with the same name!")
ValueError: More than one residue with the same name!
```
I can't quite follow the logic that is causing this error, since I'm not quite sure why having a `Topology` object with multiple residues with the same name (probably `WAT` residues here) should be disallowed.

**Comment by jchodera** [comment]
@pgrinaway pointed out that I had specified the wrong `residue_name` argument to `SmallMoleculeSetProposalEngine` (`MOL` instead of `UNL`) but a misleading error was being printed.

I've fixed this now, and am running into a different issue:
```
[LSKI1497:choderalab/perses/perses.choderalab] choderaj% python perses/tests/testsystems.py
Creating system generators...
/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/data/constant-pH/imidazole/imidazole.pdb
Constructing positions and topologies...
System 'vacuum-imidazole' has 9 atoms
System 'explicit-imidazole' has 999 atoms
Initializing proposal engines...
Building systems...
Defining thermodynamic states...
Creating SAMS samplers...
ImidazoleProtonationStateTestSystem initialized.
vacuum-imidazole
explicit-imidazole
================================================================================
SAMS sampler iteration     0
--------------------------------------------------------------------------------
Expanded Ensemble sampler iteration        0
................................................................................
MCMC sampler iteration 0
Taking 2500 steps of Langevin dynamics...
Using platform 'CPU'
potential  = 1770.348 kT
kinetic    = 1509.985 kT
force norm = 297.786 kT/A/dof
Finished integration in 3.122 s
Final energy is    -5267.202 kT
................................................................................
Updating chemical state with ncmc-geometry-ncmc scheme...
Proposing new topology...
proposed SMILES string: c1c[nH][cH+][nH]1
Generating conformers...
Conformer generation took 0.048 s
Building new Topology object...
Traceback (most recent call last):
  File "perses/tests/testsystems.py", line 1977, in <module>
    run_constph_imidazole()
  File "perses/tests/testsystems.py", line 1974, in run_constph_imidazole
    testsystem.sams_samplers['explicit-imidazole'].run(niterations=1000)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/samplers/samplers.py", line 992, in run
    self.update()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/samplers/samplers.py", line 976, in update
    self.update_sampler()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/samplers/samplers.py", line 944, in update_sampler
    self.sampler.update()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/samplers/samplers.py", line 819, in update
    self.update_state()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/samplers/samplers.py", line 697, in update_state
    topology_proposal = self.proposal_engine.propose(system, topology)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/rjmc/topology_proposal.py", line 1179, in propose
    new_mol_start_index, len_new_mol = self._find_mol_start_index(new_topology)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/rjmc/topology_proposal.py", line 1312, in _find_mol_start_index
    raise ValueError("There can only be one residue with a specific name in the topology.")
ValueError: There can only be one residue with a specific name in the topology.
```
I'm not quite sure if I have enough information to debug what is going on here.   The initial PDB file clearly shows only one imidazole (resname `UNL`).

I do note that the debug mol2 files for the failing small molecule proposal have different residue names---`current.mol2` is `UNL`, while `proposed.mol2` is `MOL`.  Perhaps this could be a clue?

**Comment by pgrinaway** [comment]
If you are in debug mode, can you set a breakpoint and see what residue names are in the topology? This is a similar error to before (needs to be made more informative): it's not finding one residue with the name that it expects (default `MOL` constructor argument). There could be more than one (though if the others are just water I don't see that as likely) or none (I think this is likely the case). As I said I'll fix this error to be more specific as to which case it is finding.

**Comment by pgrinaway** [comment]
Perhaps set the breakpoint to the first line in `SmallMoleculeSetProposalEngine._find_mol_start_index`?

**Comment by jchodera** [comment]
We've determined that this error is being thrown because the molecule starts out with the residue name `UNL` but the proposed molecules have the name `MOL`.

**Comment by jchodera** [comment]
OK, I've observed the test failure in travis. Now adding the fix.

**Comment by jchodera** [comment]
Fixes #215

**Comment by jchodera** [comment]
Tests pass locally.

**Comment by jchodera** [comment]
Hm.  `perses.tests.test_elimination` is super slow on travis:
```
Testing alchemical null elimination for 'pentane' with 0 NCMC steps ... ok (61.5070s)
Testing alchemical null elimination for 'pentane' with 1 NCMC steps ... ok (91.8482s)
Testing alchemical null elimination for 'pentane' with 50 NCMC steps ... 
```

**Comment by jchodera** [comment]
Woohoo!  All tests pass.

@pgrinaway: Review and merge?

**Comment by pgrinaway** [comment]
Reviewing now.

**Comment by pgrinaway** [comment]
Looks good to me.

**Pull request merged**
