### PR TITLE
Fix readthedocs docs build

### PR DESCRIPTION
**Pull request by jchodera**
Currently, the readthedocs API docs are failing to build.

This PR aims to fix these build failures.

### CODE REVIEW

**Comment by jchodera** [comment]
Looks like the [readthedocs build](https://readthedocs.org/api/v2/build/7915096.txt) is trying to import some things it shouldn't:
```
[rtd-command-info] start-time: 2018-10-09T19:35:21.853335, end-time: 2018-10-09T19:36:01.924973, duration: 40, exit-code: 0
python /home/docs/checkouts/readthedocs.org/user_builds/perses/conda/fix-docs/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
Running Sphinx v1.8.1
loading translations [en]... done
making output directory...
[autosummary] generating autosummary for: analysis.rst, annihilation.rst, bias.rst, changelog.rst, index.rst, installation.rst, rjmc.rst, samplers.rst, storage.rst
WARNING: [autosummary] failed to import 'perses.annihilation.HybridTopologyFactory': no module named perses.annihilation.HybridTopologyFactory
/home/docs/checkouts/readthedocs.org/user_builds/perses/conda/fix-docs/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
WARNING: [autosummary] failed to import 'perses.annihilation.ncmc_switching.NCMCAlchemicalIntegrator': no module named perses.annihilation.ncmc_switching.NCMCAlchemicalIntegrator
WARNING: [autosummary] failed to import 'perses.annihilation.ncmc_switching.NCMCEngine': no module named perses.annihilation.ncmc_switching.NCMCEngine
WARNING: [autosummary] failed to import 'perses.annihilation.ncmc_switching.NCMCGHMCAlchemicalIntegrator': no module named perses.annihilation.ncmc_switching.NCMCGHMCAlchemicalIntegrator
WARNING: [autosummary] failed to import 'perses.annihilation.ncmc_switching.NCMCHybridEngine': no module named perses.annihilation.ncmc_switching.NCMCHybridEngine
WARNING: [autosummary] failed to import 'perses.rjmc.topology_proposal.ButaneProposalEngine': no module named perses.rjmc.topology_proposal.ButaneProposalEngine
WARNING: [autosummary] failed to import 'perses.rjmc.topology_proposal.NaphthaleneProposalEngine': no module named perses.rjmc.topology_proposal.NaphthaleneProposalEngine
WARNING: [autosummary] failed to import 'perses.rjmc.topology_proposal.NullProposalEngine': no module named perses.rjmc.topology_proposal.NullProposalEngine
WARNING: [autosummary] failed to import 'perses.rjmc.topology_proposal.PeptideLibraryEngine': no module named perses.rjmc.topology_proposal.PeptideLibraryEngine
WARNING: [autosummary] failed to import 'perses.rjmc.topology_proposal.PointMutationEngine': no module named perses.rjmc.topology_proposal.PointMutationEngine
WARNING: [autosummary] failed to import 'perses.rjmc.topology_proposal.PolymerProposalEngine': no module named perses.rjmc.topology_proposal.PolymerProposalEngine
WARNING: [autosummary] failed to import 'perses.rjmc.topology_proposal.PropaneProposalEngine': no module named perses.rjmc.topology_proposal.PropaneProposalEngine
WARNING: [autosummary] failed to import 'perses.rjmc.topology_proposal.ProposalEngine': no module named perses.rjmc.topology_proposal.ProposalEngine
WARNING: [autosummary] failed to import 'perses.rjmc.topology_proposal.SmallMoleculeSetProposalEngine': no module named perses.rjmc.topology_proposal.SmallMoleculeSetProposalEngine
WARNING: [autosummary] failed to import 'perses.rjmc.topology_proposal.SystemGenerator': no module named perses.rjmc.topology_proposal.SystemGenerator
WARNING: [autosummary] failed to import 'perses.rjmc.topology_proposal.TopologyProposal': no module named perses.rjmc.topology_proposal.TopologyProposal
WARNING: [autosummary] failed to import 'perses.samplers.ExpandedEnsembleSampler': no module named perses.samplers.ExpandedEnsembleSampler
WARNING: [autosummary] failed to import 'perses.samplers.GHMCIntegrator': no module named perses.samplers.GHMCIntegrator
WARNING: [autosummary] failed to import 'perses.samplers.MCMCSampler': no module named perses.samplers.MCMCSampler
WARNING: [autosummary] failed to import 'perses.samplers.MultiTargetDesign': no module named perses.samplers.MultiTargetDesign
WARNING: [autosummary] failed to import 'perses.samplers.ProtonationStateSampler': no module named perses.samplers.ProtonationStateSampler
WARNING: [autosummary] failed to import 'perses.samplers.SAMSSampler': no module named perses.samplers.SAMSSampler
WARNING: [autosummary] failed to import 'perses.samplers.SamplerState': no module named perses.samplers.SamplerState
WARNING: [autosummary] failed to import 'perses.samplers.ThermodynamicState': no module named perses.samplers.ThermodynamicState
```

**Comment by pgrinaway** [comment]
Oh, I think those are deleted.

**Comment by jchodera** [comment]
Looks like your encrypted license is also expired in `travis` (a separate issue):
```
Test analysis tools. ... LICENSE: No valid license found for oechem
LICENSE: File(s) used: /home/travis/oe_license.txt
LICENSE: Closest license failed because:
LICENSE: expiration date
```

**Comment by jchodera** [comment]
@pgrinaway if you've reorganized a lot of classes, can you take a quick pass through the `docs/` directory and update which classes are listed in the `.rst` files? Now that Hannah and Ivy will be going through this, we need to make sure the docs are at least functional!

**Comment by pgrinaway** [comment]
Sure, I'll put that on the docket for tomorrow evening.

**Comment by jchodera** [comment]
Should we get this merged?

**Comment by pgrinaway** [comment]
This RTD build is passing now. This can be merged if that's ok with you @jchodera .

**Comment by jchodera** [comment]
This doesn't appear to be working completely, since the API docs are not being filled in:
image
Usually, this is a failure to install the package within RTD because of missing dependencies. If you look at the [build output](https://readthedocs.org/projects/perses/builds/8605484/), you see:
```
Running Sphinx v1.8.4
loading translations [en]... done
making output directory...
[autosummary] generating autosummary for: analysis.rst, annihilation.rst, bias.rst, changelog.rst, index.rst, installation.rst, rjmc.rst, samplers.rst, storage.rst
WARNING: [autosummary] failed to import 'perses.annihilation.HybridTopologyFactory': no module named perses.annihilation.HybridTopologyFactory
WARNING: [autosummary] failed to import 'perses.annihilation.ncmc_switching.NCMCEngine': no module named perses.annihilation.ncmc_switching.NCMCEngine
WARNING: [autosummary] failed to import 'perses.rjmc.topology_proposal.ButaneProposalEngine': no module named perses.rjmc.topology_proposal.ButaneProposalEngine
WARNING: [autosummary] failed to import 'perses.rjmc.topology_proposal.NaphthaleneProposalEngine': no module named perses.rjmc.topology_proposal.NaphthaleneProposalEngine
WARNING: [autosummary] failed to import 'perses.rjmc.topology_proposal.NullProposalEngine': no module named perses.rjmc.topology_proposal.NullProposalEngine
```
However, it's still an improvement, so I'll merge and debug later!

**Pull request merged**
