### PR TITLE
Sampler implementation in process

### PR DESCRIPTION
**Pull request by jchodera**
Starting basic samplers implementation.

Very much in progress and untested.  Just figuring out APIs right now.

### CODE REVIEW

**Comment by jchodera** [comment]
I've temporarily ingested `ThermodynamicState` and `SamplerState` and written a minimal functioning placeholder for `MCMCSampler` until we can switch over to the `openmmmcmc` package.

**Comment by jchodera** [comment]
Some decisions on issues #90 and #89 are needed before I can go further.

**Comment by jchodera** [comment]
This is mostly done.  Once some of the other issues I raised are cleaned up, I can finish the testing and we're off to the races with a very basic functional implementation.

This currently only replicates the NCMC-geometry-NCMC scheme we have in `test_sampler.py`, but we can add more schemes (`geometry-ncmc-geometry` and `geometry-ncmc`) later.

**Comment by jchodera** [comment]
Added tests for the whole sampler stack.  Hopefully this will work once #103 is resolved!

**Comment by jchodera** [comment]
Did a bit more cleanup and documentation.  Just waiting on @juliebehr's changes to finish.

**Comment by jchodera** [comment]
Also, the API for this shouldn't be considered final.  I'm more than happy to change this however we want to make things easier.  This is just a first stab at the whole stack.

**Comment by pgrinaway** [comment]
>This is just a first stab at the whole stack.

That's fine. I think the first stab is important because we want to get the paper out as well as get things started for collaborators. Taking a look now while the debugger takes its time...

**Comment by jchodera** [comment]
Probably easier to link to the whole new files:
* [`perses/samplers/samplers.py`](https://github.com/choderalab/perses/blob/samplers/perses/samplers/samplers.py)
* [`perses/tests/testsystems.py`](https://github.com/choderalab/perses/blob/samplers/perses/tests/testsystems.py)
* [`perses/tests/test_samplers.py`](https://github.com/choderalab/perses/blob/samplers/perses/tests/test_samplers.py)

**Comment by jchodera** [comment]
OK, I'm now stuck waiting on #93 too.

**Comment by pgrinaway** [comment]
What do you need from #93? I can just do that now and merge. Is there any reason we can't merge this first?

**Comment by jchodera** [comment]
See test failures for master. There were some thing being cleaned up in
geometry or TopologyProposal, or so I thought?

**Comment by jchodera** [comment]
Or maybe these are things I forgot to change after merging in changes from
master?

**Comment by pgrinaway** [comment]
Looks like there are 3 failures in master:

1) `GeometryEngine` failure because of a change in the `TopologyProposal` API. This is fixed in my PR and shouldn't really affect this PR.

2) `test_run_example` fails but this is basically deprecated by this PR. (also, the failure is the same change as in 1)...perhaps the changes weren't pulled in?

3) The last one looks like an oversight on my part. I need to change the test for the `SmallMoleculeSetProposalEngine`, but again I don't think it should affect this PR.

**Comment by jchodera** [comment]
Should we merge this then?

**Comment by pgrinaway** [comment]
I think that would be best.

**Comment by jchodera** [comment]
Go for it then! Will have time to clean up anything I missed tonight.

**Comment by pgrinaway** [comment]
Ok, I'll do that now. Hopefully I can finish up #93 tonight as well (if there is an API change I can fix that in #93)

**Pull request merged**
