### PR TITLE
add allow_undefined_stereo option for SDF files with undefined stereocenters

### PR DESCRIPTION
**Pull request by glass-w**
This is directly related to #673. 

In this PR I've added an option to set `allow_undefined_stereo` when creating an `OEMol` object using `createOEMolFromSDF` in `relative_point_mutation_setup.py`.

@schallerdavid and I are working with sets of ligands that contain undefined stereocenters after preparation with OpenEye (this has been reported to them and they are working on a fix). Until this is solved (or we move to `openforcefield`, as discussed in #657) we need an option to relax the requirement that all stereocenters need to be defined.

### CODE REVIEW

**Comment by jchodera** [comment]
@glass-w @schallerdavid : Can you clarify your specific issue here? Which one of these is it:
* Using SMILES strings to specify ligands that have undefined stereocenters
* Using 2D SDF files that do not specify stereochemistry
* Using 3D SDF files with flat nitrogens (or other atom OE believes are chiral)

**Comment by schallerdavid** [comment]
@jchodera ,

this issue was about larotrectinib and selitrectinib, which has an almost planar sp3 nitrogen. When reading the sdf of the docking pose into perses, we received an undefined stereo center error.

**Comment by jchodera** [comment]
Thanks for the clarification! We should deprecate everything in `perses.utils.openeye` as part of continued refactoring to switch to `openff-toolkit`.

@glass-w: You'll have to rebase or update to master, but once you do, we can merge!

**Comment by glass-w** [comment]
@mikemhenry this should be ready to merge

**Pull request merged**
