### PR TITLE
Fix null proposal engine

### LINKED ISSUE #296: We cannot copy.deepcopy Topology object
This is currently done [in `NullProposalEngine.propose`](https://github.com/choderalab/perses/blob/benchmark/perses/rjmc/topology_proposal.py#L1682) and in [`PolymerProposalEngine.propose`](https://github.com/choderalab/perses/blob/benchmark/perses/rjmc/topology_proposal.py#L232-L236). See https://github.com/choderalab/perses/pull/281 for a detailed explanation of why we cannot do this and what the fix is.

Using `deepcopy` on `Topology` objects causes Perses to fail with `openmm 7.1.0` builds.

`perses` will not run correctly on `openmm 7.0.1` because of known bugs in `CustomIntegrator`. We *must* use `7.1.0`.

### PR DESCRIPTION
**Pull request by jchodera**
Fixes #296.

Ready for review.

### CODE REVIEW

**Comment by jchodera** [comment]
Actually, I'm also going to pin the openmm version so we don't make this mistake yet again.

**Comment by jchodera** [comment]
Pinned. Will merge when tests pass.

**Comment by jchodera** [comment]
Hm. Didn't we want to just merge this into master and delete this branch instead of the other way around?

**Comment by pgrinaway** [comment]
>Hm. Didn't we want to just merge this into master and delete this branch instead of the other way around?

Yeah, but there were conflicts, so I had to do a quick merge from master.

**Comment by jchodera** [comment]
Thanks!

**Pull request merged**
