### PR TITLE
run CI on new 0.10.x branch

### PR DESCRIPTION
**Pull request by mikemhenry**
## Motivation and context

Resolves #???

## Change log

```

```

### CODE REVIEW

**Review by ijpulidos — APPROVED** [review]
Looks good, thanks!

**Comment by ijpulidos** [comment]
Wait, is it actually `0.10.x` or `0.10.*`?

**Comment by ijpulidos** [comment]
I think it needs to be `0.10.*` instead, check https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore

**Review by ijpulidos — CHANGES_REQUESTED** [review]
Change requested

**Comment by mikemhenry** [comment]
Ooops, yes typo in the name (should we use x instead of * for the branch name?)

**Pull request merged**
