### PR TITLE
Overhaul parameterization scheme used for small molecules

### PR DESCRIPTION
**Pull request by jchodera**
This PR focuses on overhauling the way we parameterize small molecules in `perses`.
We switch to a new scheme that uses OpenEye `OEMol`s to initialize a residue template generator for OpenMM's `ForceField`.

### CODE REVIEW

**Comment by hannahbrucemacdonald** [comment]
def generate_vacuum_hostguest_proposal
def generate_solvated_hybrid_test_topology
def generate_vacuum_hostguest_proposal

^ tests/utils.py
called from tests/test_hybrid_builder.py
from test_simple_overlap, test_difficult_overlap and test_hostguest_overlap

**Comment by jchodera** [comment]
After ingesting the new `OEGAFFTemplateGenerator` into `perses.forcefields`, I've been working to convert all of the tests and other infrastructure to use this template generator. In doing that, I had to fix a few other things:
* I replaced the `ProposalOrderTools` in `perses.geometry` (which made extensive use of `Residue` -> `OEMol` conversion) with Patrick's NetworkX version
* The geometry engine adds some biasing terms to increase the acceptance rates when closing rings and getting proper bond stereochemistry. To do so, it creates an `OEMol` and uses `openeye.oechem.OEOmega` to sample plausible geometries and add new valence bias terms based on this to the geometry proposal valence force field. For now, I've disabled this, but I'll need to find a better solution that works for both small molecules and biopolymer residues, so I've been thinking about creating a `TopologyPlus` subclass of OpenMM's `Topology` that just adds a few methods for retrieving the `OEMol` objects (either complete molecule or terminally-blocked version for protein residues) corresponding to each `Residue` in the topology. This can later be replaced with the `openforcefield.Topology` once it's ready in April.

**Comment by jchodera** [comment]
Now I'm only seeing failures that have to do with the molecule name not being found:
```
======================================================================
ERROR: This test fails with a 'no topical torsions found' error with the old ProposalOrderTools
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/miniconda/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/choderaj/github/choderalab/perses/perses/tests/test_hybrid_builder.py", line 135, in test_networkx_proposal_order
    test_simple_overlap(pair[0],pair[1])
  File "/Users/choderaj/github/choderalab/perses/perses/tests/test_hybrid_builder.py", line 228, in test_simple_overlap
    forcefield_kwargs=forcefield_kwargs, system_generator_kwargs=system_generator_kwargs)
  File "/Users/choderaj/github/choderalab/perses/perses/tests/utils.py", line 906, in generate_vacuum_topology_proposal
    topology_proposal = proposal_engine.propose(old_system, old_topology, current_mol=old_oemol, proposed_mol=new_oemol)
  File "/Users/choderaj/github/choderalab/perses/perses/rjmc/topology_proposal.py", line 2061, in propose
    old_mol_start_index, len_old_mol = self._find_mol_start_index(current_topology)
  File "/Users/choderaj/github/choderalab/perses/perses/rjmc/topology_proposal.py", line 2207, in _find_mol_start_index
    raise ValueError(msg)
ValueError: There must be exactly one residue with a specific name in the topology. Found 0 residues with name 'pentane'
Residues:
['MOL']
```
There's some discrepancy between the residue name we think the initial molecule is supposed to have and the residue name it actually receives.

**Comment by jchodera** [comment]
I think I've fixed the issues here! Just running more tests.

**Comment by jchodera** [comment]
I'm not sure why travis isn't building this PR, so I'll close and reopen.

**Pull request closed without merging**
