### PR TITLE
Storage layer

### PR DESCRIPTION
**Pull request by jchodera**
Beginning implementation of #194

### CODE REVIEW

**Comment by jchodera** [comment]
Conceptual question: How do we want to deal with the fact that there may be multiple sampler stacks inside a single `MultiTargetDesign` object? Do we want to have each sampler stack be organized inside of a separate dataset group within a single NetCDF file, or separate NetCDF files for each sampler stack (and another file for the `MultiTargetDesign` object)?

I'm guessing it's easiest to put everything in one file, but we need to figure out how to associate a unique name to each sampler stack (e.g. based on the environment name, like `complex-explicit`, `ligand-explicit`).

**Comment by jchodera** [comment]
I've gone the route of putting everything in one file since nobody was around to provide feedback.

The NetCDF file is organized into groups, with variables named `/envname/modname/varname`, with `envname` the environment name (`complex-explicit`, `ligand-explicit`), `modname` the module class name (`MCMCSampler`, `ExpandedEnsembleSampler`, `SAMSSampler`), and `varname` the variable name (`logp_accept`, `logp_ncnc_annihilation`, etc.).

I've implemented writing of floats (acceptance probabilities and components) and objects (free energy and log weight `dict`s), and implemented these in all the samplers.

I'll think about how best to implement the writing of positions, but already this does what you need, so you can probably merge it and get going right away, @pgrinaway.

I've aggressively kept the [storage layer code](https://github.com/choderalab/perses/blob/855791ed2c2247946f0c5ede8fb4c7367cdcf0c6/perses/storage/storage.py) as simple and general as possible, but as always, feedback on how to further simplify things is greatly appreciated.

I haven't added code to read from the NetCDF file, since I imagine you might want to write your own analysis code. If you want me to add reader routines or a way to easily get at the data through `NetCDFStorage`, just let me know what you would like to see and I can add things ASAP.

**Comment by jchodera** [comment]
Tests should pass now.

**Comment by pgrinaway** [comment]
This looks great! Thanks! I would have gone with one output file as well--I think it's easier to manage.

**Comment by jchodera** [comment]
Awesome.

Can I implement the remaining pieces in separate PRs? I think you can start
to use this as is right now.

Let me know if you need documentation on how to use it. See the
test_storage.py code for an example. Each sampler has a .storage attribute
so that you can control which samplers you want to write their data.

**Comment by pgrinaway** [comment]
>Can I implement the remaining pieces in separate PRs?

Go for it.

>Let me know if you need documentation on how to use it. See the
test_storage.py code for an example. Each sampler has a .storage attribute
so that you can control which samplers you want to write their data.

Thanks!

**Pull request merged**
