### PR TITLE
Remove beta; add property to SystemGenerator

### PR DESCRIPTION
**Pull request by pgrinaway**
Two minor changes:

* Removed `beta` from proposals and proposal engines (addressing #91)

* Added `ffxmls` property to `SystemGenerator` to assist in #95

### CODE REVIEW

**Comment by jchodera** [comment]
Awesome!  +1, AAA+++, would buy again.

**Comment by pgrinaway** [comment]
I'm going to merge this. I have to make a minor change to the `GeometryEngine` as a result but I'll do that in the other PR.

**Comment by jchodera** [comment]
Cool. I can wait until your geometry engine PR is merged to resume sampler
work.

**Comment by pgrinaway** [comment]
Ok, great.

**Pull request merged**
