### PR TITLE
[WIP] Finish full transition to openmmforcefields (away from Topology -> OEMol)

### PR DESCRIPTION
**Pull request by jchodera**

### CODE REVIEW

**Comment by jchodera** [comment]
It looks like the current failing tests are due to the mol2 files being fed into `antechamber` missing atom names:
```
(perses) lski2838:tmpgn0nav6x choderaj$ cat molecule-before-bond-perception.mol2 
@<TRIPOS>MOLECULE
naphthalene
   18    19     0     0     0
SMALL
NO_CHARGES

@<TRIPOS>ATOM
      1             0.0000    0.0000    0.0000           1 <0>         0.0000
      2             0.0000    0.0000    0.0000           1 <0>         0.0000
      3             0.0000    0.0000    0.0000           1 <0>         0.0000
      4             0.0000    0.0000    0.0000           1 <0>         0.0000
      5             0.0000    0.0000    0.0000           1 <0>         0.0000
      6             0.0000    0.0000    0.0000           1 <0>         0.0000
      7             0.0000    0.0000    0.0000           1 <0>         0.0000
      8             0.0000    0.0000    0.0000           1 <0>         0.0000
      9             0.0000    0.0000    0.0000           1 <0>         0.0000
     10             0.0000    0.0000    0.0000           1 <0>         0.0000
     11             0.0000    0.0000    0.0000           1 <0>         0.0000
     12             0.0000    0.0000    0.0000           1 <0>         0.0000
     13             0.0000    0.0000    0.0000           1 <0>         0.0000
     14             0.0000    0.0000    0.0000           1 <0>         0.0000
     15             0.0000    0.0000    0.0000           1 <0>         0.0000
     16             0.0000    0.0000    0.0000           1 <0>         0.0000
     17             0.0000    0.0000    0.0000           1 <0>         0.0000
     18             0.0000    0.0000    0.0000           1 <0>         0.0000
@<TRIPOS>BOND
     1   18   18 
     2   18   18 
     3   18   18 
     4   18   18 
     5   18   18 
     6   18   18 
     7   18   18 
     8   18   18 
     9   18   18 
    10   18   18 
    11   18   18 
    12   18   18 
    13   18   18 
    14   18   18 
    15   18   18 
    16   18   18 
    17   18   18 
    18   18   18 
    19   18   18 
(perses) lski2838:tmpgn0nav6x choderaj$ antechamber -fi mol2 -i molecule-before-bond-perception.mol2 -fo mol2 -o out.mol2

Welcome to antechamber 19.0: molecular input file processor.

acdoctor mode is on: check and diagnose problems in the input file.
-- Check Format for mol2 File --
   Status: pass

Warning: Unknown bond type for bond (0.000-0.000:@<TRIPOS>BOND
).
         Assuming it is a single bond.

Warning: Unknown bond type for bond (0.000-0.000:@<TRIPOS>BOND
).
         Assuming it is a single bond.

Warning: Unknown bond type for bond (0.000-0.000:@<TRIPOS>BOND
).
         Assuming it is a single bond.

Warning: Unknown bond type for bond (0.000-0.000:@<TRIPOS>BOND
).
         Assuming it is a single bond.

Warning: Unknown bond type for bond (0.000-0.000:@<TRIPOS>BOND
).
         Assuming it is a single bond.

Warning: Unknown bond type for bond (0.000-0.000:@<TRIPOS>BOND
).
         Assuming it is a single bond.

Warning: Unknown bond type for bond (0.000-0.000:@<TRIPOS>BOND
).
         Assuming it is a single bond.

Warning: Unknown bond type for bond (0.000-0.000:@<TRIPOS>BOND
).
         Assuming it is a single bond.

Warning: Unknown bond type for bond (0.000-0.000:@<TRIPOS>BOND
).
         Assuming it is a single bond.

Warning: Unknown bond type for bond (0.000-0.000:@<TRIPOS>BOND
).
         Assuming it is a single bond.

Warning: Unknown bond type for bond (0.000-0.000:@<TRIPOS>BOND
).
         Assuming it is a single bond.

Warning: Unknown bond type for bond (0.000-0.000:@<TRIPOS>BOND
).
         Assuming it is a single bond.

Warning: Unknown bond type for bond (0.000-0.000:@<TRIPOS>BOND
).
         Assuming it is a single bond.

Warning: Unknown bond type for bond (0.000-0.000:@<TRIPOS>BOND
).
         Assuming it is a single bond.

Warning: Unknown bond type for bond (0.000-0.000:@<TRIPOS>BOND
).
         Assuming it is a single bond.

Warning: Unknown bond type for bond (0.000-0.000:@<TRIPOS>BOND
).
         Assuming it is a single bond.

Warning: Unknown bond type for bond (0.000-0.000:@<TRIPOS>BOND
).
         Assuming it is a single bond.

Warning: Unknown bond type for bond (0.000-0.000:@<TRIPOS>BOND
).
         Assuming it is a single bond.

Warning: Unknown bond type for bond (0.000-0.000:@<TRIPOS>BOND
).
         Assuming it is a single bond.
antechamber: Fatal Error!
Unrecognized atomic name (.0000).
```
The mol2 file contains
```
(perses) lski2838:tmpgn0nav6x choderaj$ cat molecule-before-bond-perception.mol2 
@<TRIPOS>MOLECULE
naphthalene
   18    19     0     0     0
SMALL
NO_CHARGES

@<TRIPOS>ATOM
      1             0.0000    0.0000    0.0000           1 <0>         0.0000
      2             0.0000    0.0000    0.0000           1 <0>         0.0000
      3             0.0000    0.0000    0.0000           1 <0>         0.0000
      4             0.0000    0.0000    0.0000           1 <0>         0.0000
      5             0.0000    0.0000    0.0000           1 <0>         0.0000
      6             0.0000    0.0000    0.0000           1 <0>         0.0000
      7             0.0000    0.0000    0.0000           1 <0>         0.0000
      8             0.0000    0.0000    0.0000           1 <0>         0.0000
      9             0.0000    0.0000    0.0000           1 <0>         0.0000
     10             0.0000    0.0000    0.0000           1 <0>         0.0000
     11             0.0000    0.0000    0.0000           1 <0>         0.0000
     12             0.0000    0.0000    0.0000           1 <0>         0.0000
     13             0.0000    0.0000    0.0000           1 <0>         0.0000
     14             0.0000    0.0000    0.0000           1 <0>         0.0000
     15             0.0000    0.0000    0.0000           1 <0>         0.0000
     16             0.0000    0.0000    0.0000           1 <0>         0.0000
     17             0.0000    0.0000    0.0000           1 <0>         0.0000
     18             0.0000    0.0000    0.0000           1 <0>         0.0000
@<TRIPOS>BOND
     1   18   18 
     2   18   18 
     3   18   18 
     4   18   18 
     5   18   18 
     6   18   18 
     7   18   18 
     8   18   18 
     9   18   18 
    10   18   18 
    11   18   18 
    12   18   18 
    13   18   18 
    14   18   18 
    15   18   18 
    16   18   18 
    17   18   18 
    18   18   18 
    19   18   18 
```
I'm not sure yet whether the failure is caused by (1) the new `antechamber` now requires atom names, or (2) somehow our mol2 generation is no longer adding atom names.

**Comment by hannahbrucemacdonald** [comment]
I would imagine it's a new `antechamber` requirement, seeing as we haven't _removed_ adding atom names. We have this function 
https://github.com/choderalab/perses/blob/a98c4512f45329c8efa49a1d928fe20929ac1bbd/perses/utils/openeye.py#L281

`perses.utils.gegenerate_unique_atom_names()`


Do we just need to call this in the tests?

**Comment by jaimergp** [comment]
According to the [changelog](https://ambermd.org/ATPatches.php), `antechamber` hasn't received any updates since AT17. Which version were we using before? `ambermini` 16?

**Comment by jchodera** [comment]
This PR has been superceded by #618

**Pull request closed without merging**
