### PR TITLE
Fix the geometry logp_reverse by copying coordinates.

### PR DESCRIPTION
**Pull request by pgrinaway**
Potentially WIP, though it does work on my machine.

### CODE REVIEW

**Comment by pgrinaway** [comment]
To be clear, the issue here was that the torsion scan modified `old_positions`, leaving them in a messed-up position for the next round.

**Comment by pgrinaway** [comment]
Any idea why travis is not doing anything here?

**Comment by jchodera** [comment]
> To be clear, the issue here was that the torsion scan modified old_positions, leaving them in a messed-up position for the next round.

OOOOOOOH

**Comment by jchodera** [comment]
This looks much better!  Want to merge and we can deal with the other issues separately? 

Looks like there might be some mutation proposal issues and some topology proposal issues (where the wrong number of atoms is present).

**Comment by pgrinaway** [comment]
Sounds good!

**Pull request merged**
