### PR TITLE
Version CUDA Support Better With Dockerfiles

### PR DESCRIPTION
**Pull request by mikemhenry**
## Description

Using CUDA 11 as a descriptor isn't enough as cuda 11.0.3 on the host didn't work with a cuda image built with 11.2.2. 

## Motivation and context

This PR adds support for a cuda image that will work on GCP's container optimized os (cos) by providing a docker image that is built with cuda 11.0.3.

## How has this been tested?

Tested manually on GCP on a V100 GPU.

## Change log

```
Added a docker image for CUDA 11.0.3
```

### CODE REVIEW

**Comment by mikemhenry** [comment]
Still need to add a note in the readme

**Comment by mikemhenry** [comment]
Ready for review! Also see this comment, https://github.com/choderalab/perses/issues/864#issuecomment-921847591 looks like the changes worked!

**Review by ijpulidos — APPROVED** [review]
Great work, any ideas why is it failing with CUDA 11.2? Is that only on GCP?

**Comment by mikemhenry** [comment]
It works fine with CUDA 11.2, but just not on systems that only support CUDA 11.0

**Comment by mikemhenry** [comment]
Superseded by PR #1087

**Pull request closed without merging**
