### PR TITLE
Update readthedocs config so that all docs build

### PR DESCRIPTION
**Pull request by jchodera**
This PR attempts to fix the readthedocs builds.

### CODE REVIEW

**Comment by hannahbrucemacdonald** [comment]
@jchodera - Just want to point out that we also seem to have `improve-docs` and `fixing-docs` branches as well. I can try tidy all of these up into one?

**Comment by jchodera** [comment]
Whoops! I hadn't seen a PR open for `improve-docs`.

This PR is just attempting to update `docs/environment.yml` so that the docs actually compile. Hopefully, it will just take a bit of tinkering, and then you can get the other docs improvements in `improve-docs` merged separately.

**Comment by jchodera** [comment]
Unless you've already fixed that! If so, can you open a PR?

**Comment by jchodera** [comment]
I think I've got this working. New docs will appear [here](https://perses.readthedocs.io/en/fix-readthedocs/) shortly.

**Comment by jchodera** [comment]
Looks like the docs build timed out. I've retriggered the build to see if I can get it to work on a second try.

In future, we can avoid the need to install so many dependencies via `docs/environment.yml` (which takes most of the build time) by localizing external package `import`s within the functions that use them. This would make it possible to still build the docs without the need to install a huge variety of external dependencies, since these would only be needed when specific methods run.

**Comment by jchodera** [comment]
Docs build! See [here](https://perses.readthedocs.io/en/fix-readthedocs/annihilation.html).

I'm merging this and then @hannahbrucemacdonald can merge in a PR from the `improve-docs` branch.

**Pull request merged**
