### PR TITLE
Create protein library

### PR DESCRIPTION
**Pull request by juliebehr**
Moved most of the functionality from ```PointMutationEngine``` into the parent ```PolymerEngine``` and created ```PeptideLibraryEngine``` with a unique ```_choose_mutant()``` method

Assuming the ```library``` input is a list of strings of 1-letter amino acid sequences

Currently no tests for ```PeptideLibraryEngine```

### CODE REVIEW

**Comment by juliebehr** [comment]
Errors:
```
======================================================================
ERROR: Testing expanded ensemble sampler with alkanes 'explicit'
----------------------------------------------------------------------
File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/topology_proposal.py", line 943, in _topology_to_smiles
    ValueError: More than one residue with the same name!

======================================================================
ERROR: Testing expanded ensemble sampler with alkanes 'vacuum'
----------------------------------------------------------------------
File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/topology_proposal.py", line 943, in _topology_to_smiles
    ValueError: More than one residue with the same name!

======================================================================
ERROR: Testing SAMS sampler with alkanes 'explicit'
----------------------------------------------------------------------
File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/topology_proposal.py", line 943, in _topology_to_smiles
    ValueError: More than one residue with the same name!

======================================================================
ERROR: Testing SAMS sampler with alkanes 'vacuum'
----------------------------------------------------------------------
File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/topology_proposal.py", line 943, in _topology_to_smiles
    ValueError: More than one residue with the same name!

======================================================================
ERROR: Testing MultiTargetDesign sampler with alkanes mutation transfer free energy from vacuum -> explicit
----------------------------------------------------------------------
File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/topology_proposal.py", line 943, in _topology_to_smiles
    ValueError: More than one residue with the same name!

======================================================================
ERROR: Testing MultiTargetDesign sampler with alkanes mutation transfer free energy from vacuum -> vacuum
----------------------------------------------------------------------
File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/topology_proposal.py", line 943, in _topology_to_smiles
    ValueError: More than one residue with the same name!

======================================================================
ERROR: Testing MultiTargetDesign sampler with alanine dipeptide mutation transfer free energy from vacuum -> vacuum
----------------------------------------------------------------------
File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 547, in _choose_torsion
    Exception: No eligible torsions found for placing atom <Atom CD1 [16]; In PHE 1>.

======================================================================
ERROR: Testing MultiTargetDesign sampler with alanine dipeptide mutation transfer free energy from vacuum -> implicit
----------------------------------------------------------------------
File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 547, in _choose_torsion
    Exception: No eligible torsions found for placing atom <Atom CD1 [16]; In PHE 1>.

```

Are these fixed somewhere else?

**Comment by jchodera** [comment]
No, we're waiting for @pgrinaway to fix them.  
* `ValueError: More than one residue with the same name!` is #110 
* `Exception: No eligible torsions found for placing atom <Atom CD1 [16]; In PHE 1>.` is #114

**Comment by jchodera** [comment]
#110 can be easily fixed.  Maybe I should just fix that now.

#114 will require a significant refactoring of the geometry engine, though @pgrinaway already has a start on that.

**Comment by juliebehr** [comment]
Should this wait to be merged?

**Comment by jchodera** [comment]
No, go ahead and merge it if it's ready!  Those other failures can't be resolved until #110 and #114 are fixed.

**Comment by juliebehr** [comment]
Ok great!

**Pull request merged**
