### PR TITLE
Propagation steps

### PR DESCRIPTION
**Pull request by juliebehr**
Creating the option in `NCMCEngine` to take multiple steps to propagate at each lambda step.

@pgrinaway

### CODE REVIEW

**Comment by jchodera** [comment]
Out of curiosity, what is the motivation here? Purely for debugging? I
think I can prove the thermodynamic length is always shorter if you take a
lambda step for every dynamics step.

**Comment by pgrinaway** [comment]
> I think I can prove the thermodynamic length is always shorter if you take a
lambda step for every dynamics step.

Is this true for GHMC propagators? I could see an efficiency argument (or the length argument for VV), but why would the number of steps of GHMC increase the thermodynamic length?

**Comment by pgrinaway** [comment]
Ok, thanks for the in-person explanation @jchodera . Seems that it's good to have this option but in general it will be more efficient to take smaller lambda steps than to do more propagation steps.

**Comment by juliebehr** [comment]
Merge?

**Comment by jchodera** [comment]
> Merge?

@pgrinaway: I think that's you!

**Comment by bas-rustenburg** [comment]
@jchodera : Has that notebook link been moved? I'm getting a 404 page. Just curious since I use similar schemes and would like to take a look at it.

**Comment by jchodera** [comment]
Looks like it has. Ask @gregoryross?

**Pull request merged**
