### PR TITLE
Updating complex.pdb in Abl Affinity test system

### PR DESCRIPTION
**Pull request by steven-albanese**
I updated the `complex.pdb` file used for the AblAffinityTestSystem. It had missing hydrogens and overlapping atoms. 

I fixed this using Ensembler to model ABL_HUMAN_D0 using `2HYY` PDB  as a template structure. I aligned this model to 2HYY to overlay imatinib in the correct place. I then manually dragged the ligand to resolve some overlap with sidechain atoms

### CODE REVIEW

**Comment by steven-albanese** [comment]
Just added the script I'm using for the src and abl multitarget design script. Also put `src-abl` directory in the `data` directory

**Comment by jchodera** [comment]
I think this should either go in `perses/tests/testsytems.py` as another test system---I think I would prefer this---or in `perses/examples/`, but we'd need to figure out a way to get the examples to be tested automatically if we go that route.

**Comment by steven-albanese** [comment]
I wasn't sure that you wanted it to be a test system, happy to put it there. I should do that from a fork though, correct?

**Comment by jchodera** [comment]
Hm. How about just moving it to `perses/examples/abl-src-selectivity/` or something for now?  We can figure out how to add extensive tests for examples later.

**Comment by steven-albanese** [comment]
+1 will do

**Pull request merged**
