### PR TITLE
Examples run phases in expected order

### LINKED ISSUE #1121: Make examples and templates run solvent phase first
We want in general to run the solvent phase before the complex phase in the examples and templates for benchmarks.

### PR DESCRIPTION
**Pull request by ijpulidos**
## Description

Changes the order how phases are run in the examples and templates for benchmarks. Making it to run vacuum, solvent and complex phases in that order.

## Motivation and context

Resolves #1121 

## How has this been tested?

Tested locally

## Change log

```
Examples and benchmarks template input files now run vacuum, solvent and complex phases in order.
```

### CODE REVIEW

**Review by jchodera — APPROVED** [review]
Thanks! This will help improve user experience!

**Comment by jchodera** [comment]
Interestingly, I'm seeing failures here:
```
=========================== short test summary info ============================
FAILED perses/tests/test_relative_setup.py::test_relative_setup_charge_change - AssertionError: charge diff is -1 but should be zero.
assert False
 +  where False = <function isclose at 0x7f79e2bf2430>(-1, 0)
 +    where <function isclose at 0x7f79e2bf2430> = <module 'numpy' from '/usr/share/miniconda/envs/test/lib/python3.8/site-packages/numpy/__init__.py'>.isclose
====== 1 failed, 97 passed, 21 skipped, 119 warnings in 681.62s (0:11:21) ======
```
@dominic-rufa @zhang-ivy : Any idea why this test might be failing?

**Comment by jchodera** [comment]
Oddly enough, the failures are with OpenMM 7.6 and the nightly build, but not OpenMM 7.7.

**Comment by mikemhenry** [comment]
@jchodera just for the record, we are tracking that error here:
https://github.com/choderalab/perses/issues/1113

**Pull request merged**
