### PR TITLE
Fix geometry engine torsion biases and MCSS overlap criteria

### PR DESCRIPTION
**Pull request by jchodera**
I've turned on writing of atom-by-atom PDBs for geometry proposals to debug what is going wrong with kinase inhibitors.

It looks like the torsion restraints are not actually biasing the placement of closed rings.  I don't know if there was somehow a reversion somewhere, since this was working before.

### CODE REVIEW

**Comment by jchodera** [comment]
I've made two major changes in this PR that fix the geometry engine failures for kinase inhibitors:
* MCSS criteria are modified to
```
        atomexpr = oechem.OEExprOpts_Aromaticity | oechem.OEExprOpts_RingMember | oechem.OEExprOpts_HvyDegree
        bondexpr = oechem.OEExprOpts_Aromaticity | oechem.OEExprOpts_RingMember 
```
* Torsion bias phase is mapped to `[-pi,+pi)` interval, which seems to be the domain OpenMM actually uses for torsion biases.  Previously, the domain was `[0,2*pi)`, which was causing the torsion bias to be totally unreliable.

@pgrinaway : Can you review and merge?

**Comment by jchodera** [comment]
When running `python perses/tests/testsystems.py`, I've noticed that the `geometry-proposal-*-forward-initial.pdb` structures look great, but the `kinase-inhibitors-vacuum-geometry-proposals.pdb` are terrible. I think there must be some topology corruption or mixup between the generation of these two files.

**Comment by jchodera** [comment]
I can't figure out what is going on.  The atom-by-atom PDB files in `_logp_propose` look great now, but the resulting `(topology_proposal.new_topology, geometry_new_positions)` pair seems to be totally messed up:
https://github.com/choderalab/perses/blob/master/perses/samplers/samplers.py#L723-L731

**Comment by jchodera** [comment]
The problem is just with the multi-model PDB files being read incorrectly by PyMOL. Trying to find a workaround.

**Comment by jchodera** [comment]
I'm not sure how to fix the issues with PyMOL reading multi-model connectivity rendering, so for now, I am just concatenating PDB files into a single file. This renders in PyMOL as separate objects---one per frame---but the manual inspection of structures looks good at this point.

Should be ready to review and merge.

**Comment by pgrinaway** [comment]
This looks fine to merge.

**Pull request merged**
