### PR TITLE
only run dev with newest python version

### PR DESCRIPTION
**Pull request by mikemhenry**
## Description

To save some compute time/carbon, we are only going to test `dev` with the latest python version.

## Motivation and context

Resolves #???

## Change log

```

```

### CODE REVIEW

**Comment by ijpulidos** [comment]
In this case we are not using the `dev` versions from OpenMM, since we currently rely on the `matrix.openmm` option to install them in https://github.com/choderalab/perses/blob/c7971dbea0162f31a6771a0f35f55ae3efe21552/.github/workflows/CI.yaml#L55

**Comment by ijpulidos** [comment]
I just double checked that this is indeed the case for example in https://github.com/choderalab/perses/actions/runs/4295333336/jobs/7485595343#step:7:236

**Comment by ijpulidos** [comment]
Oh, but according to documentation using `include` should work for this, exactly as you proposed it. Not sure why it isn't working as expected then.

**Comment by mikemhenry** [comment]
I think I fixed it, the problem (I think) was the lack of telling micromamba to reinstall if the package is in the env. It would be faster and better to use this kind of syntax to install openmm:
```
extra-specs: |
  python=${{ matrix.python-version }}
```

but that would then crash on "dev" but would work for the other openmm version strings... but I have an idea!

**Review by ijpulidos — APPROVED** [review]
This looks good, thanks!

I think eventually we do want to think about not having to manually change the openmm dev version every time there's a new build.

**Pull request merged**
