### PR TITLE
SAMS sampler and other improvements

### PR DESCRIPTION
**Pull request by pgrinaway**
This PR contains a set of improvements including SAMS support, as well as additional yaml options and the ability to rapidly record shadow work.

### CODE REVIEW

**Comment by jchodera** [comment]
@pgrinaway : Awesome! It looks like there are some conflicts with `master`.

**Comment by pgrinaway** [comment]
Conflicts resolved. I'm going to make sure the tests pass and then merge.

**Comment by pgrinaway** [comment]
@brycestx Do you know what the right way to deal with the method call [here](https://github.com/choderalab/perses/blob/149ef1eb9a0fe5bebe5ced191102c1bb60f9b9e3/perses/tests/utils.py#L567) is? The docs suggest that method takes only one parameter, and I'm not exactly sure what that code was trying to do.

**Comment by pgrinaway** [comment]
Ah, finally, tests pass! Merging.

**Pull request merged**
