### PR TITLE
Revert "Update travis tests for new openmm-forcefields package to fix failing travis tests"

### PR DESCRIPTION
**Pull request by hannahbrucemacdonald**
Reverts choderalab/perses#623

### CODE REVIEW

**Comment by hannahbrucemacdonald** [comment]
This should return master to it's original state

**Comment by jchodera** [comment]
@hannahbrucemacdonald: I must have missed the original issue somehow: Why was the revert needed, and if I continue to fix these tests in a separate PR, should I base that PR on master or another branch?

**Comment by hannahbrucemacdonald** [comment]
I accidentally merged the changes into master, so I reverted master so that it could be merged properly when it’s ready - sorry

**Comment by jchodera** [comment]
Totally fine, thanks!

**Pull request merged**
