### PR TITLE
Disable slow tests and switch to py35 and py36

### PR DESCRIPTION
**Pull request by pgrinaway**
Just trying to disable the slow tests. Not sure why `skipIf` isn't skipping some tests...

### CODE REVIEW

**Comment by pgrinaway** [comment]
Looks like the reason those slow tests weren't being disabled was because the conda build was failing, and it was installing + testing an old version (thanks for discovering this @jchodera). We've removed the packages from the cloud, and have commented out the command to push to the cloud.

**Comment by pgrinaway** [comment]
See #387 for conda issue discussion.

**Comment by jchodera** [comment]
Looks like you fixed it by pinning `conda-build` to 2.1.17! Tests are running to completion (though it looks like some tests have caught issues). 

Those issues should probably be addressed in separate PRs as needed.

It may be worth dropping python 2.7 and 3.4 and adding 3.6 so that we only support 3.5 and 3.6 going forward. That will simplify the code.

**Comment by jchodera** [comment]
Note, for example, that new `openmmtools` releases are no longer built for Python 3.4, so we can no longer support it here either.

**Comment by pgrinaway** [comment]
>It may be worth dropping python 2.7 and 3.4 and adding 3.6 so that we only support 3.5 and 3.6 going forward. That will simplify the code.

Agreed, I'll do that now.

**Comment by pgrinaway** [comment]
@jchodera In this PR I've:

* Pinned the conda build version to the same one as `yank`
* Changed the environments to include only Python 3.5 and 3.6
* Unpinned numpy (which does not seem to be giving a problem)

If you could take a quick pass through and make sure that nothing seems terribly wrong, that would be great. Thanks!

**Comment by pgrinaway** [comment]
cc: #387 , resolved by this PR.

**Comment by pgrinaway** [comment]
Hm, nope, seems py36 is still failing.

**Comment by pgrinaway** [comment]
Oh, I need to unpin another one.

**Comment by jchodera** [comment]
The tests seem to be running, but the NCMC tests also seem to be running---was that intended?
```
Testing VV NCMC switching using harmonic oscillator with 0 NCMC steps ...    0.043 +- 0.156 kT
ok (34.4397s)
Testing VV NCMC switching using harmonic oscillator with 1 NCMC steps ...    0.133 +- 0.173 kT
ok (34.4379s)
Testing VV NCMC switching using harmonic oscillator with 50 NCMC steps ...   -0.009 +- 0.017 kT
ok (48.3885s)
Testing GHMC NCMC switching using harmonic oscillator with 0 NCMC steps ...   -0.314 +- 0.144 kT
ok (34.6554s)
Testing GHMC NCMC switching using harmonic oscillator with 1 NCMC steps ... 
```

**Comment by jchodera** [comment]
It's [this test](https://github.com/choderalab/perses/blob/3f4b744403cd11626959ab43627cecf94107b54d/perses/tests/test_ncmc_integrator.py#L142-L151) that's still running NCMC tests to test `NCMCVVAlchemicalIntegrator` and `NCMCGHMCAlchemicalIntegrator`. Do you still use those in the current application? If not, maybe add the travis skip there too?

**Comment by pgrinaway** [comment]
Ok, looks like the errors are currently unrelated (will raise issue to document), and this is complete.

**Pull request merged**
