### PR TITLE
Add a T4 inhibitors + lysozyme testsystem

### PR DESCRIPTION
**Pull request by pgrinaway**
This PR: 

* Adds a T4 inhibitors + protein affinity test system

* Adds a clean list of smiles

* Fixes the clean smiles generation by using networkx

* Adds scripts for preparation.

### CODE REVIEW

**Comment by jchodera** [comment]
> Adds a clean list of smiles

Which of the `clean_smiles_*` files here are the ones to look at?

Can you add a `README.md` documenting the protocol here and what the files contain?

**Comment by pgrinaway** [comment]
Yep.

**Comment by jchodera** [comment]
Could this be merged?

**Comment by pgrinaway** [comment]
need to fix this up first. closing for now.

**Pull request closed without merging**
