### PR TITLE
Improve docker building

### PR DESCRIPTION
**Pull request by mikemhenry**
## Motivation and context

Resolves #???

## Change log

```

```

### CODE REVIEW

**Review by ijpulidos — APPROVED** [review]
This is going to be very useful, thanks! LGTM

**Comment by ijpulidos** [comment]
I see running the examples test is failing. We probably need to find a better way to run/test the examples. When I first created this test it was done in a hacky way.

**Comment by mikemhenry** [comment]
Okay if this passes then I need to remove the trigger that builds on a push to the PR branch and we should be good to merge

**Comment by mikemhenry** [comment]
Ah yes, I forgot I need to make a perses release with the examples removed for this to pass because I use the conda-forge package to create this image.

**Pull request merged**
