### PR TITLE
Add numpy array writing and NCMC analysis to storage layer

### PR DESCRIPTION
**Pull request by jchodera**
This PR adds numpy array writing to the storage layer and instruments various parts of the code.

TODO:
- [x] numpy array writing (singletons and per-iteration)
- [x] add option to write NCMC work as a function of step number

Anything else we want to record?

### CODE REVIEW

**Comment by pgrinaway** [comment]
I think this looks good!

**Comment by jchodera** [comment]
I did a small amount of refactoring to reduce the amount of information that needs to be passed around, so will check that in and instrument the NCMC work and molecule transition matrix once the fiRASco is dealt with.

**Comment by jchodera** [comment]
This should be usable now.

I have:
* Refactored the storage class a bit to make it easier to store things without having to pass tons of information around, via introducing a `NetCDFStorageView` that can attach `envname` and/or `modname`
* Instrumented the NCMC switching to store `work_insert` and `work_delete`
* Instrumented `SmallMoleculeSetProposalEngine`
* All `testsystems` now can utilize storage by constructing them with a `storage_filename` argument, e.g.:
```python
testsystem = T4LysozymeInhibitorsTestSystem(storage_filename='output.nc')
```
I think this was everything @pgrinaway enumerated in his wish list. More can easily be added by following the examples.

I'll tackle the topology/configuration snapshot writing in a separate PR, but let me know if you need anything else.

Ready for review and merge.

**Comment by jchodera** [comment]
Trying to fix some weird python 3 issues with modules not being found, but I think the storage is working now.

The resulting structure that gets set up in the NetCDF file is pretty simple: You access the variable you want via `ncfile['/environment/module/variable']`. For example:
```python
>>> import netCDF4 as nc
>>> ncfile = nc.Datasets('output.nc', 'r')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Datasets'
>>> ncfile = nc.Dataset('output.nc', 'r')
>>> ncfile['/vacuum/NCMCEngine/work_insert']
<type 'netCDF4._netCDF4.Variable'>
float64 work_insert(iterations, work_insert0)
path = /vacuum/NCMCEngine
unlimited dimensions: iterations
current shape = (50, 500)
filling on, default _FillValue of 9.96920996839e+36 used

>>> ncfile['/vacuum/NCMCEngine/work_insert'][0,:]
...
```
You can use `ncdump -h output.nc` to inspect the variable structure.

For `ValenceSmallMoleculeLibraryTestSystem`, which only has a `vacuum` phase, this is:
```
[LSKI1497:choderalab/perses/perses.choderalab] choderaj% ncdump -h output.nc
netcdf output {
dimensions:
	iterations = UNLIMITED ; // (50 currently)
	work_delete0 = 500 ;
	work_insert0 = 500 ;

group: vacuum {

  group: MCMCSampler {
    variables:
    	double kinetic_energy(iterations) ;
    	double potential_energy(iterations) ;
    	double volume(iterations) ;
    } // group MCMCSampler

  group: NCMCEngine {
    variables:
    	double work_delete(iterations, work_delete0) ;
    	double work_insert(iterations, work_insert0) ;
    } // group NCMCEngine

  group: ExpandedEnsembleSampler {
    variables:
    	string state_key(iterations) ;
    	double naccepted(iterations) ;
    	double nrejected(iterations) ;
    	double logp_accept(iterations) ;
    	double logp_topology_proposal(iterations) ;
    	double logp_geometry(iterations) ;
    	double logp_switch(iterations) ;
    	double logp_ncmc_elimination(iterations) ;
    	double logp_ncmc_introduction(iterations) ;
    	double new_log_weight(iterations) ;
    	double old_log_weight(iterations) ;
    } // group ExpandedEnsembleSampler

  group: SAMSSampler {
    variables:
    	string logZ(iterations) ;
    	string log_weights(iterations) ;
    } // group SAMSSampler
  } // group vacuum
}
```

**Comment by jchodera** [comment]
Whoops, had to fix some issues that didn't appear in my earlier tests.

Here is the NetCDF structure for the full `T4LysozymeInhibitorsTestSystem` that I think you are targeting right now:
```
[LSKI1497:choderalab/perses/perses.choderalab] choderaj% ncdump -h output.nc 
netcdf output {
dimensions:
	iterations = UNLIMITED ; // (5 currently)
	explicit_NCMCEngine_work_delete_0 = 50 ;
	explicit_NCMCEngine_work_insert_0 = 50 ;
	vacuum_NCMCEngine_work_delete_0 = 50 ;
	vacuum_NCMCEngine_work_insert_0 = 50 ;

group: explicit {

  group: MCMCSampler {
    variables:
    	double kinetic_energy(iterations) ;
    	double potential_energy(iterations) ;
    	double volume(iterations) ;
    } // group MCMCSampler

  group: NCMCEngine {
    variables:
    	double work_delete(iterations, explicit_NCMCEngine_work_delete_0) ;
    	double work_insert(iterations, explicit_NCMCEngine_work_insert_0) ;
    } // group NCMCEngine

  group: ExpandedEnsembleSampler {
    variables:
    	string state_key(iterations) ;
    	double naccepted(iterations) ;
    	double nrejected(iterations) ;
    	double logp_accept(iterations) ;
    	double logp_topology_proposal(iterations) ;
    	double logp_geometry(iterations) ;
    	double logp_switch(iterations) ;
    	double logp_ncmc_elimination(iterations) ;
    	double logp_ncmc_introduction(iterations) ;
    	double new_log_weight(iterations) ;
    	double old_log_weight(iterations) ;
    } // group ExpandedEnsembleSampler

  group: SAMSSampler {
    variables:
    	string logZ(iterations) ;
    	string log_weights(iterations) ;
    } // group SAMSSampler
  } // group explicit

group: vacuum {

  group: MCMCSampler {
    variables:
    	double kinetic_energy(iterations) ;
    	double potential_energy(iterations) ;
    	double volume(iterations) ;
    } // group MCMCSampler

  group: NCMCEngine {
    variables:
    	double work_delete(iterations, vacuum_NCMCEngine_work_delete_0) ;
    	double work_insert(iterations, vacuum_NCMCEngine_work_insert_0) ;
    } // group NCMCEngine

  group: ExpandedEnsembleSampler {
    variables:
    	string state_key(iterations) ;
    	double naccepted(iterations) ;
    	double nrejected(iterations) ;
    	double logp_accept(iterations) ;
    	double logp_topology_proposal(iterations) ;
    	double logp_geometry(iterations) ;
    	double logp_switch(iterations) ;
    	double logp_ncmc_elimination(iterations) ;
    	double logp_ncmc_introduction(iterations) ;
    	double new_log_weight(iterations) ;
    	double old_log_weight(iterations) ;
    } // group ExpandedEnsembleSampler

  group: SAMSSampler {
    variables:
    	string logZ(iterations) ;
    	string log_weights(iterations) ;
    } // group SAMSSampler
  } // group vacuum

group: MultiTargetDesign {
  variables:
  	string log_target_probabilities(iterations) ;
  } // group MultiTargetDesign
}
```

**Comment by jchodera** [comment]
I'm confused about the python 3 failures...

**Comment by jchodera** [comment]
I've added a basic analysis framework:
```python
from perses.analysis import Analysis
analysis = Analysis(storage_filename)
analysis.plot_ncmc_work('ncmc.pdf')
```
but it looks like our old friend `No eligible torsions` is back:
```
Traceback (most recent call last):
  File "perses/tests/testsystems.py", line 2071, in <module>
    run_t4_inhibitors()
  File "perses/tests/testsystems.py", line 1856, in run_t4_inhibitors
    testsystem.designer.run(niterations=50)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/samplers/samplers.py", line 1181, in run
    self.update()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/samplers/samplers.py", line 1163, in update
    self.update_samplers()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/samplers/samplers.py", line 1124, in update_samplers
    sampler.update()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/samplers/samplers.py", line 1032, in update
    self.update_sampler()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/samplers/samplers.py", line 996, in update_sampler
    self.sampler.update()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/samplers/samplers.py", line 863, in update
    self.update_state()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/samplers/samplers.py", line 769, in update_state
    geometry_new_positions, geometry_logp_propose = self.geometry_engine.propose(topology_proposal, geometry_old_positions, self.sampler.thermodynamic_state.beta)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/rjmc/geometry.py", line 111, in propose
    logp_proposal, new_positions = self._logp_propose(top_proposal, current_positions, beta, direction='forward')
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/rjmc/geometry.py", line 938, in _logp_propose
    atom_proposal_order, logp_choice = proposal_order_tool.determine_proposal_order(direction='forward')
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/rjmc/geometry.py", line 2053, in determine_proposal_order
    chosen_torsion, logp_choice = self._choose_torsion(atoms_with_positions, atom)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/rjmc/geometry.py", line 2100, in _choose_torsion
    raise NoTorsionError("No eligible torsions found for placing atom %s." % str(atom_for_proposal))
perses.rjmc.geometry.NoTorsionError: No eligible torsions found for placing atom <Atom S1 [3]; In MOL 0>.
```

**Comment by jchodera** [comment]
Here's an example of the `analysis.plot_ncmc_work()` output:
image

**Comment by jchodera** [comment]
I've fixed the py3 test issues. For the record, I:
* converted conda dev recipe to use release versions of packages
* fixed some imports
* fixed some `__init__.py` issues

**Comment by jchodera** [comment]
Here's a neat plot showing the NCMC work (for 50-step NCMC switching with GHMC) for the `ImidazoleProtonationStateTestSystem` consisting of imidazole in explicit solvent. You can see why the NCMC-RJMC-NCMC scheme may be a poor choice for transitions involving moving charges around!
image

To me, this result suggests why we really want to switch to RJMC-NCMC-RJMC, @juliebehr and @pgrinaway

**Comment by jchodera** [comment]
Tests pass!  Ready for review.

**Comment by jchodera** [comment]
Python 3.x issues are all fixed!

**Comment by pgrinaway** [comment]
Thanks! Reviewing...

**Pull request merged**
