### PR TITLE
Implement CBMC and GHMC NCMC

### PR DESCRIPTION
**Pull request by pgrinaway**
WIP. @jchodera I was wondering if you have a chance if you can take a look at the NCMC GHMC integrator in this PR--not sure why it's failing the test. I'll continue with the CPF in the meantime.

### CODE REVIEW

**Comment by pgrinaway** [comment]
Also, maybe I can raise an issue on `pymbar`, but the uncertainty is occasionally `nan`. Taking a quick pass with the debugger, it seems the variance is sometimes calculated as slightly negative (`-1e-18 `ish), which I guess is some numerical instability.

**Comment by jchodera** [comment]
Just noting that we found the bug: The `step` counter and `total_work` need to be reset to 0 before performing a new switching iteration.  @pgrinaway will add an `integrator.reset()` call to do this.

@pgrinaway: This may need to be fixed elsewhere in other tests or in the `ExpandedEnsembleSampler` as well.

**Comment by jchodera** [comment]
Hm. Looks like the valence system is exploding on travis:
```
======================================================================
ERROR: Run abl test system.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/tests/testsystems.py", line 1455, in test_valence_write_pdb_ncmc_switching
    testsystem.exen_samplers[environment].run(niterations=1)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 820, in run
    self.update()
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 799, in update
    self.update_state()
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 742, in update_state
    [ncmc_new_positions, ncmc_introduction_logp, potential_insert] = self.ncmc_engine.integrate(topology_proposal, geometry_new_positions, direction='insert')
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/annihilation/ncmc_switching.py", line 381, in integrate
    raise e
ValueError: coordinate "-10202360.0323" could not be represented in a width-8 field
-------------------- >> begin captured logging << --------------------
```

**Comment by jchodera** [comment]
Please raise an issue on pymbar. We need to document these issues.

If you can also dump an input dataset when you see the error, that would be
even more awesome.

**Comment by jchodera** [comment]
Somehow some crazy debug information was left on that is filling up travis:
```
Testing alchemical null elimination for 'pentane' with 1 NCMC steps ... Initial potential is 25.8227638998
Potential at step 0 is 12.2348520936
and the integrator's current step is 1
Initial potential is 12.2348520936
Potential at step 0 is 34.1349678979
and the integrator's current step is 1
Initial potential is 27.0118558527
Potential at step 0 is 11.7079097372
and the integrator's current step is 1
```

**Comment by jchodera** [comment]
It doesn't look like there were any updates to this PR since the NCMC fix got merged in 8 days ago.  I have no idea where current development is happening.  Which branch should I use to generate more movies from, @pgrinaway?  

Can we try to keep things more tidy here?  I realize this is primarily your repo, @pgrinaway, but we have one PR that has been awaiting review for 15 days (#204) and another that hasn't been touched in 8 days with critical bugfixes merged in but no subsequent action.  Going forward, it would really help if:
* There was an obvious main branch to work from
* PRs were reviewed and merged in a timely manner
* Commits were kept up to date

**Comment by pgrinaway** [comment]
>It doesn't look like there were any updates to this PR since the NCMC fix got merged in 8 days ago. I have no idea where current development is happening.

Sorry about that, looks like I had forgotten to push my commits (did that saturday night as soon as I saw this).

>Can we try to keep things more tidy here?  I realize this is primarily your repo, @pgrinaway

Absolutely. I have a few ideas on how to tidy up the repo, but first I think it would be really helpful if you and I had a brief meeting about how this repo is managed. I'm happy to take over everything, but that would presumably entail other consequences, so it'd be good to have a discussion.

>one PR that has been awaiting review for 15 days (#204)

I'm sorry--I really am not sure what to make of that PR. As I said above, I'm happy to adjust my role, but let's have a meeting about this.

I agree completely with the rest of your suggestions, and once we decide on the above then I'm happy to go about implementing them. Sorry for any inconvenience/extra work incurred in making your talk.

**Comment by jchodera** [comment]
Sorry, just saw this. Let's have a quick chat about repo management while we're here in boston.

**Comment by jchodera** [comment]
We had a quick chat in Boston, but let's get the Perses team together to chat about good repo management habits and coordination next week.

**Comment by jchodera** [comment]
I can't see what is going on if people aren't pushing their code, for example.

**Comment by pgrinaway** [comment]
Sorry--had some extra crap in there. Getting rid of it. Hopefully the last commit irons things out.

**Comment by jchodera** [comment]
Looks like you still have some actual errors:
```

======================================================================
ERROR: Test NCMCAlchemicalIntegrator
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/tests/test_elimination.py", line 215, in test_ncmc_alchemical_integrator_stability_molecules
    if np.isnan(ncmc_integrator.getLogAcceptanceProbability(context)):
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/annihilation/ncmc_switching.py", line 611, in getLogAcceptanceProbability
    logp_accept = -1.0*self.getGlobalVariableByName("total_work") * unit.kilojoules_per_mole / self.kT
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 5080, in getGlobalVariableByName
    return _openmm.CustomIntegrator_getGlobalVariableByName(self, name)
Exception: Illegal global variable name: total_work
-------------------- >> begin captured logging << --------------------
```

**Comment by jchodera** [comment]
Looks like that was my fault. [These lines](https://github.com/choderalab/perses/blob/dcc9e36f8c5b5e5841c1528db9aa1c8fcaa6a094/perses/tests/test_elimination.py#L199-L202) try to instantiate an `NCMCAlchemicalIntegrator`, which is a virtual base class and should never be instantiated.  This should be changed to `NCMCGHMCAlchemicalIntegrator` or `NCMCVVAlchemicalIntegrator` (ideally just test both) instead.

**Comment by pgrinaway** [comment]
Yeah. I'll change it to `NCMCGHMCAlchemicalIntegrator` for now. After I get the scheduling stuff done, I'll fix the test to test both.

**Comment by pgrinaway** [comment]
hm, trying to debug [this](https://travis-ci.org/choderalab/perses/jobs/132916319#L801-L806) now.

**Comment by jchodera** [comment]
Mind if I take a stab at that in a separate PR?

**Comment by pgrinaway** [comment]
Sure. Do you want me to merge this?

**Comment by jchodera** [comment]
Yes, if that's the only issue.

**Comment by pgrinaway** [comment]
AFAICT it is, unless you or @juliebehr or @steven-albanese want to review it first.

**Comment by steven-albanese** [comment]
Looks fine to me

**Comment by jchodera** [comment]
Anything keeping you from checking this in, @pgrinaway ?

**Comment by pgrinaway** [comment]
Just being underground! Merging now.

**Comment by jchodera** [comment]
Great. I'll debug the NCMC stuff now.

**Comment by jchodera** [comment]
That's odd...I can't get the same test to fail on my machine.

**Comment by jchodera** [comment]
```
mski1776:perses.choderalab choderaj$ nosetests -vv --nocapture perses/tests/test_elimination.py
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
Testing alchemical null transformation of ALA sidechain in alanine dipeptide with 0 NCMC steps ... ok
Testing alchemical null transformation of ALA sidechain in alanine dipeptide with 1 NCMC steps ... ok
Testing alchemical null transformation of ALA sidechain in alanine dipeptide with 2 NCMC steps ... ok
Testing alchemical null transformation of ALA sidechain in alanine dipeptide with 50 NCMC steps ... ok
Test NCMCAlchemicalIntegrator ... ok
Testing alchemical null elimination for 'pentane' with 0 NCMC steps ... ok
Testing alchemical null elimination for 'pentane' with 1 NCMC steps ... ok
Testing alchemical null elimination for 'pentane' with 50 NCMC steps ... ok
Testing alchemical null elimination for 'biphenyl' with 0 NCMC steps ... ok
Testing alchemical null elimination for 'biphenyl' with 1 NCMC steps ... ok
Testing alchemical null elimination for 'biphenyl' with 50 NCMC steps ... ok
Testing alchemical null elimination for 'imatinib' with 0 NCMC steps ... ok
Testing alchemical null elimination for 'imatinib' with 1 NCMC steps ... ok
...
```

**Comment by jchodera** [comment]
OK, it failed on `imatinib`:
```
======================================================================
ERROR: Testing alchemical null elimination for 'imatinib' with 50 NCMC steps
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/tests/test_elimination.py", line 133, in check_alchemical_null_elimination
    raise Exception(msg)
Exception: Delta F (50 steps switching) = 28.270269 +- 0.979495 kT; should be within 6.000000 sigma of 0
delete logP:
[  95.29421621   85.67623038  105.87101102   98.04602901  128.61125504
  124.31579705  141.23525317  124.34088197  123.95649417  118.87735458
  119.40309546  121.57280351   91.47024886  105.77686843  113.02335944
  121.73605836  113.92798312  117.74789962  120.39908894  115.98979651
   90.17229583  112.54922806   81.40181727  116.69019441  106.30033816
  107.41723778  128.36642148  117.61966249  112.19382297   94.44159255
  126.69930782  113.00126349  105.84609801  123.23010631   98.85468696
  103.81532656  121.92455173  109.73925085  107.42119057   99.87411296
  101.91960374  126.30618849  122.7203355    86.38178059  110.71512592
   99.96748411  104.98604827  105.81011653  108.99624907  116.91920176]
insert logP:
[-183.99841755 -167.23672402 -149.68330468 -148.96825066 -174.32278336
 -169.14994164 -200.10875481 -191.87699645 -190.51292734 -148.02267537
 -172.04178238 -184.97139552 -200.56898405 -159.15056572 -199.62479217
 -175.72595304 -187.73711387 -210.05306041 -223.02867196 -210.62354834
 -114.54098139 -146.24603532 -202.99710192 -185.8856566  -155.75579484
 -190.10805898 -242.09854649 -199.32458383 -147.28599048 -145.32756202
 -182.96214627 -173.2617685  -180.16827902 -159.92316182 -129.5448499
 -148.61574674 -183.98716193 -166.6457058  -175.70324859 -172.86486089
 -162.80545772 -196.00240381 -185.87627656 -200.15263615 -159.46375683
 -164.18299061 -210.88550397 -138.93525449 -156.53873371 -190.91672523]
logP:
[ -88.70420134  -81.56049364  -43.81229366  -50.92222165  -45.71152832
  -44.83414458  -58.87350164  -67.53611448  -66.55643317  -29.14532079
  -52.63868692  -63.39859201 -109.09873519  -53.37369729  -86.60143273
  -53.98989468  -73.80913075  -92.30516079 -102.62958302  -94.63375183
  -24.36868556  -33.69680726 -121.59528465  -69.19546218  -49.45545669
  -82.6908212  -113.73212501  -81.70492134  -35.09216752  -50.88596948
  -56.26283845  -60.260505    -74.32218101  -36.69305551  -30.69016294
  -44.80042017  -62.06261021  -56.90645495  -68.28205802  -72.99074794
  -60.88585398  -69.69621532  -63.15594106 -113.77085556  -48.74863091
  -64.2155065  -105.8994557   -33.12513796  -47.54248464  -73.99752347]
```
I thought I had seen and fixed this at some point, and the issue had to do with the alchemical softening of valence terms.

**Comment by pgrinaway** [comment]
Hm thanks @steven-albanese , do you recall if there was an issue for this? I wonder how that would cause the issue...

**Comment by jchodera** [comment]
Yep, it was the `alchemical_angles=True` switch. If I set `alchemical_angles=None` again, I get:
```
Using /Users/choderaj/miniconda/lib/python2.7/site-packages
Finished processing dependencies for perses==0.1
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
Testing alchemical null transformation of ALA sidechain in alanine dipeptide with 0 NCMC steps ... ok
Testing alchemical null transformation of ALA sidechain in alanine dipeptide with 1 NCMC steps ... ok
Testing alchemical null transformation of ALA sidechain in alanine dipeptide with 2 NCMC steps ... ok
Testing alchemical null transformation of ALA sidechain in alanine dipeptide with 50 NCMC steps ... ok
Test NCMCAlchemicalIntegrator ... ok
Testing alchemical null elimination for 'imatinib' with 0 NCMC steps ... ok
Testing alchemical null elimination for 'imatinib' with 1 NCMC steps ... ok
Testing alchemical null elimination for 'imatinib' with 50 NCMC steps ... ok
Testing alchemical null elimination for 'pentane' with 0 NCMC steps ... ok
Testing alchemical null elimination for 'pentane' with 1 NCMC steps ... ok
Testing alchemical null elimination for 'pentane' with 50 NCMC steps ... ok
Testing alchemical null elimination for 'biphenyl' with 0 NCMC steps ... ok
Testing alchemical null elimination for 'biphenyl' with 1 NCMC steps ... ok
Testing alchemical null elimination for 'biphenyl' with 50 NCMC steps ... ok
Testing alchemical elimination using alanine dipeptide with 0 NCMC steps ... ok
Testing alchemical elimination using alanine dipeptide with 1 NCMC steps ... ok
Testing alchemical elimination using alanine dipeptide with 50 NCMC steps ... ok

----------------------------------------------------------------------
Ran 17 tests in 458.662s
```
@pgrinaway: Had you turned this back on by default without changing the alchemical `default_functions` protocol for angles?  If you turn the angles all the way off, Very Bad Things (TM) are guaranteed to happen.

**Comment by jchodera** [comment]
> Hm thanks @steven-albanese , do you recall if there was an issue for this? I wonder how that would cause the issue...

???

**Comment by pgrinaway** [comment]
I was wondering if he had raised a github issue somewhere. I wanted to see what was causing it.

That might have been my fault, turning `alchemical_angles` back on. Sorry.

**Comment by jchodera** [comment]
> That might have been my fault, turning alchemical_angles back on. Sorry.

I think this might be a bug in https://github.com/choderalab/alchemy, since even setting the `lambda_angles` function to `1` (which should not soften any angles) causes the tests to fail!
```
======================================================================
ERROR: Testing alchemical null transformation of ALA sidechain in alanine dipeptide with 2 NCMC steps
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/tests/test_elimination.py", line 133, in check_alchemical_null_elimination
    raise Exception(msg)
Exception: Delta F (2 steps switching) = 6.493700 +- 0.317974 kT; should be within 6.000000 sigma of 0
delete logP:
[-79.70428141 -80.83932505 -76.8615626  -82.60606613 -86.03060286
 -81.71043243 -80.0661826  -79.34087854 -80.38196626 -75.51265159
 -76.26955668 -73.4648813  -79.29217533 -79.97858927 -79.55299606
 -80.12284889 -82.80955511 -85.36092265 -83.69035794 -84.66686886
 -83.90630515 -78.46987044 -85.44788896 -86.59241216 -85.80761046
 -84.13009688 -86.05525829 -87.00567413 -81.8206416  -77.54424972
 -81.68716999 -78.20453923 -77.98520899 -82.79431237 -78.52813593
 -79.83464661 -87.91354246 -85.33079371 -74.97188706 -78.96469259
 -75.75294977 -76.18923385 -74.60409777 -78.56556047 -76.68058365
 -80.21437615 -76.74648416 -78.98927248 -74.30864834 -79.11703895]
insert logP:
[ 72.74363482  73.23420777  68.10794608  75.86894404  81.53708021
  72.76379023  71.91466909  72.8131977   71.60748884  67.95741827
  66.3498206   64.2769053   60.06253775  75.70326373  75.31892855
  69.42001191  74.29313664  73.00888961  75.50409717  79.52910367
  76.10609788  69.25754533  74.16873518  82.02559285  77.6483282
  69.26191363  77.75386101  80.86504407  75.54926068  65.09575461
  74.72553539  70.39168886  69.09763387  76.23984347  66.672109
  68.68338712  78.43566881  78.78423516  67.96189314  69.55944398
  64.80455292  62.74293809  64.13150335  70.35453868  66.58393681
  72.38839892  69.41483385  69.83439885  66.90193814  72.33572674]
logP:
[ -6.9606466   -7.60511728  -8.75361652  -6.73712209  -4.49352265
  -8.9466422   -8.15151352  -6.52768085  -8.77447741  -7.55524888
  -9.91973608  -9.187976   -19.22963758  -4.27532554  -4.23406751
 -10.70283697  -8.51641847 -12.35203305  -8.18626077  -5.13776519
  -7.80020727  -9.21232511 -11.27915379  -4.56683116  -8.15928226
 -14.86818324  -8.30139728  -6.14063006  -6.27138092 -12.4484951
  -6.9616346   -7.81285038  -8.88757512  -6.55446891 -11.85602693
 -11.15125949  -9.47787365  -6.54655855  -7.00999391  -9.40524861
 -10.94839684 -13.44629576 -10.47259443  -8.21102179 -10.09664684
  -7.82597723  -7.33165031  -9.15487363  -7.4067102   -6.78131221]
```

**Comment by jchodera** [comment]
I've created a PR to fix this (#207) for now.

**Comment by pgrinaway** [comment]
Thanks!

**Pull request merged**
