### PR TITLE
Fixing Geometry errors

### PR DESCRIPTION
**Pull request by pgrinaway**
Fixed a couple of issues, still have a couple more to go. WIP, hopefully can fix these today.

### CODE REVIEW

**Comment by pgrinaway** [comment]
Main test issues are fixed. Now:
* issue in #114 (and duplicates) will be fixed. 

* Adding `skipIf` statements

**Comment by pgrinaway** [comment]
Ok, so I implemented a fix for the eligible torsion thing. However, it seems that the current criteria are then sufficient to cause some members of the `ValenceSmallMoleculeLibraryTestSystem` to become unreachable from the rest. I just need to correct the array there, and have a warning saying which molecules have been removed.

**Comment by jchodera** [comment]
> Ok, so I implemented a fix for the eligible torsion thing. However, it seems that the current criteria are then sufficient to cause some members of the ValenceSmallMoleculeLibraryTestSystem to become unreachable from the rest. I just need to correct the array there, and have a warning saying which molecules have been removed.

Do you mean that some molecules cannot be reached from *any* molecule in the set, or that some molecules cannot be reached from *every* molecule in the set?

Put another way: If I make a graph of molecules as nodes connected by edges that correspond to transitions `GeometryEngine` can handle, do I end up with disjoint subgraphs?  Or just a graph that isn't densely connected?

**Comment by pgrinaway** [comment]
It actually ends up with disjoint subgraphs. I suppose this is the tradeoff between very conservative atom maps that delete most of the old atoms, and ones that leave old atoms in at the risk of creating untenable structures.

For now, I was going to just remove those molecules with a warning. Alternatively, we could alter the atom mapping criterion such that all molecules are connected to at least one other. Finally, we could also modify the `GeometryEngine` such that it can propose with less than one torsion (though I'd save this for later).

Next, I'll implement the visualization stuff so that we can have a better look at what's going on!

**Comment by jchodera** [comment]
Thanks for the clarification!

My thinking (not necessarily correct) is to prioritize:
0. bugfixes to get things to run at all
1. visualization (so we know what is going on, can have things for paper, etc.)
2. minimal modifications to get essential systems to be used in the paper (amino acids, T4 lysozyme ligands) to run
3. optimizations to make MCSS criteria more permissive for other ligand sets (kinase inhibitors, etc)
4. optimizations to ligand proposal scheme to increase acceptance probabilities
5. considering how to allow `GeometryEngine` to make more flexible proposals if item 3 still doesn't help

**Comment by pgrinaway** [comment]
I agree with your priorities, thanks for the input!

**Comment by pgrinaway** [comment]
Ok, so I added in code to avert the torsion disaster. But now there is another issue: what if one of the chemical states that the `ProposalEngine` removes is the starting state? I'm tempted to say throwing an exception might be practical here. After all, the user has supplied input that cannot be used.

As an aside, the entire `ValenceSmallMoleculeLibraryTestSystem` is disconnected under the current atom mapping scheme.

**Comment by pgrinaway** [comment]
Perhaps we should include specification of atom mapping criteria in the constructor.

**Comment by pgrinaway** [comment]
Ah, there's another issue with it. Hang on...

**Comment by pgrinaway** [comment]
Ok, I see what's wrong. One second

**Comment by pgrinaway** [comment]
Currently we're retaining 54/115 molecules in the T4 inhibitor test system with current atom mapping options.

**Comment by jchodera** [comment]
> Currently we're retaining 54/115 molecules in the T4 inhibitor test system with current atom mapping options.

Do you think that's enough?  We might try some tinkering to see if we can improve that.

**Comment by jchodera** [comment]
Is this guy good to go if you're up to 115/115 molecules now?

**Comment by pgrinaway** [comment]
Yeah, I think we can merge. Going beyond that will require additional, more complicated changes.

**Comment by pgrinaway** [comment]
Let's see what the current travis tests say about the last commit--should have fixed the sampler issue and topology proposal test issue.

**Comment by pgrinaway** [comment]
Miniconda MD5 mismatch...

**Comment by pgrinaway** [comment]
https://travis-ci.org/choderalab/perses/jobs/119378544#L178

**Comment by jchodera** [comment]
Switch the devtools/install.sh to use Miniconda2-latest instead of
Miniconda-latest

**Comment by pgrinaway** [comment]
ok

**Comment by pgrinaway** [comment]
Nice, the `ValenceSmallMoleculeLibraryTestSystem` actually passes now!

**Comment by pgrinaway** [comment]
Travis finally passes! Merging.

**Comment by jchodera** [comment]
Woohoo!

**Pull request merged**
