### PR TITLE
Implement extra angle terms to help ring closure

### PR DESCRIPTION
**Pull request by pgrinaway**
This PR implements extra angle terms to help ring closer. As a bonus, it also includes a promotion of the `always_change` option to constructor argument.

### CODE REVIEW

**Comment by pgrinaway** [comment]
Looks like I'll have to do some conflict resolution.

**Comment by jchodera** [comment]
Maybe @juliebehr can review after the conflicts are resolved, prior to merge?

**Comment by pgrinaway** [comment]
Conflicts merged. Sounds good.

**Comment by jchodera** [comment]
> @jchodera do you recognize this?

That may be an issue with pickling some object to store as a NetCDF string. I can fix that in a separate PR, though I'm surprised it didn't show up in the nosestests for the storage layer PR.

Create an issue and assign it to me?

**Comment by pgrinaway** [comment]
>That may be an issue with pickling some object to store as a NetCDF string. I can fix that in a separate PR, though I'm surprised it didn't show up in the nosestests for the storage layer PR.

Ok. I agree, it's weird that it didn't show up before.

**Comment by pgrinaway** [comment]
@juliebehr would you mind taking a quick pass over my additions? If it looks good to you, I'll merge this.

**Pull request merged**
