### PR TITLE
Implementing geometry engine

### PR DESCRIPTION
**Pull request by pgrinaway**
Beginning of initial implementation of direct switching between compounds/mutations. Currently getting together the `FFGeometryEngine` (so named because it uses forcefield data to propose geometries), followed by the proposal system for small molecules and then a script to run it.

### CODE REVIEW

**Comment by pgrinaway** [comment]
Currently brainstorming ways of efficiently traversing the molecular graph to decide the order of position assignment.

**Comment by jchodera** [comment]
The simplest approach here is to repeatedly go through the list of torsions and see if you can place atoms 1 or 4 in the 1-2-3-4 torsion list.  You can place atom 4 if positions for 4 are undefined, but you have positions for atoms 1, 2, and 3.  Similarly, you can place tom 1 if positions for 1 are undefined, and atoms 2, 3, and 4 have defined positions.  There are only O(N) torsions, so this scales well.

You can later make this more efficient by pruning the list of torsions used for this purpose if neither atoms 1 or 4 have undefined positions.

You can get the list of torsions from the OpenMM `System` object, `PeriodicTorsionForce` object.

**Comment by pgrinaway** [comment]
sounds good! Thanks!

**Comment by jchodera** [comment]
I forgot to mention that this will not work the same way for improper torsion since the bond and angle definitions will be between different atoms. you can probably just ignore impropers, but if you need to, there should be a way to create an equivalent atom placement scheme for impropers.

**Comment by jchodera** [comment]
Is this PR ready to be merged yet?

**Comment by pgrinaway** [comment]
I need to fix the computation of the determinant of the jacobian here.

**Comment by pgrinaway** [comment]
Ok, current status:
* I couldn't really get `sympy` to do what I want.
* I went back and looked at the code that uses autograd -- turns out I had made a mistake. I fixed that, and now autograd provides jacobians whose determinants are not 0. So, I think this is now working. I suppose the hairy question is now how to test it...

**Comment by jchodera** [comment]
> I suppose the hairy question is now how to test it...

There are a few tests that come to mind:
* Checking invariants.  For example, J(r,theta,phi) should be independent of phi for any (r,theta)
* Running a Monte Carlo simulation in (r,theta,phi) with a simple form of p(r,theta,phi) that should produce a uniform distribution in (x,y,z) within a sphere.  You might have to use something like p(r,theta,phi) \propto [r^2 sin(theta)] to get a uniform distribution.

Come to think of it, isn't the Jacobian determinant just `J(r,theta,phi) = r^2 sin(theta)`?

**Comment by pgrinaway** [comment]
Ok, I can do those tests. The first in particular is pretty easy.

>Come to think of it, isn't the Jacobian determinant just `J(r,theta,phi) = r^2 sin(theta)`?

So, the same as spherical coordinates? Hm, maybe.

**Comment by pgrinaway** [comment]
Empirically it seems to be the same (albeit with the opposite sign)

**Comment by jchodera** [comment]
> Empirically it seems to be the same (albeit with the opposite sign)

The Jacobian determinant should definitely be positive.  `r^2 sin(theta)` should also be positive in the allowed domain `theta \in [0,\pi]`.

**Comment by pgrinaway** [comment]
Well, the acceptance criterion uses the absolute value of dett(J), no? 

Point taken about the allowable domain of `theta`, though. I'll take a look.

**Comment by jchodera** [comment]
> Well, the acceptance criterion uses the absolute value of det(J), no?

Ah, good point!  So it doesn't matter.

**Comment by pgrinaway** [comment]
I think maybe it'd be good to get this merged and implement tests in the next PR? I've also got a couple other components about ready for PRs (proposal, biasing engine), so it might help to clean up.

**Comment by jchodera** [comment]
Sure, that works.

Travis is currently failing on some imports (`numexpr` and `oechem`).  That means we'll have to add these as dependencies, right?

**Comment by pgrinaway** [comment]
oh, let me add those before merging then!

**Comment by jchodera** [comment]
If you want to incorporate the `openeye` tools into testing, here is an example from [openmoltools](https://github.com/choderalab/openmoltools):
* license file encryption: [encryption](http://docs.travis-ci.com/user/encrypting-files/) [travis changes](https://github.com/choderalab/openmoltools/blob/master/.travis.yml#L24-L25) (note that this should probably be done within the actual `choderalab/perses` checkout with a direct push because of the possibility for accidentally encrypting for your local branch instead)
* Installation and testing: [travis block](https://github.com/choderalab/openmoltools/blob/master/.travis.yml#L37-L43)
* License file environment variable: [travis block](https://github.com/choderalab/openmoltools/blob/master/.travis.yml#L56-L58)

**Comment by pgrinaway** [comment]
Ok. I'll add that in after lunch and then merge when the tests pass.

**Comment by pgrinaway** [comment]
I think the license file is actually already installed, but cannot be decrypted in a pull request. Otherwise, the `openeye` toolkits now install on travis.

**Comment by jchodera** [comment]
Correct---the license can't be decrypted in a PR from your fork---only branches in this repo.  The only alternative is to skip those tests in PRs.

If it is ready to go, feel free to merge!

**Pull request merged**
