### PR TITLE
Fix water selection for counterion

### PR DESCRIPTION
**Pull request by zhang-ivy**
## Description

Currently, we choose a water at least X nm from protein to change into an ion. If there are glycan residues, the current implementation is incorrect, as a water may be chosen near a glycan, which we don't want. 

This PR changes the selection string from `protein` to `not water and not resn NA and not resn CL and not resn ZN`. The ions in the selection string may be supplied to the method as a list of strings.

## Motivation and context

Resolves #???

## Change log

```

```

### CODE REVIEW

**Review by mikemhenry — APPROVED** [review]
LGTM! Is there a test we could add that confirms the selection is what we want? Or maybe is there a test that if we had it, we would have caught this bug?

**Comment by zhang-ivy** [comment]
>Is there a test we could add that confirms the selection is what we want?

I don't think so. Any test I can think of would just involve running mdtraj again (but I think we should assume mdtraj is returning the correct indices).

> Or maybe is there a test that if we had it, we would have caught this bug?

I can't think of a test that would have caught this bug. This fix is necessary for systems with glycans, but most typical computational chemistry systems don't have glycans.

If anyone has any ideas for a test, feel free to push to this PR and I can review. Otherwise, this should be ready to merge.

**Comment by jchodera** [comment]
> This PR changes the selection string from protein to not water and not resn NA and not resn CL and not resn ZN. The ions in the selection string may be supplied to the method as a list of strings.

What if there are other ions in the system that are not NA, CL, or ZN?

MDTraj has a more robust way to exclude solvent in [`remove_solvent`](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/trajectory.py#L1826-L1861), but this is unfortunately not something that can be used as part of the DSL. Instead, this would require using part of the private API:
```python
from mdtraj.core.residue_names import _SOLVENT_TYPES
solvent_types = list(_SOLVENT_TYPES)
solute_indices = [atom.index for atom in mdtraj_topology.atoms if atom.residue.name not in solvent_types]
```
I suggest we use this scheme and note a `TODO` in the code to replace it once we're able to either (1) get `solvent` as a keyword into the [MDTraj DSL](https://mdtraj.org/1.6.2/atom_selection.html), or (2) transition to MDAnalysis (which is probably a good idea given that the OpenFE devs are also MDAnalysis devs).

**Comment by zhang-ivy** [comment]
>What if there are other ions in the system that are not NA, CL, or ZN?

I've made the `ion_names` an optional argument, so alternative ion names can be specified, but your suggestion is better, so I'll fix that now.

**Comment by mikemhenry** [comment]
@zhang-ivy is this ready to merge?

**Comment by zhang-ivy** [comment]
Yes, as long as others have reviewed it.

**Review by ijpulidos — APPROVED** [review]
LGTM! Agree with the comments/TODO.

**Pull request merged**
