### PR TITLE
[DO NOT MERGE] Fix protein mutations and add stereochemistry

### PR DESCRIPTION
**Pull request by zhang-ivy**
Major changes to `PointMutationEngine`:

- `_choose_mutant`, `choose_mutation_from_allowed`, `_propose_mutation` - Only one residue may be mutated at a time. To mutate multiple residues, specify `aggregate = True` when initializing `PointMutationEngine`

Major changes to `PolymerProposalEngine`:
- `_identify_differences` - New function. Identifies excess atoms and bonds and missing atoms and bonds between the old and new topology.
- `_delete_atoms` - Based off `OpenMM` `modeller`'s `delete` function, modified so that each atom in the returned topology has a property containing its old index.
- `_add_new_atoms` - Based off `OpenMM` `modeller`'s `add` function, modified so that each atom in the returned topology has a property containing its old index and each residue has a property containing a boolean indicating whether it was modified.
- `_construct_atom_map` and `get_mol_atom_matches` - Atom map wasn't implemented properly before. Also added all atoms in cap residues to the atom map (including hydrogens).

How stereochemistry was added:
Create a custom stereochemistry force in `GeometrySystemGenerator`'s constructor and add torsions to it in `_determine_extra_torsions` by setting the stereochemistry to either its naturally occuring stereochemistry (if it's an amino acid) or perceive it from the state key's oemol (if it's a small molecule).

### CODE REVIEW

**Comment by jchodera** [comment]
@pgrinaway @hannahbrucemacdonald : Oh dear---this has a lot of changes to the alchemical factory, but was never merged. Any idea how these should be reconciled with the current `master` or #504?

I'm tempted to just merge this too and sort out the issues in #504.

**Comment by pgrinaway** [comment]
@jchodera These changes to the alchemical factory are OK to merge. They remove a bug that was removed in another PR, but presumably integrated here from that branch before it was merged.

**Comment by jchodera** [comment]
@pgrinaway: Just wanted to double check this was really ready to merge!

**Comment by jchodera** [comment]
I've taken most of the `PolymerProposalEngine` and subclass improvements from this PR and merged them in with #513. I'll tackle the stereochemistry restraints in another pass after merging in #517

**Pull request closed without merging**
