### PR TITLE
Started work on test of alkanes with only valence energy terms

### PR DESCRIPTION
**Pull request by jchodera**
This test will check that we get appropriate statistics (equal sampling) of molecules with only valence terms.

### CODE REVIEW

**Comment by jchodera** [comment]
Fixed a minor bug in `determine_proposal_order` where, if no atoms needed to be proposed, `logp_choice` would be undefined.

**Comment by jchodera** [comment]
Addressed #137

**Comment by jchodera** [comment]
I've implemented a work-around for https://github.com/choderalab/perses/issues/137#issuecomment-185511489 that randomizes the positions of the atoms that have not yet been placed.

**Comment by jchodera** [comment]
We're no longer in `nan`dyland, but I'm still concerned about the vastly unfavorable geometry engine `logp` values.

**Comment by jchodera** [comment]
Implemented the more robust fix suggested in https://github.com/pandegroup/openmm/issues/1397

**Comment by jchodera** [comment]
Done for now.  There were lots of fixes, but some issues in #137 still need to be addressed (most notably the weird issues with `logp_reverse`).

This can be merged for now!

**Comment by pgrinaway** [comment]
Are we still good to merge this?

**Comment by jchodera** [comment]
Yes!

**Pull request merged**
