### PR TITLE
Add GeometryEngine as constructor argument to ExpandedEnsembleSampler

### PR DESCRIPTION
**Pull request by pgrinaway**
Added the `geometry_engine` constructor argument, and put in the `FFAllAngleGeometryEngine` as the default for all perses test systems.

### CODE REVIEW

**Comment by jchodera** [comment]
Looks good!

**Comment by pgrinaway** [comment]
Thanks! Might have missed something, checking the travis and updating.

**Comment by pgrinaway** [comment]
Ok, this one looks good. Fixed the "molecule not in list" error with the `ValenceSmallMoleculeTestSystem`

**Comment by jchodera** [comment]
Thanks!

**Pull request merged**
