### PR TITLE
Feat/fix ssl gpu error

### PR DESCRIPTION
**Pull request by mikemhenry**
## Motivation and context

Resolves #???

## Change log

```

```

### CODE REVIEW

**Comment by mikemhenry** [comment]
before merging this we will need to change the yaml to run only on merge and not on every commit to the PR

**Comment by mikemhenry** [comment]
Updating the image didn't fix it, but I will keep that as-is since it shouldn't hurt things.

**Comment by mikemhenry** [comment]
@ijpulidos this is ready for review! I removed the bit where I run the GPU tests on commits to this PR, but you can see that in the previous run we have a green check and that includes the GPU tests

**Review by ijpulidos — APPROVED** [review]
This looks good to me, LGTM!

**Pull request merged**
