### PR TITLE
updating to a working selectivity script

### PR DESCRIPTION
**Pull request by steven-albanese**
Fixed an API issue and also added in netCDF storage. This is ready to merge once someone looks at it!

### CODE REVIEW

**Comment by jchodera** [comment]
I wonder if closely related inhibitors may still work, whoever. For example, we might see if someone has tested a series of fluorinated variants of the same inhibitor.

**Comment by steven-albanese** [comment]
@jchodera: do you have any insight into how to set the netCDF storage up? Based on other test systems, it looks like a different `NetCDFStorageView` gets instantiated for every environment and passed to `SmallMoleculeSetProposalEngine`. Is that necessary? Or is it sufficient to just pass a `storage_filename` to the test system like this: `system = Selectivity(storage_filename=storage_filename)`

**Comment by steven-albanese** [comment]
Actually just talked to @pgrinaway and he was able to answer my question

**Comment by jchodera** [comment]
Great! All the examples in testsystems.py should be useful examples of how
to set up the storage interface.

**Pull request merged**
