### PR TITLE
Added NCMC tests

### PR DESCRIPTION
**Pull request by jchodera**
I have a simpler function `test_ncmc_alchemical_integrator` that fails on OpenCL but not CPU/Reference.

Working on isolating the issue to create a minimal test system.

### CODE REVIEW

**Comment by jchodera** [comment]
I think I've nailed it down. Some numerical differences on OpenCL and CUDA may have allowed the alchemical `lambda` to be a little bit smaller than 0 or a little bit bigger than 1.

**Comment by jchodera** [comment]
I seem to have eliminated the `NaN`s, but this still passes on `Reference` and `CPU` but fails on `OpenCL` on my iMac.  The NCMC statistics end up all wonky.  There must be some issue either with the integrator or with the force/energy computations.

**Comment by jchodera** [comment]
Nothing concrete yet, but the alchemical system seems to show much larger discrepancies between `OpenCL` and `Reference` than `CPU` and `Reference`.

These numbers are `energy` `energy-error` `force` `force-error`:
```
ITERATION        3 /       10 : LAMBDA =     0.600000
               Reference  -140.103626     0.000000 kcal/mol   295.335429     0.000000 kcal/mol/A
                     CPU  -140.103627    -0.000001 kcal/mol   295.335429     0.000008 kcal/mol/A
                  OpenCL  -140.103623     0.000003 kcal/mol   295.335442     0.000610 kcal/mol/A
ITERATION        4 /       10 : LAMBDA =     0.500000
               Reference  -132.604552     0.000000 kcal/mol   277.660887     0.000000 kcal/mol/A
                     CPU  -132.604545     0.000007 kcal/mol   277.660887     0.000006 kcal/mol/A
                  OpenCL  -132.604539     0.000013 kcal/mol   277.660876     0.000607 kcal/mol/A
ITERATION        5 /       10 : LAMBDA =     0.400000
               Reference  -119.141534     0.000000 kcal/mol   327.273469     0.000000 kcal/mol/A
                     CPU  -119.141530     0.000003 kcal/mol   327.273469     0.000005 kcal/mol/A
                  OpenCL  -119.141494     0.000040 kcal/mol   327.273548     0.000576 kcal/mol/A
ITERATION        6 /       10 : LAMBDA =     0.300000
               Reference  -110.397698     0.000000 kcal/mol   348.506470     0.000000 kcal/mol/A
                     CPU  -110.397696     0.000001 kcal/mol   348.506470     0.000008 kcal/mol/A
                  OpenCL  -110.397661     0.000036 kcal/mol   348.506603     0.000662 kcal/mol/A
ITERATION        7 /       10 : LAMBDA =     0.200000
               Reference  -105.139037     0.000000 kcal/mol   372.319316     0.000000 kcal/mol/A
                     CPU  -105.139032     0.000005 kcal/mol   372.319316     0.000007 kcal/mol/A
                  OpenCL  -105.139024     0.000013 kcal/mol   372.319318     0.000646 kcal/mol/A
ITERATION        8 /       10 : LAMBDA =     0.100000
               Reference   -90.745726     0.000000 kcal/mol   336.364424     0.000000 kcal/mol/A
                     CPU   -90.745721     0.000005 kcal/mol   336.364424     0.000007 kcal/mol/A
                  OpenCL   -90.745702     0.000024 kcal/mol   336.364555     0.000615 kcal/mol/A
ITERATION        9 /       10 : LAMBDA =     0.000000
               Reference   -97.286929     0.000000 kcal/mol   336.503867     0.000000 kcal/mol/A
                     CPU   -97.286924     0.000006 kcal/mol   336.503867     0.000008 kcal/mol/A
                  OpenCL   -97.286927     0.000002 kcal/mol   336.503906     0.000639 kcal/mol/A
```

**Comment by jchodera** [comment]
Here is a comparison of final work values and positions after one NCMC step (which is actually VV + switch + VV):
```
Compare NCMC integrator behavior across platforms. ... 
ITERATION     0 : Starting from identical positions and velocities...
   Reference :       0.00167700 : [   1.332  -1.041   0.229] [   1.628   0.476   0.249] [   2.121  -1.556   0.844] [   0.342  -1.335   0.687] [   1.431  -1.525  -0.732] [   0.941   1.034  -0.343] [   2.699   0.535  -0.031] [   1.525   0.892   1.216]
         CPU :       0.00167700 : [   1.332  -1.041   0.229] [   1.628   0.476   0.249] [   2.121  -1.556   0.844] [   0.342  -1.335   0.687] [   1.431  -1.525  -0.732] [   0.941   1.034  -0.343] [   2.699   0.535  -0.031] [   1.525   0.892   1.216]
      OpenCL :       0.29467438 : [   1.332  -1.041   0.229] [   1.628   0.476   0.249] [   2.121  -1.556   0.844] [   0.342  -1.335   0.687] [   1.431  -1.525  -0.732] [   0.941   1.034  -0.343] [   2.699   0.535  -0.031] [   1.525   0.892   1.216]
ITERATION     1 : Starting from identical positions and velocities...
   Reference :       0.02653421 : [   1.003  -0.433   0.849] [   1.991  -0.151  -0.338] [   1.453  -0.506   1.853] [   0.244   0.410   0.873] [   0.407  -1.380   0.572] [   1.269  -0.019  -1.137] [   2.546  -1.028  -0.560] [   2.602   0.752  -0.333]
         CPU :       0.02653421 : [   1.003  -0.433   0.849] [   1.991  -0.151  -0.338] [   1.453  -0.506   1.853] [   0.244   0.410   0.873] [   0.407  -1.380   0.572] [   1.269  -0.019  -1.137] [   2.546  -1.028  -0.560] [   2.602   0.752  -0.333]
      OpenCL :      -1.59434827 : [   1.003  -0.433   0.849] [   1.991  -0.151  -0.338] [   1.453  -0.506   1.853] [   0.244   0.410   0.873] [   0.407  -1.380   0.572] [   1.269  -0.019  -1.137] [   2.546  -1.028  -0.560] [   2.602   0.752  -0.333]
ITERATION     2 : Starting from identical positions and velocities...
   Reference :       0.04454022 : [   0.835   0.124   0.376] [   2.130  -0.685   0.106] [   0.477  -0.343   1.336] [   1.066   1.137   0.715] [   0.115   0.042  -0.373] [   2.592  -0.450  -0.848] [   1.827  -1.784   0.046] [   2.872  -0.569   0.907]
         CPU :       0.04454022 : [   0.835   0.124   0.376] [   2.130  -0.685   0.106] [   0.477  -0.343   1.336] [   1.066   1.137   0.715] [   0.115   0.042  -0.373] [   2.592  -0.450  -0.848] [   1.827  -1.784   0.046] [   2.872  -0.569   0.907]
      OpenCL :      -0.64726897 : [   0.835   0.124   0.376] [   2.130  -0.685   0.106] [   0.477  -0.343   1.336] [   1.066   1.137   0.715] [   0.115   0.042  -0.373] [   2.592  -0.450  -0.848] [   1.827  -1.784   0.046] [   2.872  -0.569   0.907]
ITERATION     3 : Starting from identical positions and velocities...
   Reference :      -0.01393091 : [   1.023   0.285   0.393] [   1.944  -0.845   0.085] [   0.200   0.005   1.123] [   1.597   1.195   0.639] [   0.435   0.495  -0.444] [   2.644  -0.518  -0.565] [   1.259  -1.651  -0.321] [   2.412  -1.230   1.008]
         CPU :      -0.01393091 : [   1.023   0.285   0.393] [   1.944  -0.845   0.085] [   0.200   0.005   1.123] [   1.597   1.195   0.639] [   0.435   0.495  -0.444] [   2.644  -0.518  -0.565] [   1.259  -1.651  -0.321] [   2.412  -1.230   1.008]
      OpenCL :      -0.95657440 : [   1.023   0.285   0.393] [   1.944  -0.845   0.085] [   0.200   0.005   1.123] [   1.597   1.195   0.639] [   0.435   0.495  -0.444] [   2.644  -0.518  -0.565] [   1.259  -1.651  -0.321] [   2.412  -1.230   1.008]
```
I realize that `CPU` might just be using the `Reference` implementation for most of the forces here, since it only implements some of the forces.

**Comment by jchodera** [comment]
This is also wonky on the cluster:
```
Compare NCMC integrator behavior across platforms. ... 
ITERATION     0 : Starting from identical positions and velocities...
   Reference :      -0.02225395 : [   1.445  -0.031   1.013] [   1.529  -0.561  -0.529] [   2.409   0.454   1.187] [   0.589   0.614   1.005] [   1.247  -0.796   1.797] [   0.673  -1.272  -0.717] [   2.445  -1.219  -0.597] [   1.652   0.326  -1.185]
         CPU :      -0.02225395 : [   1.445  -0.031   1.013] [   1.529  -0.561  -0.529] [   2.409   0.454   1.187] [   0.589   0.614   1.005] [   1.247  -0.796   1.797] [   0.673  -1.272  -0.717] [   2.445  -1.219  -0.597] [   1.652   0.326  -1.185]
        CUDA :      -2.59599783 : [   1.445  -0.031   1.013] [   1.529  -0.561  -0.529] [   2.409   0.454   1.187] [   0.589   0.614   1.005] [   1.247  -0.796   1.797] [   0.673  -1.272  -0.717] [   2.445  -1.219  -0.597] [   1.652   0.326  -1.185]
      OpenCL :      -2.59599783 : [   1.445  -0.031   1.013] [   1.529  -0.561  -0.529] [   2.409   0.454   1.187] [   0.589   0.614   1.005] [   1.247  -0.796   1.797] [   0.673  -1.272  -0.717] [   2.445  -1.219  -0.597] [   1.652   0.326  -1.185]
ITERATION     1 : Starting from identical positions and velocities...
   Reference :       0.03275646 : [   1.912  -0.036  -0.362] [   1.070  -0.564   0.850] [   1.723  -0.585  -1.244] [   1.688   1.018  -0.437] [   2.963  -0.141  -0.078] [   0.935   0.227   1.501] [   1.625  -1.365   1.424] [   0.115  -0.891   0.444]
         CPU :       0.03275646 : [   1.912  -0.036  -0.362] [   1.070  -0.564   0.850] [   1.723  -0.585  -1.244] [   1.688   1.018  -0.437] [   2.963  -0.141  -0.078] [   0.935   0.227   1.501] [   1.625  -1.365   1.424] [   0.115  -0.891   0.444]
        CUDA :       3.12496792 : [   1.912  -0.036  -0.362] [   1.070  -0.564   0.850] [   1.723  -0.585  -1.244] [   1.688   1.018  -0.437] [   2.963  -0.141  -0.078] [   0.935   0.227   1.501] [   1.625  -1.365   1.424] [   0.115  -0.891   0.444]
      OpenCL :       3.12497411 : [   1.912  -0.036  -0.362] [   1.070  -0.564   0.850] [   1.723  -0.585  -1.244] [   1.688   1.018  -0.437] [   2.963  -0.141  -0.078] [   0.935   0.227   1.501] [   1.625  -1.365   1.424] [   0.115  -0.891   0.444]
ITERATION     2 : Starting from identical positions and velocities...
   Reference :      -0.00169381 : [   1.121   0.358   0.299] [   1.859  -0.979   0.219] [   1.790   1.114   0.717] [   0.874   0.711  -0.715] [   0.215   0.242   0.798] [   1.185  -1.794  -0.002] [   2.383  -1.170   1.154] [   2.643  -0.800  -0.553]
         CPU :      -0.00169381 : [   1.121   0.358   0.299] [   1.859  -0.979   0.219] [   1.790   1.114   0.717] [   0.874   0.711  -0.715] [   0.215   0.242   0.798] [   1.185  -1.794  -0.002] [   2.383  -1.170   1.154] [   2.643  -0.800  -0.553]
        CUDA :      -0.74814347 : [   1.121   0.358   0.299] [   1.859  -0.979   0.219] [   1.790   1.114   0.717] [   0.874   0.711  -0.715] [   0.215   0.242   0.798] [   1.185  -1.794  -0.002] [   2.383  -1.170   1.154] [   2.643  -0.800  -0.553]
      OpenCL :      -0.74815054 : [   1.121   0.358   0.299] [   1.859  -0.979   0.219] [   1.790   1.114   0.717] [   0.874   0.711  -0.715] [   0.215   0.242   0.798] [   1.185  -1.794  -0.002] [   2.383  -1.170   1.154] [   2.643  -0.800  -0.553]
ITERATION     3 : Starting from identical positions and velocities...
   Reference :       0.02669112 : [   1.750  -1.016   0.419] [   1.238   0.429   0.102] [   1.260  -1.475   1.217] [   1.685  -1.574  -0.440] [   2.848  -0.954   0.589] [   1.891   0.934  -0.633] [   1.182   1.092   0.956] [   0.185   0.333  -0.308]
         CPU :       0.02669112 : [   1.750  -1.016   0.419] [   1.238   0.429   0.102] [   1.260  -1.475   1.217] [   1.685  -1.574  -0.440] [   2.848  -0.954   0.589] [   1.891   0.934  -0.633] [   1.182   1.092   0.956] [   0.185   0.333  -0.308]
        CUDA :      -0.43181935 : [   1.750  -1.016   0.419] [   1.238   0.429   0.102] [   1.260  -1.475   1.217] [   1.685  -1.574  -0.440] [   2.848  -0.954   0.589] [   1.891   0.934  -0.633] [   1.182   1.092   0.956] [   0.185   0.333  -0.308]
      OpenCL :      -0.43181161 : [   1.750  -1.016   0.419] [   1.238   0.429   0.102] [   1.260  -1.475   1.217] [   1.685  -1.574  -0.440] [   2.848  -0.954   0.589] [   1.891   0.934  -0.633] [   1.182   1.092   0.956] [   0.185   0.333  -0.308]
```
I can't tell if this is just extreme numerical instability or if there is something very odd going on in terms of behavior differences.

**Comment by jchodera** [comment]
`CustomIntegrators` can control global force parameters in both CUDA/OpenCL and Reference/CPU, right?

**Comment by jchodera** [comment]
As far as I can tell, the issue is that 
```python
self.addComputeSum("kinetic", expression)
```
stores `0` in `kinetic` regardless of whatever `expression` is.

**Comment by pgrinaway** [comment]
Thanks! this is really helpful! Can we merge this PR after I merge the other one?

**Comment by jchodera** [comment]
Don't merge this one! Was just a test.

**Comment by pgrinaway** [comment]
Ok. Should I leave it open for now or should I close it?

**Comment by jchodera** [comment]
Leave open for now?

**Comment by pgrinaway** [comment]
Ok, sounds good.

**Comment by jchodera** [comment]
OpenMM is fixed now! https://github.com/pandegroup/openmm/pull/1384

**Comment by jchodera** [comment]
OK, I've cleaned this up, merged upstream changes, and added a test for sidechain mutation NCMC. Ready to merge when tests pass.

**Comment by pgrinaway** [comment]
Great! Will merge when the tests pass!

**Pull request merged**
