### PR TITLE
Explicitly declare new global parameter for NonbondedForce

### PR DESCRIPTION
**Pull request by jchodera**
This incorporates changes to use the new API https://github.com/pandegroup/openmm/pull/2119

### CODE REVIEW

**Comment by jchodera** [comment]
Fixes #476 

I've verified this works for me with `7.3.0.dev-38ae256`

**Comment by pgrinaway** [comment]
I think the travis build had some weirdness, so I restarted them.

**Comment by jchodera** [comment]
The travis weirdness could be real conda issues. I can debug tomorrow.

**Comment by jchodera** [comment]
Travis tests are running again, but now there's a [segmentation fault](https://travis-ci.org/choderalab/perses/jobs/403971992#L1723) triggered by the test:
```
Test that the variance of the endpoint->nonalchemical perturbation is sufficiently small for pentane->butane in vacuum ... Writing omega-00000.mol2
handling exceptions
done handling exceptions
/home/travis/.travis/job_stages: line 78:  7809 Segmentation fault      (core dumped) nosetests perses --nocapture --verbosity=3 --with-timer -a '!advanced'
```
The [other test](https://travis-ci.org/choderalab/perses/jobs/403971993#L1696-L1698) also gives a core dump with a slightly different message:
```
Test that the variance of the endpoint->nonalchemical perturbation is sufficiently small for pentane->butane in vacuum ... Writing omega-00000.mol2
handling exceptions
done handling exceptions
*** Error in `/home/travis/miniconda/envs/test/bin/python': corrupted size vs. prev_size: 0x000000000985b3c0 ***
/home/travis/.travis/job_stages: line 78:  7774 Aborted                 (core dumped) nosetests perses --nocapture --verbosity=3 --with-timer -a '!advanced'
```
This is starting to sound like a real bug, though I'm not quite sure whether it is the CPU platform a CPU version of the OpenCL platform that is the culprit.

@pgrinaway : Is there a way to (1) have that test print the platform its using, and (2) serialize the system, integrator, and state for this test and submit it to the OpenMM issue tracker as a bug report?

**Comment by jchodera** [comment]
@pgrinaway Just a reminder about this.

**Pull request merged**
