### PR TITLE
Some tests for GeometryEngine and minor cleanup

### PR DESCRIPTION
**Pull request by pgrinaway**
This PR adds a number of tests for `FFAllAngleGeometryEngine`, along with docstrings and comments (and improved formatting) so they are hopefully easier to read and understand. I've also deleted some unused or broken classes. 

For the stochastic tests, I've implemented what @jchodera had suggested before:

`pval_threshold = pval_base / (ntests * ncommits)` 

where there are 3 stochastic tests, and 10000 commits in the life of the project. I used 0.01 as the base for the p value.

### CODE REVIEW

**Comment by jchodera** [comment]
Looks much better!

**Comment by jchodera** [comment]
Looks like the tests may have caught some actual issues!
```
======================================================================
ERROR: Test the proposal of angles by GeometryEngine by comparing to proposals from a normal distribution
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/perses/tests/test_geometry_engine.py", line 251, in test_propose_angle
    raise Exception("The angle may be drawn from the wrong distribution. p= %f" % pval)
Exception: The angle may be drawn from the wrong distribution. p= 0.040234
======================================================================
ERROR: Test the proposal of bonds by GeometryEngine by comparing to proposals from a normal distribution
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/perses/tests/test_geometry_engine.py", line 287, in test_propose_bond
    raise Exception("The bond may be drawn from the wrong distribution. p= %f" % pval)
Exception: The bond may be drawn from the wrong distribution. p= 0.308467
======================================================================
ERROR: Test, using the kolmogorov-smirnov test, that the torsion angles drawn via the geometry engine match the expected
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/perses/tests/test_geometry_engine.py", line 655, in test_propose_torsion
    raise Exception("Torsion may not have been drawn from the correct distribution.")
Exception: Torsion may not have been drawn from the correct distribution.
```

**Comment by pgrinaway** [comment]
Oh, wow, that was a very stupid mistake on my part. Fixing now.

**Comment by pgrinaway** [comment]
Ok, this PR is ready for review. Tests pass.

**Pull request merged**
