### PR TITLE
[WIP] Ring map - checking _size_ of ring occupancy

### PR DESCRIPTION
**Pull request by hannahbrucemacdonald**
There is an issue with some Bace ligands, where because we are only checking if atoms are in rings or not, that we end up mapping atoms in rings of different sizes e.g.:

image

### CODE REVIEW

**Comment by hannahbrucemacdonald** [comment]
@dominicrufa can you review please?

**Comment by jchodera** [comment]
@hannahbrucemacdonald : I've retriggered the tests for you! 

I see a bunch of tests failing with:
```
perses.tests.test_topology_proposal.test_mapping_strength_levels ... sh: 0: getcwd() failed: No such file or directory
Cannot open file (ATOMTYPE.INF) with mode (w).
```
This is likely occurring because a temporary directory is being created and then deleted before some part of the antechamber process could be completed. I'm trying to figure out where this is happening, but I'm not sure how much time we want to invest in trying to make something we know is fundamentally flawed run, since it will still produce fundamentally flawed results.

**Comment by jchodera** [comment]
Hm, this test runs locally. I think this might be an issue with another test that changes the current working directory, which might mess up subsequent tests if a test fails before completion.

**Comment by jchodera** [comment]
I've fixed the tests that change the working directory, but haven't extensively looked for other methods that may also manipulate the working directory.

I also fixed some very broken logic where `atom_expr` and `bond_expr` were being used by `app/setup_relative_calculation.py:run_setup()`, but were not ever defined in that method. 

Hopefully this will get rid of the failures arising from `getcwd() failed: No such file or directory` and let you debug the rest!

**Comment by jchodera** [comment]
Ah! We had been pinning `ambertools==19.0` in `devtools/conda-recipe`. I've fixed that, and also tried to suppress some other conda install noise.

**Comment by jchodera** [comment]
I'm seeing many fewer failures now!

I'm not sure if we can suppress the `antechamber/bondtype` warnings about unknown bond types, but it would vastly clean up the test output if we could.

**Comment by jchodera** [comment]
Yay! Looks like there are 9 failures now, and they're all relevant failures:
https://travis-ci.org/choderalab/perses/jobs/649939655?utm_medium=notification&utm_source=github_status

Passing this back to @hannahbrucemacdonald

**Comment by hannahbrucemacdonald** [comment]
> Ah! We had been pinning ambertools==19.0 in devtools/conda-recipe. I've fixed that, and also tried to suppress some other conda install noise.


Sorry I pinned it a few days ago in an act of desperation to try fix the antechamber issues, I should have unpinned

**Comment by hannahbrucemacdonald** [comment]
>I also fixed some very broken logic where atom_expr and bond_expr were being used by app/setup_relative_calculation.py:run_setup(), but were not ever defined in that method.

Sorry my bad - I was rushing to commit stuff last night, but thanks for fixing. Hopefully this should all be a bit better in the `Experiments` pr

**Comment by jchodera** [comment]
@hannahbrucemacdonald : I've updated `openmoltools` to get rid of those bond warnings, so I'll rerun the tests and (hope) we can actually see the real errors now.

**Comment by jchodera** [comment]
This test output is much more comprehensible!

I hadn't seen this warning before:
> Warning: maximum number of matches limit (1024) is reached

We should also really try to get the mutations PR in before we move further with the experiments PR.

**Comment by hannahbrucemacdonald** [comment]
I think that warning is from openeye, when we are doing the matching criteria, sometimes if two molecules have a lot of ways to map, we see this. I'm doing my best to get this passing, but there are still a few broken tests that I'm worried about. Doing my best to get them squashed this week.

**Comment by hannahbrucemacdonald** [comment]
perses.tests.test_samplers.test_hybrid_scheme
> this is failing because of a variable called `chain_id` which I think I can fix
perses.tests.test_relative.test_compare_energies
> this is broken because we've added the checking for ring memership for mapping. I need to add a atom mapping criteria to the test that lets us map napthalene to benzene
test_topology_proposal.test_mapping_strength_levels
> same as before, where I've changed what the mapping behavior is, what we consider the 'right' mapping has changed, and I need to update the tests accordingly

**Comment by jchodera** [comment]
@hannahbrucemacdonald  :Can you open an issue (and assign it to me) to fix that failing protein mutation test you commented out? I can come back to it later!

**Comment by hannahbrucemacdonald** [comment]
We have some passes and some fails... not completely sure what the difference between all the different CI environments are but I'll try fix it today, once and for all

**Comment by hannahbrucemacdonald** [comment]
Closes #603

**Pull request merged**
