### PR TITLE
Release 0.9.5

### PR DESCRIPTION
**Pull request by mikemhenry**
Quick release to get our citations in order, see https://github.com/choderalab/perses/pull/948

### CODE REVIEW

**Comment by mikemhenry** [comment]
@jchodera if you could take a look at this when you get a chance that would be great! Also would it be okay for me to merge the release on conda-forge as well? Thanks!

**Comment by jchodera** [comment]
Shoot, sorry for not catching this earlier:
1. Can we update `CITATION.cff` to include middle initials in "given names", e.g. "John" -> "John D." to reflect current publication practice?
2. Any idea why builds are failing?

**Comment by jchodera** [comment]
It looks like at least some of these failures are due to the change in how diameter is computed for solvating systems: https://github.com/openmm/openmm/pull/3480
```
_____________________________ test_position_output _____________________________
[gw1] linux -- Python 3.8.12 /usr/share/miniconda/envs/test/bin/python

    def test_position_output():
        """
        Test that the hybrid returns the correct positions for the new and old systems after construction
        """
        from perses.annihilation.relative import HybridTopologyFactory
        import numpy as np
    
        # Generate topology proposal
>       topology_proposal, old_positions, new_positions = utils.generate_solvated_hybrid_test_topology()

perses/tests/test_relative.py:489: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
perses/tests/utils.py:533: in generate_solvated_hybrid_test_topology
    new_positions, _ = geometry_engine.propose(top_proposal, solvated_positions, beta)
perses/rjmc/geometry.py:237: in propose
    logp_proposal, new_positions, rjmc_info, atoms_with_positions_reduced_potential, final_context_reduced_potential, neglected_angle_terms, omitted_terms = self._logp_propose(top_proposal, current_positions, beta, direction='forward', validate_energy_bookkeeping = validate_energy_bookkeeping)
perses/rjmc/geometry.py:641: in _logp_propose
    final_context = openmm.Context(final_system, final_system_integrator, platform)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <openmm.openmm.Context;  >
args = (<openmm.openmm.System; proxy of <Swig Object of type 'OpenMM::System *' at 0x7f58aa7020f0> >, <openmm.openmm.VerletIn...at 0x7f58a8c4bc00> >, <openmm.openmm.Platform; proxy of <Swig Object of type 'OpenMM::Platform *' at 0x7f58a8a90870> >)

    def __init__(self, *args):
        r"""
        __init__(self, system, integrator) -> Context
        __init__(self, system, integrator, platform) -> Context
        __init__(self, system, integrator, platform, properties) -> Context
        __init__(self, other) -> Context
        Construct a new Context in which to run a simulation, explicitly specifying what Platform should be used to perform calculations and the values of platform-specific properties.
    
        Parameters
        ----------
        system : System
            the System which will be simulated
        integrator : Integrator
            the Integrator which will be used to simulate the System
        platform : Platform
            the Platform to use for calculations
        properties : map< std::string, std::string >
            a set of values for platform-specific properties. Keys are the property names.
        """
>       _openmm.Context_swiginit(self, _openmm.new_Context(*args))
E       openmm.OpenMMException: NonbondedForce: The cutoff distance cannot be greater than half the periodic box size.

/usr/share/miniconda/envs/test/lib/python3.8/site-packages/openmm/openmm.py:7[257](https://github.com/choderalab/perses/runs/5400530956?check_suite_focus=true#step:9:257): OpenMMException
```

**Comment by jchodera** [comment]
Let's address the failing nightlies by increasing the buffer size for the
tests that are failing.

We should also open an issue to change defaults and
recommendations/examples as well as box shape in advance of the next OpenMM
release.

Once we add middle initials to the citations to match what folks generally
publish under, this is then ready to go!

**Comment by zhang-ivy** [comment]
#952  adds the middle initials to the citation file!

**Comment by mikemhenry** [comment]
@jchodera Just to be clear we want to

- [ ]  fix failing tests by increasing the buffer size
- [ ]  add middle initials (https://github.com/choderalab/perses/pull/952)

Then do the release?

**Comment by jchodera** [comment]
> @jchodera Just to be clear we want to

Correct!

**Pull request merged**
