### PR TITLE
Canonicalize input smiles

### PR DESCRIPTION
**Pull request by pgrinaway**
Makes sure that the input smiles strings are canonical isomeric smiles in the openeye flavor by taking the input library and converting each to an `OEMol` then to canonical isomeric SMILES.

### CODE REVIEW

**Comment by jchodera** [comment]
Canonicalicious.

**Comment by jchodera** [comment]
We might also want to do some other cleanup here, like then taking the unique set of SMILES, e.g.
```python
molecules = list(set(molecules))
```

**Comment by pgrinaway** [comment]
oh ok i can add that in now.

**Comment by pgrinaway** [comment]
At least one of those builds seemed to have passed everything to a point and [then stalled](https://travis-ci.org/choderalab/perses/builds/109448524#L886).

**Comment by pgrinaway** [comment]
Also timed out...hm...

**Comment by jchodera** [comment]
I'm confused by that too.  It's possible my [parallelization of nosetests](https://github.com/choderalab/perses/blob/master/.travis.yml#L39) is to blame.  Want to disable that?

**Comment by pgrinaway** [comment]
Looks like you're only using 1 process though?

**Comment by pgrinaway** [comment]
Or were you suggesting to increase that number?

**Comment by pgrinaway** [comment]
Oh, nevermind, that says -1. I missed the negative sign.

**Comment by jchodera** [comment]
This is looking much better.

I bet we can parallelize the tests with a travis build matrix, testing each component in a separate branch of the matrix.  I can try that is a separate PR.

**Comment by pgrinaway** [comment]
Yeah, I think we've passed the earlier issue. It seems like some of the tests were just not writing output in the parallel scheme, causing travis to end the build?

**Comment by pgrinaway** [comment]
Ok, I'm going to try to figure out what is going wrong here.

**Comment by jchodera** [comment]
I imagine there are simply issues with the SMILES strings I downloaded from the Shoichet lab website.  The files are here: https://github.com/choderalab/perses/tree/master/perses/data

**Comment by jchodera** [comment]
If you run `nosetests -vv perses/tests/test_samplers.py` locally, you can trigger the failing tests right away.

**Comment by pgrinaway** [comment]
Ok, well, this might be an opportune moment to fix the Python 3 failures as well.

**Comment by pgrinaway** [comment]
Looks like it's running into the issue mentioned in #114 . Also, a minor issue regarding reading the SMILES csvs: I needed to read with `r` instead of `rb`.

**Comment by jchodera** [comment]
Shoot.  This is still timing out:
```
Testing expanded ensemble sampler with AlkanesTestSystem 'explicit' ... 
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```
It must be that there simply isn't enough output printed when the samplers are not failing.

Let's go ahead and merge and I can add some sampler output and reduce the number of steps per iteration.

**Comment by pgrinaway** [comment]
Ok. Merging this. I will look more into the molecule construction failures.

**Pull request merged**
