### PR TITLE
Don't alchemically soften angles until we can figure out why this is broken

### PR DESCRIPTION
**Pull request by jchodera**
cc: #203 and #202 

I'm temporarily reverting the change that set `alchemical_angles = True` since this doesn't seem to be working as expected. I will debug this in https://github.com/choderalab/alchemy now, but this change can be reviewed and merged.

We should never allow `lambda_bonds` or `lambda_angles` to be zero, so I have also changed the `default_functions` to only let this drop to 0.1.

### CODE REVIEW

**Comment by jchodera** [comment]
@pgrinaway: Any idea what is going on with [this failure](https://travis-ci.org/choderalab/perses/jobs/132995616#L813-L846)?
```
======================================================================
FAIL: Doctest: perses.samplers.samplers.ExpandedEnsembleSampler
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/lib/python3.4/doctest.py", line 2187, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
nose.proxy.AssertionError: Failed doctest test for perses.samplers.samplers.ExpandedEnsembleSampler
  File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/perses-0.1-py3.4.egg/perses/samplers/samplers.py", line 509, in ExpandedEnsembleSampler
----------------------------------------------------------------------
File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/perses-0.1-py3.4.egg/perses/samplers/samplers.py", line 563, in perses.samplers.samplers.ExpandedEnsembleSampler
Failed example:
    exen_sampler.run()
Exception raised:
    Traceback (most recent call last):
      File "/home/travis/miniconda/envs/_test/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest perses.samplers.samplers.ExpandedEnsembleSampler[12]>", line 1, in <module>
        exen_sampler.run()
      File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/perses-0.1-py3.4.egg/perses/samplers/samplers.py", line 820, in run
        self.update()
      File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/perses-0.1-py3.4.egg/perses/samplers/samplers.py", line 799, in update
        self.update_state()
      File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/perses-0.1-py3.4.egg/perses/samplers/samplers.py", line 727, in update_state
        geometry_new_positions, geometry_logp_propose = self.geometry_engine.propose(topology_proposal, geometry_old_positions, self.sampler.thermodynamic_state.beta)
      File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/perses-0.1-py3.4.egg/perses/rjmc/geometry.py", line 111, in propose
        logp_proposal, new_positions = self._logp_propose(top_proposal, current_positions, beta, direction='forward')
      File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/perses-0.1-py3.4.egg/perses/rjmc/geometry.py", line 1035, in _logp_propose
        phi, logp_phi = self._propose_mtm_torsion(atom, torsion, res_mol, mol_conf, positions, r, theta, context, beta)
      File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/perses-0.1-py3.4.egg/perses/rjmc/geometry.py", line 1216, in _propose_mtm_torsion
        trial_xyzs = self.torsion_scan(bond_position, angle_position, torsion_position, internal_coordinates, proposed_torsions)
      File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/perses-0.1-py3.4.egg/perses/rjmc/geometry.py", line 1243, in torsion_scan
        from coordinate_numba import torsion_scan
    ImportError: No module named 'coordinate_numba'
```

**Comment by pgrinaway** [comment]
This is really weird. The same thing happened on travis before--but not on my local machine--then re-running the build eliminated it.

**Comment by pgrinaway** [comment]
Looks like there is [extra output](https://travis-ci.org/choderalab/perses/jobs/132995606#L806-L822) somewhere too, disrupting a doctest. I will look more into the import failure.

**Comment by pgrinaway** [comment]
Oops, just noticed you fixed that.

**Comment by jchodera** [comment]
If the NCMC tests pass,can you merge this and debug in a new PR?

**Comment by pgrinaway** [comment]
Sure

**Pull request merged**
