### PR TITLE
Changing Hybrid{sams|repex}Sampler to accept variable number of sampler states

### PR DESCRIPTION
**Pull request by hannahbrucemacdonald**
This adds an optional argument called `n_samplers` which defines the number of sampler states to run with. If `n_samplers != n_states` it will pick approximately equally spaced sampler states from the list.

The default for n_samplers is to equal n_states, but possibly we would want the defaults to be:

REPEX n_samplers = n_states
SAMS n_samplers = 1

?

### CODE REVIEW

**Comment by jchodera** [comment]
Can we distinguish between the number of samplers (replicas) and the number of thermodynamic states? The multistate samplers actually support multiple samplers (replicas) for any number of thermodynamic states for SAMS.

**Comment by jchodera** [comment]
Oh, maybe I'm confused here and you're already distinguishing between the two?

**Comment by hannahbrucemacdonald** [comment]
That’s what I’m trying to do, so n_states is the number of thermodynamic states and n_samplers is the number of sampler states.

at the moment perses would only allow number of thermodynamic == number sampler

**Comment by hannahbrucemacdonald** [comment]
So I’m changing it so Ana can start doing some sams experiments

**Comment by jchodera** [comment]
Awesome! Apologies for misunderstanding!

**Comment by hannahbrucemacdonald** [comment]
If it’s confusing maybe there is a better choice of variable names. n_windows and n_samplers or something

**Comment by jchodera** [comment]
Why not just use the sample terminology we use [in the multistate samplers themselves](https://openmmtools.readthedocs.io/en/0.18.1/api/generated/openmmtools.multistate.MultiStateSampler.html#openmmtools.multistate.MultiStateSampler.n_replicas) instead of inventing new terminology?

There, we use `n_replicas` to denote the number of replicas, and `n_states` to denote the number of thermodynamic states. The "sampler" actually refers to the whole `MutliStateSampler` object (or subclass) in this terminology, which is why I was confused about the ambiguity of using "sampler" to mean either the `MultiStateSampler` or a replica.

**Comment by hannahbrucemacdonald** [comment]
ok the error at least isn't a seg fault any more, but it's now complaining that the output file from an antechamber simulation doesn't exist...

**Comment by hannahbrucemacdonald** [comment]
Is it ok if we go ahead and merge the fix-sams branch for now? It does what it should do, and fixes at least part of the tests

**Comment by jchodera** [comment]
Yes! I can fix the remaining tests separately in #623

**Pull request merged**
