### PR TITLE
Fix geometry with amino acids

### PR DESCRIPTION
**Pull request by pgrinaway**
The main purpose of this PR (WIP, not finished yet) is to fix the issues introduced by #167 for amino acids. For small molecules, it is straightforward to fish out the residue in question and turn it into an `OEMol`, but for amino acids that are part of a protein, they need to be capped with something. I have written some code that does this with hydrogens, but I still get some errors. Will post a minimal example as the first comment in the PR.

### CODE REVIEW

**Comment by pgrinaway** [comment]
Example of code that yields errors:
```python
import simtk.openmm.app as app
def _oemol_from_residue(res):
    """
    Get an OEMol from a residue, even if that residue
    is polymeric. In the latter case, external bonds
    are replaced by hydrogens.

    Parameters
    ----------
    res : app.Residue
        The residue in question

    Returns
    -------
    oemol : openeye.oechem.OEMol
        an oemol representation of the residue with topology indices
    """
    from openmoltools.forcefield_generators import generateOEMolFromTopologyResidue
    external_bonds = list(res.external_bonds())
    new_atoms = {}
    highest_index = 0
    if external_bonds:
        new_topology = app.Topology()
        new_chain = new_topology.addChain(0)
        new_res = new_topology.addResidue("new_res", new_chain)
        for atom in res.atoms():
            new_atom = new_topology.addAtom(atom.name, atom.element, new_res, atom.id)
            new_atom.index = atom.index
            new_atoms[atom] = new_atom
            highest_index = max(highest_index, atom.index)
        for bond in res.internal_bonds():
            new_topology.addBond(new_atoms[bond[0]], new_atoms[bond[1]])
        for bond in res.external_bonds():
            highest_index += 1
            new_atom = new_topology.addAtom("H", app.Element.getByAtomicNumber(1), new_res, highest_index)
            new_atom.index = highest_index
            if bond[0].residue == res:
                new_topology.addBond(new_atoms[bond[0]], new_atom)
            else:
                new_topology.addBond(new_atoms[bond[1]], new_atom)
        res_to_use = new_res
    else:
        res_to_use = res
    oemol = generateOEMolFromTopologyResidue(res_to_use, geometry=True)
    return oemol

if __name__=="__main__":
    import openmmtools.testsystems as ts
    ala = ts.AlanineDipeptideImplicit()
    top = ala.topology
    ala_res = list(top.residues())[1] #get ALA
    mol = _oemol_from_residue(ala_res)
    print(mol)
```

**Comment by pgrinaway** [comment]
And the error:
```python
Warning: Can't assign MMFF type to atom number     8  C   on residue ALA  1
Warning: Can't assign MMFF type to atom number     9  O   on residue ALA  1
Warning: Can't assign MMFF type to atom number    10  H   on residue ALA  1
Warning: force field setup failed due to missing parameters for molecule new_res
```
with `OEOmega`. I'm wondering if I should give up on munging the topology and just manually create an `OEMol` and add in the hydrogens. I was trying to avoid duplicating code in `openmoltools` but this might be worse.

**Comment by pgrinaway** [comment]
I noticed that there's an issue with travis where it's saying there is no package named `perses`. I haven't taken a closer look yet, but if anyone knows offhand what that might be and the solution is simple, I'd be happy to put it in this PR. Otherwise, once I get the amino acid stuff sorted out, I will take a closer look.

**Comment by pgrinaway** [comment]
Well, running the `myb` example, there are a few weird things. First of all, for `Proposed mutation: GLU 103 GLU`, shouldn't there be no alchemical atoms? Yet there are two... then, it looks like the conversion of the `Residue` into an `OEMol` is still failing for amino acids... not sure what the deal there is. @juliebehr any thoughts on what could be wrong here?

**Comment by pgrinaway** [comment]
more specifically, what is wrong with this:
```python
    @staticmethod
    def _oemol_from_residue(res):
        """
        Get an OEMol from a residue, even if that residue
        is polymeric. In the latter case, external bonds
        are replaced by hydrogens.

        Parameters
        ----------
        res : app.Residue
            The residue in question

        Returns
        -------
        oemol : openeye.oechem.OEMol
            an oemol representation of the residue with topology indices
        """
        import openeye.oechem as oechem
        from openmoltools.forcefield_generators import generateOEMolFromTopologyResidue
        external_bonds = list(res.external_bonds())
        if external_bonds:
            for bond in external_bonds:
                res.chain.topology._bonds.remove(bond)
        mol = generateOEMolFromTopologyResidue(res, geometry=False)
        oechem.OEAddExplicitHydrogens(mol)
        return mol
```

**Comment by juliebehr** [comment]
What's the error it gives you here?

**Comment by pgrinaway** [comment]
Basically the same as before--it can't parameterize some atoms. But right now I'm getting "Process finished with exit code 134" for the `myb` example, which apparently means SIGABRT/some kind of assertion failure in the C++ code. I'll dig deeper for that.

**Comment by pgrinaway** [comment]
I should add that the SIGABRT happens before sampling begins, so it's not in any of the proposal functions.

**Comment by juliebehr** [comment]
I made a thing that is very ugly:
```
import simtk.openmm.app as app
def _oemol_from_residue(res):
    """
    Get an OEMol from a residue, even if that residue
    is polymeric. In the latter case, external bonds
    are replaced by hydrogens.

    Parameters
    ----------
    res : app.Residue
        The residue in question

    Returns
    -------
    oemol : openeye.oechem.OEMol
        an oemol representation of the residue with topology indices
    """
    from openmoltools.forcefield_generators import generateOEMolFromTopologyResidue
    external_bonds = list(res.external_bonds())
    for bond in external_bonds:
        print(bond)
    new_atoms = {}
    highest_index = 0
    if external_bonds:
        new_topology = app.Topology()
        new_chain = new_topology.addChain(0)
        new_res = new_topology.addResidue("new_res", new_chain)
        for atom in res.atoms():
            new_atom = new_topology.addAtom(atom.name, atom.element, new_res, atom.id)
            new_atom.index = atom.index
            new_atoms[atom] = new_atom
            highest_index = max(highest_index, atom.index)
        for bond in res.internal_bonds():
            new_topology.addBond(new_atoms[bond[0]], new_atoms[bond[1]])
        for bond in res.external_bonds():
            internal_atom = [atom for atom in bond if atom.residue==res][0]
            print('internal atom')
            print(internal_atom)
            highest_index += 1
            if internal_atom.name=='N':
                print('Adding H to N')
                new_atom = new_topology.addAtom("H2", app.Element.getByAtomicNumber(1), new_res, highest_index)
                new_atom.index = highest_index
                new_topology.addBond(new_atoms[internal_atom], new_atom)
            if internal_atom.name=='C':
                print('Adding OH to C')
                new_atom = new_topology.addAtom("O2", app.Element.getByAtomicNumber(8), new_res, highest_index)
                new_atom.index = highest_index
                new_topology.addBond(new_atoms[internal_atom], new_atom)
                highest_index += 1
                new_hydrogen = new_topology.addAtom("HO", app.Element.getByAtomicNumber(1), new_res, highest_index)
                new_hydrogen.index = highest_index
                new_topology.addBond(new_hydrogen, new_atom)
        res_to_use = new_res
        external_bonds = list(res_to_use.external_bonds())
    else:
        res_to_use = res
    oemol = generateOEMolFromTopologyResidue(res_to_use, geometry=True)
    return oemol

if __name__=="__main__":
    import openmmtools.testsystems as ts
    ala = ts.AlanineDipeptideImplicit()
    top = ala.topology
    ala_res = list(top.residues())[1] #get ALA
    print(type(ala_res))
    mol = _oemol_from_residue(ala_res)
    print(mol)
```

Basically I think it was mad because you put a hydrogen on the backbone C when it wanted an OH

**Comment by juliebehr** [comment]
Or to your more streamlined version that doesn't add atoms at all and just removes the external bonds, I'm not sure what's wrong there because it runs fine for me?

**Comment by jchodera** [comment]
I can confirm that @juliebehr's script works for me.  Adding these two lines
```python
   from openmoltools.openeye import molecule_to_mol2                                                                                                                                          
    molecule_to_mol2(mol, tripos_mol2_filename='output.mol2')                                                                                                                                  
 ```
generates a nice-looking mol2 file that seems to be correct.

**Comment by pgrinaway** [comment]
Hm. Will investigate further. Not sure what is going on, as she also said that my 2nd try works as well.

**Comment by pgrinaway** [comment]
I changed it to cycle through all of the amino acids in the LysozymeImplicit example and some of those AAs fail with @juliebehr 's code too (but not all) (for example):

```python
<Atom 2537 (N) of chain 0 residue 158 (ASP)>
Adding H to N
Warning: Can't assign MMFF type to atom number     8  CG  on residue ASP  1
Warning: Can't assign MMFF type to atom number     9  OD1 on residue ASP  1
Warning: Can't assign MMFF type to atom number    10  OD2 on residue ASP  1
Warning: force field setup failed due to missing parameters for molecule new_res
```

**Comment by pgrinaway** [comment]
full code: 
```python
import simtk.openmm.app as app
def _oemol_from_residue(res):
    """
    Get an OEMol from a residue, even if that residue
    is polymeric. In the latter case, external bonds
    are replaced by hydrogens.

    Parameters
    ----------
    res : app.Residue
        The residue in question

    Returns
    -------
    oemol : openeye.oechem.OEMol
        an oemol representation of the residue with topology indices
    """
    from openmoltools.forcefield_generators import generateOEMolFromTopologyResidue
    external_bonds = list(res.external_bonds())
    for bond in external_bonds:
        print(bond)
    new_atoms = {}
    highest_index = 0
    if external_bonds:
        new_topology = app.Topology()
        new_chain = new_topology.addChain(0)
        new_res = new_topology.addResidue("new_res", new_chain)
        for atom in res.atoms():
            new_atom = new_topology.addAtom(atom.name, atom.element, new_res, atom.id)
            new_atom.index = atom.index
            new_atoms[atom] = new_atom
            highest_index = max(highest_index, atom.index)
        for bond in res.internal_bonds():
            new_topology.addBond(new_atoms[bond[0]], new_atoms[bond[1]])
        for bond in res.external_bonds():
            internal_atom = [atom for atom in bond if atom.residue==res][0]
            print('internal atom')
            print(internal_atom)
            highest_index += 1
            if internal_atom.name=='N':
                print('Adding H to N')
                new_atom = new_topology.addAtom("H2", app.Element.getByAtomicNumber(1), new_res, highest_index)
                new_atom.index = highest_index
                new_topology.addBond(new_atoms[internal_atom], new_atom)
            if internal_atom.name=='C':
                print('Adding OH to C')
                new_atom = new_topology.addAtom("O2", app.Element.getByAtomicNumber(8), new_res, highest_index)
                new_atom.index = highest_index
                new_topology.addBond(new_atoms[internal_atom], new_atom)
                highest_index += 1
                new_hydrogen = new_topology.addAtom("HO", app.Element.getByAtomicNumber(1), new_res, highest_index)
                new_hydrogen.index = highest_index
                new_topology.addBond(new_hydrogen, new_atom)
        res_to_use = new_res
        external_bonds = list(res_to_use.external_bonds())
    else:
        res_to_use = res
    oemol = generateOEMolFromTopologyResidue(res_to_use, geometry=True)
    return oemol

if __name__=="__main__":
    import openmmtools.testsystems as ts
    lys = ts.LysozymeImplicit()
    top = lys.topology
    res_list = list(top.residues())
    for i in range(1, len(res_list)-1):
        mol = _oemol_from_residue(res_list[i])
        print(mol)
```

Does this work for you guys? I'm just trying to figure out if I've somehow messed up my Python installation.

**Comment by pgrinaway** [comment]
seems to be lys, glu, and asp that are failing in the LysozymeImplicit example. Maybe something to do with the titration states of those residues?

**Comment by juliebehr** [comment]
The atoms that are failing are unrelated to the external bonds situation, and I would think it almost certainly has to do with protonation states.  I'm not sure how to systematically know what protonation state openeye wants, though?

**Comment by jchodera** [comment]
@juliebehr is right---all those residues have a net formal charge. It could be that [the bond order perception step](https://github.com/choderalab/openmoltools/blob/master/openmoltools/forcefield_generators.py#L125-L139) is failing because the charge state is not considered.

**Comment by juliebehr** [comment]
The C-terminal residue is also failing:
```
Warning: Can't assign MMFF type to atom number    17  NZ  on residue LYS  1
Warning: Can't assign MMFF type to atom number    18  HZ1 on residue LYS  1
Warning: Can't assign MMFF type to atom number    19  HZ2 on residue LYS  1
Warning: Can't assign MMFF type to atom number    20  HZ3 on residue LYS  1
Warning: Can't assign MMFF type to atom number    21  C   on residue LYS  1
Warning: Can't assign MMFF type to atom number    22  O   on residue LYS  1
Warning: Can't assign MMFF type to atom number    23  OXT on residue LYS  1
```

the NH3s are where the positive charge is, but it's also not understanding COOxt, which is how openmm is identifying the terminal group.

**Comment by juliebehr** [comment]
I'm assuming you're skipping the N-terminus on purpose but just for the record if you weren't it would also not like that:
```
Warning: Can't assign MMFF type to atom number     1  N   on residue MET  1
Warning: Can't assign MMFF type to atom number     2  H1  on residue MET  1
Warning: Can't assign MMFF type to atom number     3  H2  on residue MET  1
Warning: Can't assign MMFF type to atom number     4  H3  on residue MET  1
```

**Comment by jchodera** [comment]
This all depends on the `bondtype` program (run by `antechamber` via [this line](https://github.com/choderalab/openmoltools/blob/master/openmoltools/forcefield_generators.py#L138)) uses atom names to determine element types for bond order perception. It's possible that we're screwing these up in the added atoms, either in the test script or in the `generateOEMolFromTopologyResidue` function. Can you guys look into this a bit?  You might just try copying the `generateOEMolFromTopologyResidue` into the test script and futzing with that.

I have checked that adding the net charge flag (`-nc -1`) to the `antechamber` call doesn't seem to change anything.

**Comment by jchodera** [comment]
It could also be my translation of [GAFF bond orders to OEMol orders](https://github.com/choderalab/openmoltools/blob/master/openmoltools/forcefield_generators.py#L142) is broken.  For example, check the -CO2 bond types here:
```
CHARGE      0.00 ( 0 )
Formula: H6 C4 N1 O4 
ATOM      1  N   MOL  2767       0.000   0.000   0.000  0.000000         1
ATOM      2  H   MOL  2767       0.000   0.000   0.000  0.000000         1
ATOM      3  CA  MOL  2767       0.000   0.000   0.000  0.000000         1
ATOM      4  HA  MOL  2767       0.000   0.000   0.000  0.000000         1
ATOM      5  CB  MOL  2767       0.000   0.000   0.000  0.000000         1
ATOM      6  HB2 MOL  2767       0.000   0.000   0.000  0.000000         1
ATOM      7  HB3 MOL  2767       0.000   0.000   0.000  0.000000         1
ATOM      8  CG  MOL  2767       0.000   0.000   0.000  0.000000         1
ATOM      9  OD1 MOL  2767       0.000   0.000   0.000  0.000000         1
ATOM     10  OD2 MOL  2767       0.000   0.000   0.000  0.000000         1
ATOM     11  C   MOL  2767       0.000   0.000   0.000  0.000000         1
ATOM     12  O   MOL  2767       0.000   0.000   0.000  0.000000         1
ATOM     13  O2  MOL  2767       0.000   0.000   0.000  0.000000         1
ATOM     14  HO  MOL  2767       0.000   0.000   0.000  0.000000         1
ATOM     15  H2  MOL  2767       0.000   0.000   0.000  0.000000         1
BOND    1    1    2    1      N    H
BOND    2    3    4    1     CA   HA
BOND    3    5    6    1     CB  HB2
BOND    4    5    7    1     CB  HB3
BOND    5    1    3    1      N   CA
BOND    6    3    5    1     CA   CB
BOND    7    5    8    1     CB   CG
BOND    8    8    9    9     CG  OD1
BOND    9    8   10    9     CG  OD2
BOND   10    3   11    1     CA    C
BOND   11   11   12    2      C    O
BOND   12   11   13    1      C   O2
BOND   13   13   14    1     O2   HO
BOND   14    1   15    1      N   H2
```

**Comment by juliebehr** [comment]
What's wrong with the bond orders?

**Comment by jchodera** [comment]
`ASP` seems to fail with
```
<Atom 2537 (N) of chain 0 residue 158 (ASP)>
Adding H to N
/tmp/debug/tmpY_0tGJ
Warning: Can't assign MMFF type to atom number     8  CG  on residue ASP  1
Warning: Can't assign MMFF type to atom number     9  OD1 on residue ASP  1
Warning: Can't assign MMFF type to atom number    10  OD2 on residue ASP  1
Warning: force field setup failed due to missing parameters for molecule new_res
```
Here's the `mol2` file for an ASP:
```
@<TRIPOS>MOLECULE
new_res
   15    14     0     0     0
SMALL
NO_CHARGES

@<TRIPOS>ATOM
      1 N1          0.0000    0.0000    0.0000 N.3       1 MOL         0.0000
      2 H1          0.0000    0.0000    0.0000 H         1 MOL         0.0000
      3 C1          0.0000    0.0000    0.0000 C.3       1 MOL         0.0000
      4 H2          0.0000    0.0000    0.0000 H         1 MOL         0.0000
      5 C2          0.0000    0.0000    0.0000 C.3       1 MOL         0.0000
      6 H3          0.0000    0.0000    0.0000 H         1 MOL         0.0000
      7 H4          0.0000    0.0000    0.0000 H         1 MOL         0.0000
      8 C3          0.0000    0.0000    0.0000 C.2       1 MOL         0.0000
      9 O1          0.0000    0.0000    0.0000 O.co2     1 MOL         0.0000
     10 O2          0.0000    0.0000    0.0000 O.co2     1 MOL         0.0000
     11 C4          0.0000    0.0000    0.0000 C.2       1 MOL         0.0000
     12 O3          0.0000    0.0000    0.0000 O.2       1 MOL         0.0000
     13 O4          0.0000    0.0000    0.0000 O.3       1 MOL         0.0000
     14 H5          0.0000    0.0000    0.0000 H         1 MOL         0.0000
     15 H6          0.0000    0.0000    0.0000 H         1 MOL         0.0000
@<TRIPOS>BOND
     1    1    2 1
     2    3    4 1
     3    5    6 1
     4    5    7 1
     5    1    3 1
     6    3    5 1
     7    5    8 1
     8    8    9 5
     9    8   10 5
    10    3   11 1
    11   11   12 2
    12   11   13 1
    13   13   14 1
    14    1   15 1
```
It suggests that Tripos types `C.2` and `O.co2` are having trouble being typed for `omega`.
Those `CG-OD1` and `CG-OD2` bonds are Tripos bond type 5, which isn't a valid Tripos bond type.  The [OpenEye bond order](https://docs.eyesopen.com/toolkits/cpp/oechemtk/OEChemClasses/OEBondBase.html#OEChem::OEBondBase::SetOrder) doesn't use these either.  I think I had selected the [bond order atom map](https://github.com/choderalab/openmoltools/blob/master/openmoltools/forcefield_generators.py#L142) based on the [`OEKekulize` bond orders](https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemFunctions.html#OEChem::OEKekulize), but this may be inappropriate here.

**Comment by jchodera** [comment]
I think I've fixed this in https://github.com/choderalab/openmoltools/pull/207

**Comment by jchodera** [comment]
That fix has been merged in `openmoltools`.  Try now?

**Comment by pgrinaway** [comment]
Sweet! Looks like the Lysozyme example is running fine now!

**Comment by pgrinaway** [comment]
I thnik this is basically good to go. Thanks @jchodera @juliebehr !

**Comment by jchodera** [comment]
I'm not sure why the travis tests fail with `Failure: ImportError (No module named perses) ... ERROR
Failure: ImportError (No module named perses) ... ERROR`, but local nosetests fail with lots of errors like this:
```
======================================================================
ERROR: Testing MultiTargetDesign sampler with AlanineDipeptideTestSystem transfer free energy from vacuum -> implicit
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/samplers/samplers.py", line 1084, in run
    self.update()
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/samplers/samplers.py", line 1066, in update
    self.update_samplers()
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/samplers/samplers.py", line 1030, in update_samplers
    sampler.update()
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/samplers/samplers.py", line 946, in update
    self.update_sampler()
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/samplers/samplers.py", line 914, in update_sampler
    self.sampler.update()
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/samplers/samplers.py", line 791, in update
    self.update_state()
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/samplers/samplers.py", line 723, in update_state
    geometry_new_positions, geometry_logp_propose  = self.geometry_engine.propose(topology_proposal, geometry_old_positions, self.sampler.thermodynamic_state.beta)
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/rjmc/geometry.py", line 98, in propose
    logp_proposal, new_positions = self._logp_propose(top_proposal, current_positions, beta, direction='forward')
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/rjmc/geometry.py", line 183, in _logp_propose
    growth_system = growth_system_generator.create_modified_system(top_proposal.new_system, atom_proposal_order.keys(), growth_parameter_name, reference_topology=top_proposal.new_topology)
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/rjmc/geometry.py", line 886, in create_modified_system
    self._determine_extra_torsions(modified_torsion_force, reference_topology, growth_indices)
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/rjmc/geometry.py", line 915, in _determine_extra_torsions
    residue = atoms[growth_indices[0].idx].residue
IndexError: list index out of range
```

**Comment by pgrinaway** [comment]
Oh, I see. There are no alchemical atoms. In that case, should `GeometryEngine` just return the same positions as it was given?

**Comment by jchodera** [comment]
I think so! I wonder why the test has no alchemical atoms defined...

**Comment by pgrinaway** [comment]
Ok. It's proposing `ALA` to `ALA`, so presumably the atom map is complete, with no new atoms to propose.

**Comment by pgrinaway** [comment]
I'd assume we'd just want to eliminate proposals to remain in the current state, at least for now?

**Comment by jchodera** [comment]
Actually, it doesn't seem easy to exclude self-transitions without major refactoring of the `PointMutation` class since we allow specifications of tuples of mutations.  Instead, it would probably be better to have `GeometryEngine.propose()` check for self-transitions and return the same coordinates and `logP = 0`.

**Comment by pgrinaway** [comment]
Yeah. Just did that! Looks like the test works for me now.

**Comment by jchodera** [comment]
Whoops, I may have just fucked this up with a commit that did the same thing.

**Comment by jchodera** [comment]
Phew, looks like changes are complementary.  Feel free to merge!

**Comment by jchodera** [comment]
Hm  If you run `python perses/tests/testsystems.py`, the `kinase-inhibitors-vacuum-geometry-proposals.pdb` is still looking like it has disastrous geometry proposals.

**Comment by pgrinaway** [comment]
Hm, running through the `GeometryEngine` test alone, it seems the problematic component in most cases right after proposal is `NonbondedForce`, which is consistent with what I am seeing in PDBs (most egregious example being part of the molecule sticking through a ring). Do you have another example?

As a side note, can we avoid committing to another's PR without asking on the discussion first? Otherwise it could get confusing and counterproductive.

**Comment by jchodera** [comment]
Sorry about that. Totally my fault. I got confused about which branch I was on and realized too late that I was in the wrong one.

**Comment by jchodera** [comment]
Did you take a look at the PDB file of the proposals generated by running the kinase inhibitor test?

**Comment by jchodera** [comment]
I think that kinase inhibitor test was working before, so I am confused why the additions for amino acids causes it to generate really poor conformations again.  Unless something is screwed up with the PDB writing?

**Comment by pgrinaway** [comment]
Running now. Yeah, I'm not sure what the deal with that is. The additions for the amino acids basically just return the result of `generateOEMolFromTopologyResidue` without any extra fiddling.

**Comment by pgrinaway** [comment]
Wow, those geometries are really crap. Interestingly, running the `GeometryEngine` test alone after ~1000 steps of VV produces fairly decent geometries. I wonder if the "always accept" thing is enabled? But then I guess the initial energies would be much higher.

**Comment by jchodera** [comment]
I'm very confused since the atom-by-atom PDBs looked great.

**Comment by jchodera** [comment]
Did you add a test to make sure all amino acids could interconvert?  What is it called?

**Comment by jchodera** [comment]
I'm trying to fix the proposal issues here:
https://github.com/choderalab/perses/pull/170

I think the issues were 
* torsion restraint phase was in wrong domain
* MCSS match criteria still needs improvement

**Comment by pgrinaway** [comment]
Ok. Will take a look after lunch.

**Comment by jchodera** [comment]
Please do. Would still love to have something to show on Wed morning.

**Comment by pgrinaway** [comment]
Ok. In the future it would be good to mention things like this when we have meetings about what needs to get done and when.

**Comment by jchodera** [comment]
> Ok. In the future it would be good to mention things like this when we have meetings about what needs to get done and when.

Sure, when I know ahead of time, I'll give advance warning.  This is mostly just a "would be nice" desire to show something neat at the end of my talk, rather something that was planned.

**Comment by pgrinaway** [comment]
Running a test based on @juliebehr 's `PointMutationEngine` test, that generates mutations from all amino acids to all others locally right now. It is also pushed to the PR.

**Comment by jchodera** [comment]
Great!

**Comment by pgrinaway** [comment]
Is it useful to have this test run on an actual protein, or should it just run on an individual peptide? I realized that it's running on an actual protein right now, which could be good to test, but also takes a lot longer and might conflate other issues (such as the proposals resulting in a very high `NonbondedForce` potential).

**Comment by jchodera** [comment]
Can you just try a blocked peptide?  We just need to ensure that all possible interconversions work.

**Comment by pgrinaway** [comment]
Yep, just pushed that.

**Comment by jchodera** [comment]
Great. We can overhaul the testing more broadly to focus on fast tests in another PR---I realize that any tests involving actual proteins are pretty slow.

**Comment by pgrinaway** [comment]
Yeah. Just realized this test starting from `AlanineDipeptide` only tests `ALA` -> [amino acid]. Will fix now.

**Comment by juliebehr** [comment]
With the ```protein = False``` flag, you're only ever mutating from ALA to the other residues -- is this what you want?

**Comment by juliebehr** [comment]
Ah, never mind.

**Comment by pgrinaway** [comment]
Sorry, I think I need to give this test a bit more thought. I need decent starting geometries for the test, so I'll need to build terminally-blocked amino acids for each AA. Should be quick, but just an update on the status.

**Comment by jchodera** [comment]
You can use `leap` to do this if you want.

Examples:
* https://github.com/choderalab/openmm-constph/blob/master/calibration-implicit/setup-blocked-amino-acids.leap.in
* https://github.com/choderalab/mcce-charges/blob/master/his-test-peptides/setup.leap.in

@juliebehr may also have some spiffy OpenMM `ForceField` way of doing this.

**Comment by pgrinaway** [comment]
Oh, that's way easier than building them in OpenEye. Nice, thanks.

**Comment by jchodera** [comment]
Alternatively, you can start with `ACE-ALA-NME` and just do a sequence of perturbations that carry you through all possible `NxN` transformations, e.g.
`ALA > VAL > LEU > GLY > ...`

**Comment by pgrinaway** [comment]
Well, that's what I was going to do. But I don't want to start a geometry test from a previous proposal (potentially causing accumulating bad proposals). And then I'd need to do some atom mapping to get a new omega geometry. Alternatively, I could write a `generateOEMolFromTopologyResidue` function that includes the `ACE-x-NME`. But I had imagined it'd be better to perform minimal futzing with what would be found in a simulation.

**Comment by pgrinaway** [comment]
Ok, the test is now running with each blocked amino acid -> each other blocked amino acid.

**Comment by jchodera** [comment]
Awesome!

**Comment by pgrinaway** [comment]
hm, looks like there are still occasional malformed rings... (for instance, in TRP->TYR).

**Comment by pgrinaway** [comment]
Otherwise, the only problems that ever occur are in the `NonbondedForce`.

**Comment by jchodera** [comment]
Can you turn on the [`write_proposal_pdb` option](https://github.com/choderalab/perses/blob/geometry-amino-acids/perses/rjmc/geometry.py#L78) and see if the issue with the initial scaffold alignment or the atom-by-atom ring growth?

**Comment by pgrinaway** [comment]
Taking a look. I think it's the atom-by-atom ring growth.

**Comment by jchodera** [comment]
It's possible I have the domain thing wrong.  The need to add `pi` to the phase is weird, so I wonder if that is an issue.

**Comment by jchodera** [comment]
Where are we at with this?

**Comment by pgrinaway** [comment]
Well, I think this PR is basically done. Its purpose was to allow amino acids to be proposed by `GeometryEngine`. There is also a test case for the amino acids. We should probably resolve the torsion stuff in another PR.

**Comment by jchodera** [comment]
Great!  Go ahead and merge then!

**Pull request merged**
