### PR TITLE
Fix VV and GHMC NCMC

### PR DESCRIPTION
**Pull request by jchodera**
Lots of fixes for VV and GHMC NCMC!

### CODE REVIEW

**Comment by jchodera** [comment]
Wow, I wonder if I accidentally brought in some other changes.

**Comment by jchodera** [comment]
I think there are a few more logic flow issues left over from reworking the integrators into something you have to call `nsteps` times.  Sorting those out now. Don't merge yet!

**Comment by jchodera** [comment]
I've refactored the common code between `NCMCVVAlchemicalIntegrator` and `NCMCGHMCAlchemicalIntegrator` into an `NCMCAlchemicalIntegrator` base class and vastly simplified the code for the VV and GHMC NCMC integrators.  The NCMC tests pass on my machine.

Let's see if the tests pass here and then you can review and merge, @pgrinaway!

Wait...why is travis not running?

**Comment by jchodera** [comment]
Ah. Travis isn't running because this is a PR into your branch, @pgrinaway

**Comment by jchodera** [comment]
OK, so you'll need to review and merge and take things from here, @pgrinaway.

**Comment by pgrinaway** [comment]
Thanks so much! will review and merge!

**Comment by pgrinaway** [comment]
This looks great! Thanks a million!

**Pull request merged**
