### PR TITLE
Migrate multitopology alchemical stuff to examol

### PR DESCRIPTION
**Pull request by jchodera**
* Moved nosetests from conda recipe to `.travis.yml`
* Added encrypted `oe_license.txt` using the travis [encrypted files](http://docs.travis-ci.com/user/encrypting-files/) mechanism

### CODE REVIEW

**Comment by jchodera** [comment]
* Changed travis-ci service to user `jchodera`

**Comment by pgrinaway** [comment]
Hm, don't we need YANK for its alchemical stuff?

**Comment by jchodera** [comment]
The plan in #4 was to have a separate `perses/annihilation/` module to handle alchemical annihilation.  That's probably the best plan for now, since everything can be self-contained.

I've actually been wanting to migrate `alchemy.py` *out* of YANK into its own repo so it can be more thoroughly tested on its own.  I wonder if it makes the most sense to have this in a separate `alchemy` repo or to put it here (and possibly rename `perses` to `alchemy`).  Alternatively, we can have an `alchemy` repo that also pulls in `dualtopology` and `multitopology`, and just keep `perses` for the RJMC stuff.

Thoughts?

**Comment by pgrinaway** [comment]
>I've actually been wanting to migrate alchemy.py out of YANK into its own repo so it can be more thoroughly tested on its own. 

I think this makes a lot of sense. We may also have additional applications that need to be able to make alchemical modifications--there's no need to induce a dependency on YANK there.

As to the rest, I think it would actually make sense to have `perses` just contain the RJMC stuff, alchemy to be separate, and the multitopology stuff to be separate as well (since we have different collaborations for that). It might make planning for each of the projects a bit easier, too.

**Comment by jchodera** [comment]
> As to the rest, I think it would actually make sense to have perses just contain the RJMC stuff, alchemy to be separate, and the multitopology stuff to be separate as well (since we have different collaborations for that). It might make planning for each of the projects a bit easier, too.

I think this sounds logical to me.

How about this for a plan:
* I'll set up a new `alchemy` repo as a new home for the working alchemical annihilation stuff from YANK.  Tests should all pass for this, and I can add even more testing since we can run travis for longer than when we had to test with the rest of YANK.
* I'll create a `multitopology` repo and migrate our (currently mostly broken) code from `perses` there.  We can work on getting that working again separately.
* That will leave the RJMC stuff inside `perses`, where all tests should pass.

**Comment by pgrinaway** [comment]
Sounds good! What about putting multitopology stuff in `examol`?

Thanks!

**Comment by jchodera** [comment]
> Sounds good! What about putting multitopology stuff in examol?

Great idea!  Working on that now.

**Comment by jchodera** [comment]
Alchemy stuff is now going here, by the way: https://github.com/choderalab/alchemy

**Comment by jchodera** [comment]
Multitopology stuff has now been migrated to [`examol`](http://github.com/choderalab/examol)

**Comment by jchodera** [comment]
OK, looks like we're good again.  Merging.

Can you take over now, @pgrinaway?

**Comment by pgrinaway** [comment]
Yep, sounds good!

**Pull request merged**
